### ISSUE TITLE
查看年度报告的时候无法查看完整的聊天记录

### ISSUE THREAD

**Issue by kawenli** [LC044/WeChatMsg#102]
**是否检查过issues没有相同问题**
检查过没有
**bug描述**
对比微信聊天记录查看会有不全的内容,电脑版微信聊天能到2020年,而"留痕"只能查看到2023年7月的聊天记录,再往前就无法查看

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/52768098/f81eeca6-ab11-4ffe-b074-dcb1f503746d)
![image](https://github.com/LC044/WeChatMsg/assets/52768098/7b467ed4-cf24-4113-b97c-e8f86e5c82bb)

**是否可复现**
可以
**运行环境:**
 - OS: [e.g. Win10]
 - Python版本:
 - 软件版本: 0.2.6
 - 微信版本:3.9.8.15

**Comment by LC044** [comment]
查看一下是该好友的聊天记录不全还是所有好友的聊天记录都不全，或者重启微信重新解密试一下

**Comment by Chenmo1212** [comment]
是所有的好友聊天记录都不全，貌似只能解密近几个月的，时间稍微长一点就不太行了。

**Comment by LC044** [comment]
> 是所有的好友聊天记录都不全，貌似只能解密近几个月的，时间稍微长一点就不太行了。

试试最新版，刚发布了，还不行的话反馈一下

**Comment by Chenmo1212** [comment]
现在能成功导出了。消息记录是全的，表情包也有下载。但是图片视频音频什么的还是处于空白的状态。

**Comment by Chenmo1212** [comment]
抱歉抱歉，0.2.8版本的图片，视频，音频都能正确下载了。

此外Mark一个小问题，上周的代码与这周的代码有个重要的变化app文件夹下的ui组件文件夹之前是“Ui”，这周是“ui”。因此在重新pull下来最新代码的时候，会自动忽略掉大小写，从而导致运行python main.py时会提示无法引入app.ui。
