### ISSUE TITLE
敏感信息

### ISSUE THREAD

**Issue by wanglaojianlibao** [LC044/WeChatMsg#103]
https://github.com/LC044/WeChatMsg/blob/d7ebe9c1d5ab6b09fe2689d7ba8d46b62827e55c/app/decrypt/decrypt.py#L122

老哥太不小心了

**Comment by handsomeBB** [comment]
这是他本地的，怕什么

**Comment by wanglaojianlibao** [comment]
之前 wx 暴露过 bug，能通过 wxid 能直接查到对应的手机号。。。不担心就算了
