### ISSUE TITLE
可否直接提供qq聊天记录，对聊天记录进行分析

### ISSUE THREAD

**Issue by nanyi-z** [LC044/WeChatMsg#105]
提供 QQ 聊天记录，例如 TXT 文件。
对聊天记录进行分析，聊天记录包含聊天的发生时间和聊天内容。
词云需要进行条件筛选，将聊天时间、无意义的介词连词进行删除。
对聊天内容进行情感判断等。

**Comment by LC044** [comment]
可以实现但不在该项目开发范围之内
