### ISSUE TITLE
年度报告为所有聊天记录的累计报告

### ISSUE THREAD

**Issue by uniform641** [LC044/WeChatMsg#110]
**是否检查过issues没有相同问题**
是
**bug描述**
年度报告为所有聊天记录的累计报告

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/45708157/523ae468-af29-4095-be0c-01b1b52637fe)
今年几乎没有聊天

**是否可复现**
是，可稳定复现

**运行环境:**
 - OS: Win10
 - Python版本: 3.11.7
 - 软件版本: 0.2.8
 - 微信版本: 3.9.8.15

**Additional context**

**Comment by LC044** [comment]
已解决
