### ISSUE TITLE
请问可以导出更久远的聊天记录吗？

### ISSUE THREAD

**Issue by dianso** [LC044/WeChatMsg#116]
**是否检查过issues没有相同问题**

**bug描述**
我和媳妇的导出了，我看是2020-2023的聊天记录，之前2016开始的没有导出。

感谢，已star

**报错截图**

**是否可复现**

**运行环境:**
 - OS: WIN11
 - Python版本:3
 - 软件版本: 最新
 - 微信版本:最新

**Additional context**

**Comment by LC044** [comment]
你看看你的软件目录下app/database/msg/下面的MSG0.db,MSG1.db······，这些db文件有多少，可以截个图给我

**Comment by LC044** [comment]
试试最新版本能否解决该问题
