### ISSUE TITLE
解密使用发现少了很多的聊天记录

### ISSUE THREAD

**Issue by yuantao1994** [LC044/WeChatMsg#117]
在微信里面可以看到聊天记录，但是软件里面看不到。
使用后发现有部分人有聊天记录但是不全，部分人一条记录都没有这部分人在微信里面看得到聊天记录的。

![image](https://github.com/LC044/WeChatMsg/assets/10337433/081286e5-f940-4e71-b73a-ef1a14d15486)

![image](https://github.com/LC044/WeChatMsg/assets/10337433/860acf97-9471-486d-bc9a-d509355e8629)

**Comment by LC044** [comment]
工具里看不到可以试试导出HTML，导出的应该是全的

**Comment by songjingcn** [comment]
需要首东上拉刷新，似乎跟微信一样，某个时间节点的信息不是立刻加载出来，需要上拉才能加载。

**Comment by LC044** [comment]
试试新版能否解决该问题
