### ISSUE TITLE
群聊信息能导出吗？

### ISSUE THREAD

**Issue by cocomany** [LC044/WeChatMsg#119]
解密聊天记录后，没看到群聊的记录。期待支持导出群聊记录。

**Comment by edica02** [comment]
exe文件不能查看群聊的记录。但是可以使用数据库软件，查看解密的db文件。就可以导出群聊天记录了。

**Comment by EliYip** [comment]
貌似需要PC微信将群聊保存到通讯录，然后就可以查看和导出了。

**Comment by LC044** [comment]
已支持
