### ISSUE TITLE
解密数据库的时候报错

### ISSUE THREAD

**Issue by rabbit-zhu** [LC044/WeChatMsg#124]
在解密数据库的时候，无法自动带出信息
填写信息后，无法获取密钥

![image](https://github.com/LC044/WeChatMsg/assets/55568349/d345df18-5458-443e-ac06-95b042e8608a)

![image](https://github.com/LC044/WeChatMsg/assets/55568349/616ff88d-880a-4f6e-a59a-7484e3bf1623)

**Comment by yw199569** [comment]
<img width="720" alt="Snipaste_2023-12-13_11-33-29" src="https://github.com/LC044/WeChatMsg/assets/28047876/5adb8c40-6f81-44b3-ac1d-52169c3b887e">
我这个也是

**Comment by LC044** [comment]
试试最新代码能否解决该问题
