### ISSUE TITLE
无法获取聊天图片

### ISSUE THREAD

**Issue by akashiwest** [LC044/WeChatMsg#126]
**bug描述**
微信软件中聊天有图片，但是WeChatMsg软件无法获取聊天中的图片，导出html也不行（ps.我的微信新安装了不久）

我看了下微信安装目录，发现 **C:\Users\Admin\Documents\WeChat Files\wxid_mycode\FileStorage\Image** 目录大小为0Kb，内部只有空文件夹 Thumb；
但是在 **C:\Users\Admin\Documents\WeChat Files\wxid_mycode\FileStorage\MsgAttach** 里面有很多以md5字符命名的文件夹，我猜测是以每个聊天记录分类的。点进去 **\md5Code\Image\2023-12** 发现存在 .dat 后缀的图片，我用python写了个脚本解密出来发现就是聊天图片。不知道是不是新版本的微信改位置了？还是说我微信的问题？希望大佬看一下

**报错截图**
<img width="869" alt="屏幕截图 2023-12-13 121803" src="https://github.com/LC044/WeChatMsg/assets/89328105/ca7ec893-a516-4c0a-a90d-361963f41eab">
<img width="980" alt="屏幕截图 2023-12-13 121511" src="https://github.com/LC044/WeChatMsg/assets/89328105/64ae0cdd-b0e6-482a-a06b-08aca4067823">
<img width="1158" alt="屏幕截图 2023-12-13 121356" src="https://github.com/LC044/WeChatMsg/assets/89328105/70c54c0e-5315-4def-84d1-0b91a22ba12d">
<img width="646" alt="屏幕截图 2023-12-13 121324" src="https://github.com/LC044/WeChatMsg/assets/89328105/c25fe88a-821f-4d7f-9566-cf4ee9503b53">

**运行环境:**
 - OS: Windows11 22H2
 - Python版本: 3.10.7
 - 软件版本:  MemoTrace-0.2.7
 - 微信版本: 3.9.8.15

**Comment by LC044** [comment]
0.2.8将修复该问题，可以等待发布最新版，也可自行构建环境运行代码

**Comment by akashiwest** [comment]
好的谢谢。另外再麻烦问下导出html的时候聊天内的图片是即时从wxid文件夹中拷贝出来的吗？我想的是直接备份一下生成的app文件夹，然后如果我要重装系统后面再想看聊天记录的时候图片会被保留吗？

**Comment by LC044** [comment]
导出的数据后期不依赖于任何其他东西，备份之后可随时查看，图片视频语音都是单独复制出来的，把某个联系人的文件夹单独保存即可

**Comment by LC044** [comment]
已解决
