### ISSUE TITLE
解锁VIP才能查看是因为。。。还没开发完么

### ISSUE THREAD

**Issue by lixiangyang9b** [LC044/WeChatMsg#133]
如题。。。辛苦开发大佬们了

**Comment by HHaoWang** [comment]
看了一下代码里边确实没有截图里的内容，估计还在开发吧

**Comment by EliYip** [comment]
标记为VIP的内容的确是因为没有开发完，作者还是学生。

麻烦关闭这条issue，减少作者的负担，感谢。

**Comment by LC044** [comment]
> 标记为VIP的内容的确是因为没有开发完，作者还是学生。
> 
> 麻烦关闭这条issue，减少作者的负担，感谢。

不如赞助一下加加速😏
