### ISSUE TITLE
QSvgIOHandler: QImage allocation failed (size 1024 x 1024)

### ISSUE THREAD

**Issue by eddiechowx** [LC044/WeChatMsg#134]
**是否检查过issues没有相同问题**
是
**bug描述**
解密成功过后再次运行软件 loading 报错 QSvgIOHandler: QImage allocation failed (size 1024 x 1024)，闪退，用管理员模式依然如此，重复多次基本上是这个错，偶尔发现一次 libpng out of memory，猜测是不是我的聊天记录文件太大导致？我迁移了差不多 9G 的聊天记录，太大了导致解析不了内存溢出？
**报错截图**
<img width="473" alt="企业微信20231214-111546@2x" src="https://github.com/LC044/WeChatMsg/assets/11539740/5b5ec918-744e-4096-8ab7-8fc9ee4b2aef">

**是否可复现**
 是
**运行环境:**
 - OS: win11（macOS 14.1 M1 Pro 下的 VMware Fusion 虚拟机安装的）
 - Python版本: 3.10.11
 - 软件版本: 0.2.8
 - 微信版本: 3.9.8.15

**Comment by LC044** [comment]
能通过debug检测到是哪个svg加载出错吗

**Comment by eddiechowx** [comment]
> 能通过debug检测到是哪个svg加载出错吗

额，，，直接运行的 0.2.8 exe，可以开启 debug 模式吗？

**Comment by LC044** [comment]
应该是/app/resources/icons/default_avatar.svg加载出错，你可以运行源码把这个换成尺寸较小的图片，记得利用工具将qrc转为py文件

**Comment by LC044** [comment]
可以用记事本打开这个svg图片把1024改成64，然后利用工具将qrc转为py文件，可自行百度

**Comment by eddiechowx** [comment]
试了半天是系统内存不足的问题导致的；我的 win11 是虚拟机，前面只配了 8G 内存，后面升到 16G，再运行 exe，开了任务管理器看内存占用情况，加载9G+的聊天记录，exe 的内存占用一路飙到 10G+，扛住了，页面正常显示了

**Comment by LC044** [comment]
windows系统只需要四五百兆内存就行了，不知道是不是虚拟机导致的内存占用飙升

**Comment by eddiechowx** [comment]
会不会和消息记录的大小相关？消息记录越大，第一次 loading 的时候就耗的内存越多？我迁移的消息刚好 9G+，然后和监测的 exe 进程的内存占用峰值 10G+有点相近，不过正常 loading 出来过后，内存占用就回落了，稳定在 1.5G 的样子
