### ISSUE TITLE
[功能建议] 导出群聊记录时为群成员添加昵称

### ISSUE THREAD

**Issue by EliYip** [LC044/WeChatMsg#135]
在v0.2.8中，即便我通过*将群聊保存到通讯录*这个操作使其可以被MemoTrace识别，但是导出的时候并没有被程序进行正确的处理，主要体现在程序默认将我和所有其他人视为两个对象，因此没有产生区分，渲染后的html文件中，所有其他成员均为同一个头像。

我之前有导出mac上微信数据库的经验，其中的sqlite3数据中有一列`msgContent`，其中会以群成员微信ID+换行+消息内容的形式记录群成员消息，例如：

```
wxid_cmlvfrye4f5322:
语音聊吧。  语音识别难
```

就代表`wxid_cmlvfrye4f5322`这个人发送了这条消息，而如何找到这个人，我没有实操过，参考v2ex上的[这篇文章](https://www.v2ex.com/t/466053)中的：

> 试了一下，还有个 wccontact db，里面是所有联系人，联系人的 m_nsUsrName 做一次 md5 后对应聊天记录 db 里以 Chat_xxx 开头的表。
> 终于可以把我一些有用的记录导出来了，谢谢~

我不确定是否有其他更巧妙的办法，也希望大佬们能提供意见。

**Comment by LC044** [comment]
已支持
