### ISSUE TITLE
重启后加载sqlite报错

### ISSUE THREAD

**Issue by purple-WL** [LC044/WeChatMsg#136]
win10，python 3.8，最新版代码

报错内容如下:
Exception: no such table: ContactHeadImg1
Traceback (most recent call last):
..........
sqlite3.OperationalError: no such table: ContactHeadImg1
2023-12-14 16:26:55,598 - main.py[line:70] - ERROR: None

**Comment by tan-huang** [comment]
win11，python3.11，最新版

在手机端显示迁移成功后，电脑微信提示崩溃。
重启电脑微信后，重新运行留痕软件，闪退。
退出电脑微信后台，再次运行微信，提示更新并允许，等待片刻后再次运行微信，运行留痕软件，闪退。
![image](https://github.com/LC044/WeChatMsg/assets/79386425/24b152f2-bf0b-40b2-88ee-d028eaa5cae6)

**Comment by LC044** [comment]
> win11，python3.11，最新版
> 
> 在手机端显示迁移成功后，电脑微信提示崩溃。 重启电脑微信后，重新运行留痕软件，闪退。 退出电脑微信后台，再次运行微信，提示更新并允许，等待片刻后再次运行微信，运行留痕软件，闪退。 ![image](https://private-user-images.githubusercontent.com/79386425/290463258-24b152f2-bf0b-40b2-88ee-d028eaa5cae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDQ1OTUsIm5iZiI6MTcwMjU0NDI5NSwicGF0aCI6Ii83OTM4NjQyNS8yOTA0NjMyNTgtMjRiMTUyZjItYmYwYi00MGIyLTg4ZWUtZDAyOGVhYTVjYWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA4NTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjBlMWQ0ZGYyOGZmMTliYjI0OWRjZmM4M2ViNmMxNGVhMzliMTc4YWM5NWZlNGIwMTVkMWRlMjM5ZDdkNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kzeh2j0-mGrsBEeM8A5S0Re4Uyn-VMNn0JVldF876uc)

把app/database/msg文件夹删了重新试试

**Comment by LC044** [comment]
微信更新到3.9.8.15

**Comment by LC044** [comment]
解密的时候没有报密钥错误吗

**Comment by tan-huang** [comment]
> 解密的时候没有报密钥错误吗
win10，python3.11，留痕0.2.8，微信版本3.9.6.33（未更新最新版）

第一次启动软件时会提示“密钥”相关字样，忘记是啥了，然后按教程勾选并获取信息则没有报错。刚刚删除msg文件夹后已正常运行，目前可进入聊天子菜单。谢谢您LC044！（未更新微信）。

**Comment by purple-WL** [comment]
删除msg文件后可以了，什么时候出macos版本
