### ISSUE TITLE
导出csv出现乱码

### ISSUE THREAD

**Issue by aaayun** [LC044/WeChatMsg#137]
**是否检查过issues没有相同问题**

是

**bug描述**
导出全部聊天记录为csv时出现中文乱码

**报错截图**
![1702539637638](https://github.com/LC044/WeChatMsg/assets/17832044/91509688-0301-4694-b9b4-46fad5249f25)

**是否可复现**
是
**运行环境:**
 - OS: [e.g. Win10]
 - Python版本:3.12.1
 - 软件版本: 0.2.8
 - 微信版本:3.9.8.15

**Comment by LC044** [comment]
麻烦提交issue的时候仔细查看文档 #40

**Comment by wudg** [comment]
同问题
是否可复现
是
运行环境:

OS: [e.g. Win10]
Python版本:3.10.9
软件版本: 0.2.8
微信版本:3.9.8.15
