### ISSUE TITLE
No such file or directory: 'app/DataBase/Msg/MSG0.db'

### ISSUE THREAD

**Issue by wzgrx** [LC044/WeChatMsg#138]
**是否检查过issues没有相同问题**

**bug描述**

**报错截图**

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 0.28
 - 微信版本:最新

**Additional context**

log
ok 本次加载用了 0.7039506435394287 s
0
1
0
================================
[+]  version: 3.9.8.15

Traceback (most recent call last):
  File "app\ui\tool\pc_decrypt\pc_decrypt.py", line 181, in btnExitClicked
  File "shutil.py", line 434, in copy2
  File "shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'

**Comment by LC044** [comment]
应该是密钥出错了

**Comment by wzgrx** [comment]
> 应该是密钥出错了

密钥为None，怎么解决

**Comment by GoForceX** [comment]
是不是可以试试 #144

**Comment by LC044** [comment]
> 是不是可以试试 #144

别试了，我已经把他的代码合进去了，拉取最新代码试试，并且也支持导出群聊了

**Comment by wzgrx** [comment]
> > 是不是可以试试 #144
> 
> 别试了，我已经把他的代码合进去了，拉取最新代码试试，并且也支持导出群聊了

厉害厉害，可以用了，非常感谢

**Comment by wzgrx** [comment]
> 是不是可以试试 #144

最新代码解决了，谢谢
