### ISSUE TITLE
能否添加已解散或退出群聊的聊天记录

### ISSUE THREAD

**Issue by aaayun** [LC044/WeChatMsg#140]
RT，有些群聊是已经解散或退出的，但是聊天记录还存在，能否添加存储这部分群聊的聊天记录

**Comment by TickToTock** [comment]
同求，有些群是群主自己解散的，微信官方版无法迁移这部分的聊天记录，但群的聊天内容和图片视频音频都还保存在手机中。我尝试用MemoTrace-0.2.8，发现可以从手机迁移到PC版微信，在软件中能读取到那个已经解散的群，但是导出html发现，图片视频这些内容都没有被正确导出。您的软件是目前唯一一款能导出部分解散群记录的，能不能后续再更新一下，支持这个功能。我因为这个问题迟迟不敢换手机。

**Comment by LC044** [comment]
试试最新版

**Comment by TickToTock** [comment]
> 试试最新版

您好，我使用最新的1.0版本，发现原来能看到并导出的群不见了。该群记录一直完整的在我安卓手机上，后来群主解散群聊，这个记录就只在手机，PC微信无法导出已经解散的群记录。但是我发现用上一版0.2.8的时候，手机迁移到PC后，在MemoTrace的好友那一栏，是可以找到这个群的，只是导出后只有很少一部分群记录被留下来。这次升级1.0以后，我执行和之前一模一样的操作（先迁移到PC，再读取），完全看不到那个群了。
如果可以的话，是否能请您着重制作一下“导出已经被解散的群，在安卓手机上的留存记录”这个功能，我一直在用6年前的旧手机，就是因为腾讯不允许迁移已经解散的群聊天记录，为了留下这段信息，我只能一直把旧手机当主力使用。
感谢您的付出
