### ISSUE TITLE
【微信聊天记录文件读取缺陷】

### ISSUE THREAD

**Issue by XS170202102296** [LC044/WeChatMsg#141]
**是否检查过issues没有相同问题**
否
**bug描述**
我用软件读取了我微信聊天记录之后，选择了我需要的导出目标，然后预览，从12月15日预留到8月之后发现更早的的聊天记录没有给我读取，在微信检查之后我8月之前的微信聊天记录是有的，但是软件应该是不支持这么大聊天记录的读取吧还是咋样就是没读到，该聊天记录文件为2.2g左右。

**报错截图**

**是否可复现**
是
**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:3.11.4
 - 软件版本: 0.2.8
 - 微信版本:3.9.8.15

**Additional context**
增加更大聊天记录的文件读取功能。

**Comment by ChiacagoFengli** [comment]
我也有这样的问题，最早的聊天记录只到2023年12月17日。
运行环境:

OS: [Win11]
Python版本:3.11.5
软件版本: 0.2.8
微信版本:3.9.8.15

**Comment by hmy1210** [comment]
同样的问题我也存在，
PC端里的记录最早去到20年的，但是导出 只能到10月底的。10月初的都没

![image](https://github.com/LC044/WeChatMsg/assets/30746089/2e8a5095-7751-47ce-b8c7-977f8ff4d0af)

**Comment by LC044** [comment]
> 同样的问题我也存在， PC端里的记录最早去到20年的，但是导出 只能到10月底的。10月初的都没
> 
> ![image](https://private-user-images.githubusercontent.com/30746089/291068926-2e8a5095-7751-47ce-b8c7-977f8ff4d0af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjQ1NTMsIm5iZiI6MTcwMjgyNDI1MywicGF0aCI6Ii8zMDc0NjA4OS8yOTEwNjg5MjYtMmU4YTUwOTUtNzc1MS00N2NlLWI4YzctOTc3ZjhmZjRkMGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0NDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZjNkOTljNmFhMjU5MzEzZTlkY2ZhNDRlNDJiYWYyMWUwNWFhZWU4MGJkMTE0YTExNjQwZTMwYTNlN2JlOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tRbFH8ov6uAc5pSETzPk3h3osu9lAHForJvXCw4TL9k)

app/database/msg里的全部msg.db文件截个图发一下，我看看怎么回事

**Comment by LC044** [comment]
> > 同样的问题我也存在， PC端里的记录最早去到20年的，但是导出 只能到10月底的。10月初的都没
> > ![image](https://private-user-images.githubusercontent.com/30746089/291068926-2e8a5095-7751-47ce-b8c7-977f8ff4d0af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjQ1NTMsIm5iZiI6MTcwMjgyNDI1MywicGF0aCI6Ii8zMDc0NjA4OS8yOTEwNjg5MjYtMmU4YTUwOTUtNzc1MS00N2NlLWI4YzctOTc3ZjhmZjRkMGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0NDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZjNkOTljNmFhMjU5MzEzZTlkY2ZhNDRlNDJiYWYyMWUwNWFhZWU4MGJkMTE0YTExNjQwZTMwYTNlN2JlOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tRbFH8ov6uAc5pSETzPk3h3osu9lAHForJvXCw4TL9k)
> 
> app/database/msg里的全部msg.db文件截个图发一下，我看看怎么回事

截图的时候要显示文件大小

**Comment by LC044** [comment]
不回的话就先关了

**Comment by ChiacagoFengli** [comment]
<img width="547" alt="dd2f55c1c25bca315427cd030504af4" src="https://github.com/LC044/WeChatMsg/assets/154012055/4ec7bf8a-5cdc-4857-9ae8-4d8faf289dc7">
更新版本之后这个问题依然存在

**Comment by XS170202102296** [comment]
你放的图片我这边看不了，还有就是别关啊，学生党看github回复没那么及时
