### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'None\\MSG\\MicroMsg.db'

### ISSUE THREAD

**Issue by puppy-j** [LC044/WeChatMsg#144]
**是否检查过issues没有相同问题**

**bug描述**
点击获取信息会出现：
2023-12-16 17:29:46,452 - pc_decrypt.py[line:87] - ERROR: Traceback (most recent call last):
  File "app\ui\tool\pc_decrypt\pc_decrypt.py", line 55, in get_info
  File "app\decrypt\get_wx_info.py", line 302, in get_info
  File "app\decrypt\get_wx_info.py", line 275, in read_info
  File "app\decrypt\get_wx_info.py", line 213, in get_key
  File "app\decrypt\get_wx_info.py", line 176, in verify_key
FileNotFoundError: [Errno 2] No such file or directory: 'None\\MSG\\MicroMsg.db'
**报错截图**
![1702719118702](https://github.com/LC044/WeChatMsg/assets/112534052/9f2732ae-813d-4f7b-af76-b867fa892cd3)

**是否可复现**
是
**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 0.2.8
 - 微信版本:3.9.8.15

**Additional context**

**Comment by Epiphuany** [comment]
我也是出现这样的问题，一模一样

**Comment by wzgrx** [comment]
+1，卸载重装试了好多次，都不行，是不是微信号有问题

**Comment by LC044** [comment]
> +1，卸载重装试了好多次，都不行，是不是微信号有问题

你会用python不，要是会的话可以运行一下代码版本，看看能否解决问题，不会的话可以等下个版本再试用

**Comment by Epiphuany** [comment]
> > +1，卸载重装试了好多次，都不行，是不是微信号有问题
> 
> 你会用python不，要是会的话可以运行一下代码版本，看看能否解决问题，不会的话可以等下个版本再试用

  运行的就是代码版本，一样的报这个错

**Comment by LC044** [comment]
> > > +1，卸载重装试了好多次，都不行，是不是微信号有问题
> > 
> > 
> > 你会用python不，要是会的话可以运行一下代码版本，看看能否解决问题，不会的话可以等下个版本再试用
> 
> 我运行的就是代码版本，一样的报这个错

什么时候的代码，是最新的吗

**Comment by wzgrx** [comment]
> > > > +1，卸载重装试了好多次，都不行，是不是微信号有问题
> > > 
> > > 
> > > 你会用python不，要是会的话可以运行一下代码版本，看看能否解决问题，不会的话可以等下个版本再试用
> > 
> > 
> > 我运行的就是代码版本，一样的报这个错
> 
> 什么时候的代码，是最新的吗

python也试了，都是最新版本，还是不行，是不是和系统有关系，电脑是win11，python3.10 3.11版本都试了，晕了，是不是要换个电脑，杀毒软件就火绒，系统也是重新装的没几天，也没下载啥软件

**Comment by LC044** [comment]
> > > > > +1，卸载重装试了好多次，都不行，是不是微信号有问题
> > > > 
> > > > 
> > > > 你会用python不，要是会的话可以运行一下代码版本，看看能否解决问题，不会的话可以等下个版本再试用
> > > 
> > > 
> > > 我运行的就是代码版本，一样的报这个错
> > 
> > 
> > 什么时候的代码，是最新的吗
> 
> python也试了，都是最新版本，还是不行，是不是和系统有关系，电脑是win11，python3.10 3.11版本都试了，晕了，是不是要换个电脑，杀毒软件就火绒，系统也是重新装的没几天，也没下载啥软件

最新的代码应该是不会报这个错的，你再拉取一下最新的代码，版本是0.2.9

**Comment by wzgrx** [comment]
> > > > > > +1，卸载重装试了好多次，都不行，是不是微信号有问题
> > > > > 
> > > > > 
> > > > > 你会用python不，要是会的话可以运行一下代码版本，看看能否解决问题，不会的话可以等下个版本再试用
> > > > 
> > > > 
> > > > 我运行的就是代码版本，一样的报这个错
> > > 
> > > 
> > > 什么时候的代码，是最新的吗
> > 
> > 
> > python也试了，都是最新版本，还是不行，是不是和系统有关系，电脑是win11，python3.10 3.11版本都试了，晕了，是不是要换个电脑，杀毒软件就火绒，系统也是重新装的没几天，也没下载啥软件
> 
> 最新的代码应该是不会报这个错的，你再拉取一下最新的代码，版本是0.2.9

试了7.8次了，没有用，我怀疑是微信号被云控了

**Comment by wzgrx** [comment]
> > > > > > +1，卸载重装试了好多次，都不行，是不是微信号有问题
> > > > > 
> > > > > 
> > > > > 你会用python不，要是会的话可以运行一下代码版本，看看能否解决问题，不会的话可以等下个版本再试用
> > > > 
> > > > 
> > > > 我运行的就是代码版本，一样的报这个错
> > > 
> > > 
> > > 什么时候的代码，是最新的吗
> > 
> > 
> > python也试了，都是最新版本，还是不行，是不是和系统有关系，电脑是win11，python3.10 3.11版本都试了，晕了，是不是要换个电脑，杀毒软件就火绒，系统也是重新装的没几天，也没下载啥软件
> 
> 最新的代码应该是不会报这个错的，你再拉取一下最新的代码，版本是0.2.9

Traceback (most recent call last):
  File "D:\WeChatMsg\app\ui\tool\pc_decrypt\pc_decrypt.py", line 190, in btnExitClicked
    shutil.copy2("app/DataBase/Msg/MSG0.db", target_database)  # 使用一个数据库文件作为模板
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\zjx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'

**Comment by wzgrx** [comment]
> Traceback (most recent call last):
> File "D:\WeChatMsg\app\ui\tool\pc_decrypt\pc_decrypt.py", line 190, in btnExitClicked
> shutil.copy2("app/DataBase/Msg/MSG0.db", target_database) # 使用一个数据库文件作为模板
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\zjx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 436, in copy2
> copyfile(src, dst, follow_symlinks=follow_symlinks)
> File "C:\Users\zjx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 256, in copyfile
> with open(src, 'rb') as fsrc:
> ^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'

错误信息表明在执行 shutil.copy2("app/DataBase/Msg/MSG0.db", target_database) 时发生了 FileNotFoundError，即找不到指定的文件 'app/DataBase/Msg/MSG0.db'。

首先，确保指定的源文件路径是正确的。在你的脚本中，它是相对路径，相对于当前脚本所在的目录。请确保 pc_decrypt.py 脚本确实位于 D:\WeChatMsg\app\ui\tool\pc_decrypt\ 目录中。

如果脚本确实在正确的目录中，那么需要检查 'app/DataBase/Msg/MSG0.db' 文件是否存在。可能有以下原因导致文件找不到：

文件不存在： 确保 app/DataBase/Msg/MSG0.db 文件确实存在于相对路径下。

相对路径问题： 当前工作目录可能不是你期望的目录。你可以在脚本的开头添加以下代码来打印当前工作目录：

python
Copy code
import os
print("Current working directory:", os.getcwd())
确保当前工作目录是你预期的路径。如果不是，你可以使用 os.chdir() 来更改当前工作目录。

路径拼接问题： 请确保路径拼接是正确的。你可以使用 os.path.join() 函数来确保路径拼接的跨平台性。例如：

python
Copy code
import os
source_file = os.path.join("app", "DataBase", "Msg", "MSG0.db")
确保文件存在且路径正确，这样应该能够解决 FileNotFoundError 错误。

**Comment by LC044** [comment]
你这个报错好像跟他们不一样吧

**Comment by Epiphuany** [comment]
> 你这个报错好像跟他们不一样吧

拉取的最新版本0.2.9，还是报错
`D:\BrowserDownload\liuheng\WeChatMsg-master>python main.py
ok 本次加载用了 1.6873149871826172 s
2023-12-17 14:36:20,665 - pc_decrypt.py[line:92] - ERROR: Traceback (most recent call last):
  File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\ui\tool\pc_decrypt\pc_decrypt.py", line 60, in get_info
    result = get_wx_info.get_info(VERSION_LIST)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 303, in get_info
    result = read_info(VERSION_LIST, True)  # 读取微信信息
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 275, in read_info
    tmp_rd['key'] = get_key(tmp_rd['filePath'], addrLen)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 213, in get_key
    if verify_key(key_bytes, MicroMsg_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 176, in verify_key
    with open(wx_db_path, "rb") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'None\\MSG\\MicroMsg.db'`

**Comment by LC044** [comment]
> > 你这个报错好像跟他们不一样吧
> 
> 拉取的最新版本0.2.9，还是报错 D:\BrowserDownload\liuheng\WeChatMsg-master>python main.py ok 本次加载用了 1.6873149871826172 s 2023-12-17 14:36:20,665 - pc_decrypt.py[line:92] - ERROR: Traceback (most recent call last): File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\ui\tool\pc_decrypt\pc_decrypt.py", line 60, in get_info result = get_wx_info.get_info(VERSION_LIST) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 303, in get_info result = read_info(VERSION_LIST, True) # 读取微信信息 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 275, in read_info tmp_rd['key'] = get_key(tmp_rd['filePath'], addrLen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 213, in get_key if verify_key(key_bytes, MicroMsg_path): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 176, in verify_key with open(wx_db_path, "rb") as file: ^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'None\MSG\MicroMsg.db'

刚又更新了一下，再试试

**Comment by LC044** [comment]
可以加我QQ，863909694，备注一下信息

**Comment by wzgrx** [comment]
> > > 你这个报错好像跟他们不一样吧
> > 
> > 
> > 拉取的最新版本0.2.9，还是报错 D:\BrowserDownload\liuheng\WeChatMsg-master>python main.py ok 本次加载用了 1.6873149871826172 s 2023-12-17 14:36:20,665 - pc_decrypt.py[line:92] - ERROR: Traceback (most recent call last): File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\ui\tool\pc_decrypt\pc_decrypt.py", line 60, in get_info result = get_wx_info.get_info(VERSION_LIST) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 303, in get_info result = read_info(VERSION_LIST, True) # 读取微信信息 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 275, in read_info tmp_rd['key'] = get_key(tmp_rd['filePath'], addrLen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 213, in get_key if verify_key(key_bytes, MicroMsg_path): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BrowserDownload\liuheng\WeChatMsg-master\app\decrypt\get_wx_info.py", line 176, in verify_key with open(wx_db_path, "rb") as file: ^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'None\MSG\MicroMsg.db'
> 
> 刚又更新了一下，再试试

 'filePath': 'D:\\Soft\\WeChat\\WeChat Files\\'key': 'None'}]
Traceback (most recent call last):
  File "D:\WeChatMsg\app\ui\tool\pc_decrypt\pc_decrypt.py", line 190, in btnExitClicked
    shutil.copy2("app/DataBase/Msg/MSG0.db", target_database)  # 使用一个数据库文件作为模板
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zjx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\zjx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'

还是不行

**Comment by GoForceX** [comment]
遇到了同样的问题，拉取 GitHub 后显示密钥为 None

用这个 https://github.com/SnowMeteors/GetWeChatKey 改了一下 get_wx_info.py

现在可以正常获取了，但是那边没有 LICENSE 不太好直接用（

**Comment by LC044** [comment]
> 遇到了同样的问题，拉取 GitHub 最新代码后显示密钥为 None
> 
> 用这个 https://github.com/SnowMeteors/GetWeChatKey 改了一下 get_wx_info.py
> 
> 现在可以正常获取了，但是那边没有 LICENSE 不太好直接用（
> 
> 对于想自己改的各位，可以用这个方法：
> 
> 1. 在 GetWeChatKey.py 中的 GetInfo 方法 `if self.CheckKey(key):` 后换行并添加 `return key`
> 2. 把文件内所有代码复制到 get_wx_info.py 开头
> 3. 在本项目的 get_wx_info.py 中的 get_key(db_path, addr_len) 方法开头处添加
> 
> ```python
>     wechat = Pymem("WeChat.exe")
>     k = Wechat(wechat).GetInfo()
> 
>     if k:
>         return k
> ```
> 
> 不是很优雅的解决方案，但是能用（

感谢
