### ISSUE TITLE
推荐组件库使用 qfluentwidget

### ISSUE THREAD

**Issue by Atticuszz** [LC044/WeChatMsg#149]
也是国内大佬弄的 pyqt 组件库，效果有多棒？win11 自带主题的质量😎

**Comment by LC044** [comment]
欢迎您帮忙适配

**Comment by Atticuszz** [comment]
可能要等一些时间，手里项目还没搞完，寒假还有写论文，如果有贡献者想要用它可以滴滴我，我之前写过，摸出一套比较高效稳定的模式，可以给你们提供一些好主意(･ω･)👉，祝你们项目越来越好✌️![Screenshot_2023-12-17-11-21-13-17_e39d2c7de19156b0683cd93e8735f348.jpg](https://github.com/LC044/WeChatMsg/assets/119986792/4a18257f-ec38-4d5a-aece-9eb5ac6e92ba)

**Comment by LC044** [comment]
太巧了，我也没有时间，看来大家都很忙

**Comment by LC044** [comment]
等你有时间了再慢慢适配也挺好，不着急

**Comment by Atticuszz** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets

**Comment by Atticuszz** [comment]
> 等你有时间了再慢慢适配也挺好，不着急

👌😇
