### ISSUE TITLE
导出聊天记录的时候（HTML格式）会显示，系统找不到指定路径……

### ISSUE THREAD

**Issue by whalecc77** [LC044/WeChatMsg#150]
**是否检查过issues没有相同问题**

**bug描述**

**报错截图**

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**

**Comment by LC044** [comment]
把报错截图发一下啊

**Comment by 418667527** [comment]
> 把报错截图发一下啊

![微信截图_20231217221753](https://github.com/LC044/WeChatMsg/assets/63603940/6fb6bd27-b5ee-4a56-b652-a129de84ae10)
应该就是这样的
