### ISSUE TITLE
微信已经更新到3.9.8.25 求大佬更新

### ISSUE THREAD

**Issue by boluoa7** [LC044/WeChatMsg#151]
**是否检查过issues没有相同问题**

**bug描述**
A clear and concise 

description of what the bug is.

**报错截图**
![Snipaste_2023-12-17_17-48-34](https://github.com/LC044/WeChatMsg/assets/131236729/66ad69f2-c82c-41e9-912f-48034f2b8d7c)
![Snipaste_2023-12-17_17-48-19](https://github.com/LC044/WeChatMsg/assets/131236729/b69b06b6-2f19-4087-a6f5-0823fb095fe7)
**是否可复现**

**运行环境:**
 - OS: [e.g. Win10]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**

**Comment by LC044** [comment]
已适配
