### ISSUE TITLE
导出聊天记录时包含链接？ 出现闪退

### ISSUE THREAD

**Issue by 418667527** [LC044/WeChatMsg#156]
**是否检查过issues没有相同问题**
无
**bug描述**
导出聊天记录时包含链接（可能）？ 出现闪退

**报错截图**

#
![微信截图_20231217221753](https://github.com/LC044/WeChatMsg/assets/63603940/c5b3307d-bb8d-4cfc-87cd-c8f5c631ae0d)

**是否可复现**
可
**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:3.10.11
 - 软件版本: 2.9 20231217 22：00最新
 - 微信版本:3.9.8.15

**Comment by 418667527** [comment]
导出的 html格式

**Comment by LC044** [comment]
更新一下代码再试试
