### ISSUE TITLE
聊天记录超过10G时导出会崩溃

### ISSUE THREAD

**Issue by purple-WL** [LC044/WeChatMsg#161]
最近想把和爱人的聊天记录导出下，文件夹16G，可以正常识别出所有记录，只是在导出的时候还是会提示OperationalError: (sqlite3.OperationalError) no such table xxx，导出中断。

**Comment by LC044** [comment]
图呢

**Comment by purple-WL** [comment]
老弟我忘记截图了，我现在在上班用的macOS，回头补充，文件小的话导出很顺利，可能太大了吧

**Comment by Leo-Smith666** [comment]
大点的好像是会崩的，我一个2.9G的试了下，点完导出HTML就闪退了

**Comment by LC044** [comment]
图片、视频、表情包看看是哪个导致闪退的，闪退的时候黑框里会有报错信息，迅速截个屏或者录屏

**Comment by Leo-Smith666** [comment]
明白了大佬，下次试的时候录个屏看一下😘
