### ISSUE TITLE
群聊记录导出HTML后，记录中每个人说话不显示名字，无法知道是谁说了什么话

### ISSUE THREAD

**Issue by admin233** [LC044/WeChatMsg#162]
**是否检查过issues没有相同问题**

**bug描述**

**报错截图**

**是否可复现**

**运行环境:**
 - OS: win10
 - Python版本:
 - 软件版本: v0.2.8
 - 微信版本:3.9.8.15

**Additional context**

**Comment by LC044** [comment]
您好，最新代码已支持群聊，您可运行源码或者等待下个版本
