### ISSUE TITLE
导出的记录需要发言人名称

### ISSUE THREAD

**Issue by flyingcountry** [LC044/WeChatMsg#164]
感谢大哥的软件，我有些知识分享的群，一直想备份，这个真是解决了大问题。不过使用时候还有点问题，就是导出的html，可能是已经解散的群的原因，里面的头像都是一样的，又没有名字，就不知道是哪个人发的信息了。

**Comment by LC044** [comment]
最新代码已实现群聊导出功能，您可运行源码，或者等几天我会发布最新版
