### ISSUE TITLE
解密后再运行就出错，用新的虚拟机系统同样出错。

### ISSUE THREAD

**Issue by flyspark803** [LC044/WeChatMsg#165]
**是否检查过issues没有相同问题**

**bug描述**
![Uploading 2023-12-18_101544.png…]()

**报错截图**

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**

**Comment by LC044** [comment]
图片看不到，别用虚拟机了，换个windows吧
