### ISSUE TITLE
启动成功后，重启程序报错release unlocked lock后闪退

### ISSUE THREAD

**Issue by lijing-2008** [LC044/WeChatMsg#166]
**是否检查过issues没有相同问题**
解密启动都没问题，就是重启程序时闪退，看到命令行窗口报错为release unlocked lock

<img width="466" alt="error" src="https://github.com/LC044/WeChatMsg/assets/59533655/fb0f4164-fc6e-49e9-81d7-3662fa4b0133">

**是否可复现**

**运行环境:**
 - OS: [e.g. Win10]
 - Python版本:无
 - 软件版本: 0.2.8
 - 微信版本:3.9.8.15

**Additional context**

**Comment by LC044** [comment]
删除msg文件夹之后重新解密一下
