### ISSUE TITLE
批量导出/备份完整的聊天记录和检索

### ISSUE THREAD

**Issue by geeklihui** [LC044/WeChatMsg#167]
首先感谢开发者的付出，这个项目有极大的意义，微信的记录备份终于不用依赖于某部特定手机或电脑了。

不知道是不是我的用法或理解不对，我想要定期备份聊天记录到一个文件里，日后可以方便检索，目前没找到合适的操作步骤。

1. 菜单“数据”>“导出聊天记录（全部）”>“CSV”，导出来的是乱码，我大概猜得到是编码问题，应该改一下就能读，但是似乎也没有图片、语音、表情包这些。受限于 CSV 格式，这个方法应该很难实现完整备份了。

2. 好友界面“导出聊天记录”、“导出 HTML”能够导出相对完整的记录，这个形式可以保存的比较完整，但是语音条显示长度为 0，无法播放，转文字倒是有显示；语音通话/视频通话记录还是没有。
![image](https://github.com/LC044/WeChatMsg/assets/28993319/b10838a9-7a07-419f-8813-9eb3b30c1143)
先假设语音无法播放为 bug，后续会修复，或者是我用法不对，环境没装好之类的，总之，这种方法应该就是最完整的导出步骤了，但是我没有找到可以批量导出的方法，似乎只能一个个好友单独导出。还是做不到全部聊天记录一起备份。

3. 聊天界面看不到表情包和语音通话/视频通话记录。我考虑过，解密后的数据库和主程序一起备份，日后直接用主程序读取解密后的数据库，应该就能读到所有数据了，可是因为界面里看不到完整的记录（语音、表情包都是不显示的，所以不导出 HTML 都不知道有没有缺漏的记录），还是得导出 HTML 才能检索完整的聊天记录。

不知道能否实现完整的备份和检索，第二种就是要实现批量导出 HTML，第三种是要修复聊天界面不显示语音、表情包等。还有就是目前我没找到更新数据库的入口，已经解密后，再重新打开软件似乎会直接读取之前的数据库，新的聊天记录不知道如何导出来，是需要换一个路径执行主程序吗？

再次感谢开发者。

**Comment by LC044** [comment]
试试1.0.3
