### ISSUE TITLE
建议增加搜索聊天记录功能并定位，还有建议把每个联系人的图片放在联系人的目录下

### ISSUE THREAD

**Issue by vicentory** [LC044/WeChatMsg#172]
功能很好，点赞支持。
建议增加搜索聊天记录功能并定位。
还有建议把每个联系人的图片放在联系人的目录下，这样复制粘贴只要移动单独某个人的文件夹既可以。
<img width="535" alt="image" src="https://github.com/LC044/WeChatMsg/assets/10493597/d663ab39-f1f4-4119-8763-e826ed3f19b6">

**Comment by STDquantum** [comment]
在导出html的地方已经每个人的都分开了
