### ISSUE TITLE
打开白屏  直接报错  100%复现

### ISSUE THREAD

**Issue by CPsharpING** [LC044/WeChatMsg#177]
**是否检查过issues没有相同问题**

**bug描述**

**报错截图**
![ee1f66ecbf744f19f05c5cb6202ab17](https://github.com/LC044/WeChatMsg/assets/98728923/e8191987-8dd5-4248-803c-de9cac0f1a98)

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**

**Comment by LC044** [comment]
哪个是白色啊，难道是我色盲了吗

**Comment by LC044** [comment]
不回的话就先关了，下次提issue的时候说明白谢谢
