### ISSUE TITLE
移动整个data文件夹，html中的语音无法播放

### ISSUE THREAD

**Issue by Burro-CMD** [LC044/WeChatMsg#182]
**bug描述**
整个导出操作是在Win11上完成，之后移动整个data文件夹到Win10中，html中的语音播放按钮显示灰色且无法播放，尝试了edge, chrome都是一样的现象，单独去查看voice中的语音是没有问题的

**报错截图**
![Snipaste_2023-12-19_14-04-26](https://github.com/LC044/WeChatMsg/assets/52642959/48c48d14-8eca-4a7a-8abf-1aa10d84f135)

**是否可复现**
可以复现

**Comment by STDquantum** [comment]
已修复 可以等下一个正式版本发布

**Comment by Lll05** [comment]
我导出后语音是.pcm.silk HTML里也无法播放
![1702991666690](https://github.com/LC044/WeChatMsg/assets/102873003/1a8869d7-4114-475e-b799-0fc353e6536a)

**Comment by LC044** [comment]
已修复

**Comment by Burro-CMD** [comment]
非常感谢。
