### ISSUE TITLE
重启闪退

### ISSUE THREAD

**Issue by saresam** [LC044/WeChatMsg#183]
**是否检查过issues没有相同问题**
是的，好像没看到。

**bug描述**
有安教程获取信息，点击开始启动，进度条走到98%而后闪退。
重启时显示：
![微信截图_20231219145805](https://github.com/LC044/WeChatMsg/assets/30542980/9930d74f-d04f-48bc-882d-95c8d23e13cf)

有试过删除Msg文件夹，再次开始启动操作后还是闪退，依然显示上面的报错。

**报错截图**
![微信截图_20231219145805](https://github.com/LC044/WeChatMsg/assets/30542980/9930d74f-d04f-48bc-882d-95c8d23e13cf)
**是否可复现**
可复现

**运行环境:**
 - OS: Win10
 - Python版本: 
 - 软件版本: 0.2.8
 - 微信版本:3.9.8.15

**Additional context**

**Comment by LC044** [comment]
你会python不，会的话可以加我QQ，不会的话先等等吧
