### ISSUE TITLE
3.9.8.25 版本无法使用了

### ISSUE THREAD

**Issue by playmobil** [LC044/WeChatMsg#185]
我用的是较早的版本，直接就升级到3.9.8.25
使用 release 0.2.8 提示“微信版本不匹配，请更新微信版本为：3.9.8.15”

**Comment by LC044** [comment]
最新代码已适配3.9.8.25，你可关注公众号等待最新版发布

**Comment by WhisperWindE** [comment]
漏了无数群聊, 找也找不到.

**Comment by LC044** [comment]
> 漏了无数群聊, 找也找不到.

可能是没充VIP吧
