### ISSUE TITLE
HTML方式没有导出文件、"合并转发"及Links消息

### ISSUE THREAD

**Issue by xengpro** [LC044/WeChatMsg#186]
**bug描述**
感谢大佬开发拯救众生的好工具！今天试了下，发现消息导出为HTML时，文件、"合并转发"及Links的消息都没有导出呢

**是否可复现**
是

**运行环境:**
 - OS: Win11
 - Python版本: 3.11.5(本机)
 - 软件版本: 0.2.8
 - 微信版本: 3.9.8.15

**Comment by Gliangquan** [comment]
文件那里是软件就没获取到文件，所以导出也没有

**Comment by LC044** [comment]
文件已实现
