### ISSUE TITLE
with mac vm win11, use 留痕.exe 提示 no such table msg 并重启

### ISSUE THREAD

**Issue by xiedi-w** [LC044/WeChatMsg#191]
**是否检查过issues没有相同问题**

**bug描述**
按照操作步骤：
2.1 设置信息 
1. 完成 获取信息
2. 完成微信安装路径是自动填充
3. 开始解密，解密时控制台提示如下，稍作3秒。exe关闭，控制台关闭

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/53244726/4373b899-dc21-464d-983a-f187490d53eb)

**是否可复现**
可以
**运行环境:**
 - OS: win11（mac 虚拟机安装win111）
 - Python版本: 暂时没有按照py，我按照https://blog.lc044.love/post/5没有提示安装。如果有需要可以安装py
 - 软件版本: MemoTrace-0.2.8
 - 微信版本: 3.9.8.15

**Additional context**
无

**Comment by xiedi-w** [comment]
已经尝试的方法为：
重启微信，删除exe同级的app/database/Msg 目录，重启MemoTrace-0.2.8。按照步骤操作后还是会复现问题

**Comment by LC044** [comment]
mac虚拟机不太了解，你可下载源码进行运行，如发现解决办法可以反馈，我修改代码

**Comment by xiedi-w** [comment]
好的 我尝试一下

**Comment by Shirakiina** [comment]
M1 是 arm 的架构，可能是这方面的原因，我也试过这样弄，一直不太行。后面没办法找了个 amd64 的电脑才可以。

**Comment by LC044** [comment]
试试新版能否解决该问题
