### ISSUE TITLE
年度报告分析的起始时间点不为今年的1月1日

### ISSUE THREAD

**Issue by SPTAU** [LC044/WeChatMsg#193]
**是否star**
是

**是否检查过issues没有相同问题**
无

**bug描述**
年度分析报告中，分析的范围并不是以当前年份的1月1日作为起始点

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/46211051/c7cbb4fb-047d-42cc-8dbd-2be3f9931a5d)

**是否可复现**
是

**运行环境:**
 - OS: Win11
 - Python版本: Python 3.10
 - 软件版本:  0.2.9
 - 微信版本: 3.9.8.25

**Comment by LC044** [comment]
已修改
