### ISSUE TITLE
首次运行报错，再次运行闪退

### ISSUE THREAD

**Issue by Yangrunhu** [LC044/WeChatMsg#195]
**bug描述**
首次运行，可以正常获取相关微信信息，报错提示为： `[Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'`
后续不删除data文件夹等运行，报错提示为：`'NoneType' object is not iterable`

**报错截图**
首次运行：
![image](https://github.com/LC044/WeChatMsg/assets/23611602/16e21dad-c652-4dcf-bc28-eaf9b0f4fadd)

第二次运行：
![image](https://github.com/LC044/WeChatMsg/assets/23611602/862d1632-9290-4a2a-889b-1529ed9dd995)

**是否可复现**
是

**运行环境:**
 - OS: Win11
 - Python版本:3.10.9
 - 软件版本: 12月20日源代码版本
 - 微信版本:3.9.8.25

**Additional context**
微信聊天记录位置非默认安装后的保存地址。

**Comment by LC044** [comment]
提供一下获取信息界面截图，路径，wxid，密钥是否正常

**Comment by Yangrunhu** [comment]
> 提供一下获取信息界面截图，路径，wxid，密钥是否正常

能够正常获取到信息，提供部分截图。
![image](https://github.com/LC044/WeChatMsg/assets/23611602/5f73459a-44f6-4e58-ac2b-cc7855e05968)

我这边尝试修改了一下，现在可以正常运行了。
修改过程为：
将`pc_decrypt.py` 190行代码中的`MSG0.db`修改为`MSG01.db`
![image](https://github.com/LC044/WeChatMsg/assets/23611602/d7924ae4-353d-4af0-a793-1b1962ca66c0)

**Comment by LC044** [comment]
是你的数据库有十几个吗，是从MSG01开始命名的吗

**Comment by Yangrunhu** [comment]
不是，是从MSG01（2）.db开始的。
msg2-msg9，前面还有msg01（2）和msg（3）以及msg01

**Comment by LC044** [comment]
> 不是，是从MSG01（2）.db开始的。 msg2-msg9，前面还有msg01（2）和msg（3）以及msg01

好乱的命名，你看一下微信文件保存目录的原始数据库是咋命名的

**Comment by Yangrunhu** [comment]
> > 不是，是从MSG01（2）.db开始的。 msg2-msg9，前面还有msg01（2）和msg（3）以及msg01
> 
> 好乱的命名，你看一下微信文件保存目录的原始数据库是咋命名的

![image](https://github.com/LC044/WeChatMsg/assets/23611602/19da728a-c8c9-4c13-83a3-2a94c79c232d)
我的原始目录就是这样的，出现这种情况可能是之前，我设置onedriver同步目录，然后再重启微信之后，同步之前的聊天记录就不见了。
