### ISSUE TITLE
年度报告词云图部分过滤表情包文字

### ISSUE THREAD

**Issue by qyh540** [LC044/WeChatMsg#197]
做的年度报告功能生成的词云图部分，会把表情包描述例如 [发怒]，作为词语绘制上去；我觉得不用将表情包和文字放在一起做词云；

**Comment by LC044** [comment]
[发怒]这个不叫表情包，他就是纯文本，跟普通文本没有区别，需要单独过滤

**Comment by qyh540** [comment]
对的，我的意思就是词云图绘制的时候应该过滤掉这部分对应表情包的”纯文本“；或者对表情包部分单独做个可视化报告；不过没关系看起来挺好自己改的

**Comment by LC044** [comment]
等下个版本我会出一个自定义停用词功能

**Comment by LC044** [comment]
已支持自定义过滤词
