### ISSUE TITLE
直接用sqlcipher.bat解密报错

### ISSUE THREAD

**Issue by aRookieMan** [LC044/WeChatMsg#2]
前辈，我直接用sqlcipher.bat解密，报错：file is encrypted or is not a database。怎么解决？

**Comment by LC044** [comment]
将我的代码下载下来，运行之后根据提示加载需要的两个文件即可自动解密数据库，会生成一个未加密的sqlite数据库，可以使用任何支持sqlite的数据库打开。我的程序可以自动解密，不需要第三方程序了

**Comment by aRookieMan** [comment]
请问会在那个目录下生成？我使用您的程序，解密界面卡在99%

**Comment by LC044** [comment]
解密后的数据库会保存在./app/data/DataBase文件夹里，如果一直卡在99%可耐心等待或者重新启动软件，实测700M的数据库是可以正常解密的，如果数据库文件过大可尝试只恢复部分聊天记录

**Comment by aRookieMan** [comment]
> 解密后的数据库会保存在./app/data/DataBase文件夹里，如果一直卡在99%可耐心等待或者重新启动软件，实测700M的数据库是可以正常解密的，如果数据库文件过大可尝试只恢复部分聊天记录

感谢，已经没问题了

**Comment by 914988803** [comment]
实测3.86g的数据库，解密不了（不知道是不是能否解密）msg.db文件生成了，但是文件大小只有736kb,再次运行后报错： File "c:\sharer\WeChatMsg\main.py", line 41, in loadMainWinView
    self.viewMainWIn = mainview.MainWinController(username=username)
  File "c:\sharer\WeChatMsg\app\Ui\mainview.py", line 30, in __init__
    self.Me = data.get_myinfo()
  File "c:\sharer\WeChatMsg\app\DataBase\data.py", line 123, in get_myinfo
    cursor.execute(sql)
sqlite3.OperationalError: no such table: userinfo

**Comment by LC044** [comment]
使用最新代码可解决该问题
