### ISSUE TITLE
聊天记录导出HTML闪退

### ISSUE THREAD

**Issue by bingjiling2023** [LC044/WeChatMsg#203]
**bug描述**
对联系人的聊天记录导出为html时闪退，具体时间是开始后30秒左右，下图为导出html时的截图，后面程序就异常结束了，闪退时无任何提示

**报错截图**
![bug_Snipaste_2023-12-21_01-24-24](https://github.com/LC044/WeChatMsg/assets/92205815/5839d9e0-3bdf-4f80-b987-d80fb2d6100f)

**是否可复现**
重试很多遍都是闪退

**运行环境:**
 - OS: Win10 
 - Python版本: 
 - 软件版本: v1.0.0
 - 微信版本:3.9.8.25

**Comment by LC044** [comment]
可以试试单独导出文本、图片、等看看是哪个出错了

**Comment by LC044** [comment]
已解决，重新下载试试
