### ISSUE TITLE
能不能手动提取手机内的文件不用迁移（安卓或者越狱后的苹果）

### ISSUE THREAD

**Issue by lalasou** [LC044/WeChatMsg#205]
首先这个项目很棒！很好用。

不知道 迁移是否必须？ 如果能自己传输文件会更方便
能不能手动提取手机内的文件不用迁移（安卓或者越狱后的苹果）

**Comment by LC044** [comment]
root后的安卓可以

**Comment by lalasou** [comment]
> root后的安卓可以

在哪里有wiki吗
没找到  手机直接复制文件的说明

**Comment by LC044** [comment]
试试发布的0.1.0（最早的那个）
