### ISSUE TITLE
数据库文件位置和年度报告端口占用如何取消

### ISSUE THREAD

**Issue by Haoami0** [LC044/WeChatMsg#206]
操作系统：windows11
我的操作：运行MemoTrace-1.0.0.exe
问题描述：
请问
1. 数据解密后 解密后的数据库放在哪？
2. 生成年度报告后，年度报告有网页文件html吗？如果有在哪？
3. 生成年度报告后，127.0.0.1:21314端口一直被占用，即使关掉应用程序、重启电脑，该端口仍被占用为微信年度聊天报告？我使用`netstat -ano|findstr 21314`终端命令，试图查看占用这个端口的应用程序，找不到

**Comment by LC044** [comment]
1.看教程
2.没有
3.暂时不清楚

**Comment by bingjiling2023** [comment]
2：检查代码，copy到根目录下
