### ISSUE TITLE
20G的数据备份导出实战

### ISSUE THREAD

**Issue by lanzeweie** [LC044/WeChatMsg#207]
作者这个项目简直就是跟我的理念一模一样！！！！
我现在微信累积备份数据20G左右。
我将一步一步导出，并把环境与遇到的问题依依放在这里供参考。
将使用 Releases MemoTrace-1.0.0.exe 进行操作。

**Comment by Yudezhi** [comment]
我的是21G，每次都提示不在同一个网络环境中

**Comment by samuncleorange** [comment]
> 我的是21G，每次都提示不在同一个网络环境中

你这都和这个项目无关。你的锅或者微信的锅。一段开代理好像不行。

**Comment by lanzeweie** [comment]
Windows11-专业版   微信版本 3.9.8.15
24G数据证明
![24G](https://github.com/LC044/WeChatMsg/assets/53991448/df53b9af-5261-4575-bd13-371ada615307)
