### ISSUE TITLE
大佬 导出HTML聊天记录时闪退

### ISSUE THREAD

**Issue by boluoa7** [LC044/WeChatMsg#212]
**是否star**

**是否检查过issues没有相同问题**

**bug描述**

**报错截图**
![1703162931198](https://github.com/LC044/WeChatMsg/assets/131236729/d3485766-84f6-4d09-aa26-630ce2156fbd)

**是否可复现**

**运行环境:**
 - OS: [e.g. Win10]
 - Python版本:
 - 软件版本: 1.0.0
 - 微信版本:3.9.8.25

**Additional context**

**Comment by LC044** [comment]
已解决，重新下载试试
