### ISSUE TITLE
解密后报错，看起来像是font相关

### ISSUE THREAD

**Issue by sorrrrrymybad** [LC044/WeChatMsg#215]
**是否star**
是
**是否检查过issues没有相同问题**
是
**bug描述**
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="Fixedsys", pointsize=12, pixelsize=16, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-16) dpi=144
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="System", pointsize=12, pixelsize=16, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("System", lfWidth=0, lfHeight=-16) dpi=144
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="Terminal", pointsize=12, pixelsize=16, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Terminal", lfWidth=0, lfHeight=-16) dpi=144
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="Fixedsys", pointsize=15, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=144

解密后每次打开都会报这个错误，并且不显示聊天记录
**报错截图**
![微信截图_20231222154223](https://github.com/LC044/WeChatMsg/assets/44777851/e558600e-23c7-4602-b576-86e4f2b9e475)

**是否可复现**
是
**运行环境:**
 - OS: [e.g. Win11]Win11
 - Python版本:
 - 软件版本: 1.0.0
 - 微信版本:3.9.8.25

**Comment by LC044** [comment]
你用的是exe程序还是python代码

**Comment by sorrrrrymybad** [comment]
直接运行的exe程序，这个电脑上没有任何环境

**Comment by LC044** [comment]
那你试试0.2.8版本，看看能否正常打开，那个版本不支持最新版微信，就看看能否显示界面就行

**Comment by LC044** [comment]
还有你屏幕分辨率和缩放率都是多少

**Comment by sorrrrrymybad** [comment]
0.2.8版本命令行显示
ok 本次加载用了 0.2672412395477295 s
0
仍然不显示聊天记录
屏幕分辨率是3840x2160，缩放率是150%
另外我的备份比较大30G左右，而且同步备份完成之后才升级的新版本微信，不知道有没有影响

**Comment by LC044** [comment]
还是没有显示界面吗

**Comment by sorrrrrymybad** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/44777851/1f390d3e-6b7d-449b-979e-e5c87b23c553)
是的

**Comment by sorrrrrymybad** [comment]
上面说的多等一会，我用1.0.0版本等了大概1个小时了，聊天记录还是空白的

**Comment by LC044** [comment]
> ![image](https://private-user-images.githubusercontent.com/44777851/292426940-1f390d3e-6b7d-449b-979e-e5c87b23c553.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzQ0OTcsIm5iZiI6MTcwMzIzNDE5NywicGF0aCI6Ii80NDc3Nzg1MS8yOTI0MjY5NDAtMWYzOTBkM2UtNmI3ZC00NDliLTk3OWUtZTVjODdiMjNjNTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA4MzYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ODA1YjYxNzVkODk4MmIxOTBmNWZjNzc2MjExMjM1MGViZDQ3ZDFjNmMxNDJlMjkzMDdhOTBmMjgyYmU4MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PkNoFipHS7YzkA_otV55QU9MkUker3IMd8ZfTvK1dEc) 是的

这不是可以吗

**Comment by sorrrrrymybad** [comment]
啊，怪我没有表达清楚可能，我的问题是聊天记录一直不显示，选择导出一个原本记录有很多的好友，导出文件也非常小

**Comment by LC044** [comment]
> 啊，怪我没有表达清楚可能，我的问题是聊天记录一直不显示，选择导出一个原本记录有很多的好友，导出文件也非常小

应该是合并数据库的时候出错了，你可以等下个版本修复，可以关注公众号接收更新日志

**Comment by sorrrrrymybad** [comment]
好的，谢谢回复

**Comment by LC044** [comment]
试试新版能否解决聊天记录显示不全的问题
