### ISSUE TITLE
每次加载到98%软件都会无响应，不是卡进度

### ISSUE THREAD

**Issue by ajun0719** [LC044/WeChatMsg#216]
**bug描述**
每次加载到98%都会无响应（只是软件卡死，电脑其他操作无问题）

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/49946489/4f0df268-934c-4b90-b659-49df1d3f3523)

**是否可复现**
100%复现

**运行环境:**
 - OS: Win10
 - Python版本:
 - 软件版本: 1.0.0
 - 微信版本: 3.9.8.25

**Comment by thinkhero** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/1930362/d7e62d5f-b526-4cd1-9a51-26f81782a222)

**Comment by thinkhero** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/1930362/72849dee-7af7-4d82-8f8b-49c36251b661)
我也是这个情况，看了下是这个

**Comment by Awen1095** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/86345343/1d792a0d-c469-4371-ac6d-96f0afb58dbd)
我是这个样子，试了三次，数据100G左右

**Comment by BernieHuang2008** [comment]
> ![image](https://private-user-images.githubusercontent.com/86345343/292479950-1d792a0d-c469-4371-ac6d-96f0afb58dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzkzMDEsIm5iZiI6MTcwMzQ3OTAwMSwicGF0aCI6Ii84NjM0NTM0My8yOTI0Nzk5NTAtMWQ3OTJhMGQtYzQ2OS00MzcxLWFjNmQtOTZmMGFmYjU4ZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA0MzY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxN2U3NTQzZTdlZDA2YTY5MzE5ZDUzN2MxNjBmN2QwY2NiOTFjOTk0MTkzZTE2MmRhZDBkNzA2ZjVkMzg0ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L4qv7PT5p-QeLEvbdgKl8IFCT-GOYV2IH4quew1mkfM) 我是这个样子，试了三次，数据100G左右

我也是，卡在97%，报错也是no such table MSG

**Comment by BernieHuang2008** [comment]
可是下载源代码运行就没问题

**Comment by LC044** [comment]
试试新版能否解决该问题
