### ISSUE TITLE
导出好友消息到html（导出类别全选）闪退

### ISSUE THREAD

**Issue by mosttt** [LC044/WeChatMsg#219]
**是否star**
是
**是否检查过issues没有相同问题**
是
**bug描述**
导出好友消息到html（导出类别全选）闪退
**报错截图**
![{AEAA7AAD-AD3C-4b0b-8C81-26D96EE028C9}](https://github.com/LC044/WeChatMsg/assets/33774040/6b967f7b-14a3-4f91-b858-6921d398096e)

**是否可复现**
是
**运行环境:**
 - OS:Win11
 - Python版本:
 - 3.11.2
 - 软件版本: 
 - 微信版本:
 - 3.9.6.33

**Additional context**

**Comment by LC044** [comment]
试试新版
