### ISSUE TITLE
readme里面有写支持手机端，没看到如何提取手机中的聊天记录

### ISSUE THREAD

**Issue by JLUGQQ** [LC044/WeChatMsg#22]

**Comment by timxi** [comment]
same question here

**Comment by qianhuaipeng** [comment]
加一

**Comment by Lu-Qi-777** [comment]
手机微信点 我 - 设置 - 通用 - 聊天记录迁移与备份 - 迁移 - 迁移到电脑
然后数据就到电脑上了（

**Comment by Iey4iej3** [comment]
迁移到电脑需要 PC 客户端。并不是所有人都愿意安装 PC 客户端（例如 Linux 用户，以及倾向于尽量使用自由软件的用户）。
