### ISSUE TITLE
1、置顶的群聊内容无法导出。2、导出csv是乱码。

### ISSUE THREAD

**Issue by daneyoung01** [LC044/WeChatMsg#220]
1、置顶的群聊内容无法导出。2、导出csv是乱码。 大家也有这个情况吗？

**Comment by occasional15** [comment]
我是置顶群都找不到！！

**Comment by daneyoung01** [comment]
我就是置顶群找不到

**Comment by alex-oos** [comment]
csv 我也是乱码，我导出html就没有问题

**Comment by occasional15** [comment]
> csv 我也是乱码，我导出html就没有问题

CSV是用UTF-8编码的，而EXCEL是ANSI编码，由于编码方式不一致导致出现乱码。所以只需要把CSV文件的编码方式修改成与Excel相同的编码方式就可以了。查看https://blog.csdn.net/weixin_43848614/article/details/107742922

**Comment by occasional15** [comment]
> csv 我也是乱码，我导出html就没有问题

群聊导出HTML应该会报错

**Comment by LC044** [comment]
新版已解决该问题
