### ISSUE TITLE
QCursorGif 不存在

### ISSUE THREAD

**Issue by chen-yingfa** [LC044/WeChatMsg#221]
**是否star**
是
**是否检查过issues没有相同问题**
是
**bug描述**

根据README clone 然后 pip install 之后 `python main.py` 就会报错，是因为 QCursorGif 不存在，import 不了。

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/54496664/43dd57ab-9d3c-4b77-af47-435c592470d7)

**是否可复现**
shi是
**运行环境:**
 - OS: Win11
 - Python版本: 3.11.7
 - 软件版本: main branch at the time of writing
 - 微信版本: does not matter

**Additional context**

**Comment by LC044** [comment]
再试一下
