### ISSUE TITLE
提示解密成功请重启，但是重新打开应用提示数据库错误请重启微信后重试，也看不到聊天记录

### ISSUE THREAD

**Issue by 0sty** [LC044/WeChatMsg#223]
**是否star**
是
**是否检查过issues没有相同问题**
是
**bug描述**
提示解密成功请重启，但是重新打开应用提示数据库错误请重启微信后重试，也看不到聊天记录
**报错截图**
![IMG_20231223_225355](https://github.com/LC044/WeChatMsg/assets/109896079/5518d10b-590e-4773-a58c-88305f6b15ba)
![IMG_20231223_225326](https://github.com/LC044/WeChatMsg/assets/109896079/1cfeef9b-afda-4012-bc79-8747ef807504)
![IMG_20231223_225440](https://github.com/LC044/WeChatMsg/assets/109896079/5703ded9-c26d-46a0-96ef-4dd79530e547)
![mmexport1703343478430](https://github.com/LC044/WeChatMsg/assets/109896079/a38ca59e-f627-4d33-97c5-6008b419ac3f)

**是否可复现**
100%复现
**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:3.11
 - 软件版本: 1.0.0
 - 微信版本:3.9.8.25

**Additional context**

**Comment by biansty** [comment]
我室友用着倒是正常的，怀疑是微信号的问题，重装了微信、用虚拟机也还是不行

**Comment by biansty** [comment]
> **是否star** 是 **是否检查过issues没有相同问题** 是 **bug描述** 提示解密成功请重启，但是重新打开应用提示数据库错误请重启微信后重试，也看不到聊天记录 **报错截图** ![IMG_20231223_225355](https://private-user-images.githubusercontent.com/109896079/292632201-5518d10b-590e-4773-a58c-88305f6b15ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Njk1NTEsIm5iZiI6MTcwMzU2OTI1MSwicGF0aCI6Ii8xMDk4OTYwNzkvMjkyNjMyMjAxLTU1MThkMTBiLTU5MGUtNDc3My1hNThjLTg4MzA1ZjZiMTViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwNTQwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTg1YTU0OGFmOWQzNTY0YTUwMDkyN2ExMTZjNjgwZjA5NWNhZmY1MDY5Njg4NTNhYjAzYzE2ZDVlMTAyZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hpKHWuJ6Zqna7IY_4ocxVo0UOV0QX9e3kIrlMpKwn_s) ![IMG_20231223_225326](https://private-user-images.githubusercontent.com/109896079/292632210-1cfeef9b-afda-4012-bc79-8747ef807504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Njk1NTEsIm5iZiI6MTcwMzU2OTI1MSwicGF0aCI6Ii8xMDk4OTYwNzkvMjkyNjMyMjEwLTFjZmVlZjliLWFmZGEtNDAxMi1iYzc5LTg3NDdlZjgwNzUwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwNTQwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDMzZGJjNDA3YmIyM2E4ODZiNzg2MDViZTdiNTk5OTA2NWRiY2FmYmFkZDEwYTg2MmU3NWNmODc4N2EwNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tX_JCnOCYaQ3OYmxsq_8GhDBOLpYeeSUdWTgryIn2rc) ![IMG_20231223_225440](https://private-user-images.githubusercontent.com/109896079/292632216-5703ded9-c26d-46a0-96ef-4dd79530e547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Njk1NTEsIm5iZiI6MTcwMzU2OTI1MSwicGF0aCI6Ii8xMDk4OTYwNzkvMjkyNjMyMjE2LTU3MDNkZWQ5LWMyNmQtNDZhMC05NmVmLTRkZDc5NTMwZTU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwNTQwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmMyNDZkMDY3YTk5OGYzOTg5ZWMyYzg2NDFjMzY2YmEwMjk1MDkxOWRmNzgwMjUyZDVjZTdlZTA2NGVjMjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oHvmkXZsrL2PEpKrSpbNle7W2JMn7VYb3UPnn-QB_-A) ![mmexport1703343478430](https://private-user-images.githubusercontent.com/109896079/292632241-a38ca59e-f627-4d33-97c5-6008b419ac3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Njk1NTEsIm5iZiI6MTcwMzU2OTI1MSwicGF0aCI6Ii8xMDk4OTYwNzkvMjkyNjMyMjQxLWEzOGNhNTllLWY2MjctNGQzMy05N2M1LTYwMDhiNDE5YWMzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwNTQwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGRiZjhmYmVmNTdiOGYwMDJiMmFkNmQzZmRhOGM2M2MyMGE3NjMzNzE4ZGFkMTFiNDJhNmM4NmUwYjQ0OWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z5R19J5IC-AoK0vFRof4jEd0h09KoeeCIp6fMpv9UGo)
> 
> **是否可复现** 100%复现 **运行环境:**
> 
>     * OS: [e.g. Win11]操作系统：[e.g. Win11]
> 
>     * Python版本:3.11
> 
>     * 软件版本: 1.0.0
> 
>     * 微信版本:3.9.8.25
> 
> 
> **Additional context附加上下文**

问题解决，获取信息后关闭微信，然后再点击开始启动，解密完成后重启应用，一切正常
