### ISSUE TITLE
群聊导出HTML格式闪退

### ISSUE THREAD

**Issue by occasional15** [LC044/WeChatMsg#224]
![image](https://github.com/LC044/WeChatMsg/assets/147971641/2332d0c4-0274-4acb-9981-5bf2143dae2b)
如图，每次选择群聊导出HTML格式格式点击导出后会报错+闪退。

还有一个bug，我的3个置顶群其中2个找不到，取消置顶后，反复重启了n多次才出现。

**Comment by LC044** [comment]
可以等下个版本修复该问题

**Comment by occasional15** [comment]
> 可以等下个版本修复该问题

感谢大佬！希望可以优先修复HTML导出功能，作为小白用户，最想要实现聊天记录的如实保存（重点是文字和图片），HTML和Word格式都可以。个人聊天和群聊都很重要，目前都有bug。

**Comment by LC044** [comment]
试试新版

**Comment by occasional15** [comment]
非常感谢大佬！经过测试1.01版，能够顺畅运行并将群聊导出到Word或HTML。
反馈一个问题：群聊导出到Word后，所有图片均为缩略图（很模糊），我已经在微信中正常加载了图片，并用软件重新解密然后重启。不知道这是bug还是什么原因？
关于群聊导出到Word，希望能在头像旁边添加微信名+群昵称（至少其中一个），这个很重要。
其实我最终的需求是pdf（或epub，可以转成pdf），HTML的界面很好看（比word好看），如果能直接转换成epub或pdf就好了（这时候翻页按钮就比较突兀了），这是一个设想。

**Comment by LC044** [comment]
难道你想把几个G的图片放到word里？

**Comment by occasional15** [comment]
> 难道你想把几个G的图片放到word里？

嘿嘿，确实确实。希望大佬后面可以考虑添加Word中的微信名+群昵称，这样就完美了

**Comment by GreenHatHG** [comment]
> > 试试新版
> 
> 非常感谢大佬！经过测试1.01版，能够顺畅运行并将群聊导出到Word或HTML。 反馈一个问题：群聊导出到Word后，所有图片均为缩略图（很模糊），我已经在微信中正常加载了图片，并用软件重新解密然后重启。不知道这是bug还是什么原因？ 关于群聊导出到Word，希望能在头像旁边添加微信名+群昵称（至少其中一个），这个很重要。 其实我最终的需求是pdf（或epub，可以转成pdf），HTML的界面很好看（比word好看），如果能直接转换成epub或pdf就好了（这时候翻页按钮就比较突兀了），这是一个设想。

请问下大佬最终是pdf这个目前是怎么实现的呢

**Comment by occasional15** [comment]
> 请问下大佬最终是pdf这个目前是怎么实现的呢
我是直接word转pdf的。因为我要做笔记，pdf方便。
