### ISSUE TITLE
年度报告随机闪退，尤其是当通过局域网内其他设备访问时 

### ISSUE THREAD

**Issue by zlj-tyf** [LC044/WeChatMsg#229]
年度报告随机闪退，尤其是当通过局域网内其他设备访问时
当我通过IP地址在我手机上访问年度报告页面时，会随机闪退，尤其是页面renderer部分

**Comment by LC044** [comment]
一定要加上christmat不要只写ip+端口，因为之前的东西没删，ip+端口会报错
