### ISSUE TITLE
提示丢失dll文件，重新安装该dll文件后提示参数错误

### ISSUE THREAD

**Issue by aaaaway** [LC044/WeChatMsg#234]
**是否star**

**是否检查过issues没有相同问题**

**bug描述**
提示丢失dll文件，重新安装该dll文件后提示参数错误

**报错截图**

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11]win7
 - Python版本:
 - 软件版本: 0.2.8
 - 微信版本:3.9.8.15

**Additional context**

**Comment by aaaaway** [comment]
提示丢失api-ms-win-core-path-l1-1-0.dll文件，重新安装该dll文件后提示参数错误

**Comment by aaaaway** [comment]
提示丢失api-ms-win-core-path-l1-1-0.dll文件，重新安装该dll文件后提示参数错误

**Comment by aaaaway** [comment]
![cd017681617a7f75609b6e460048a16](https://github.com/LC044/WeChatMsg/assets/154870947/72a0cf2e-633f-4bc2-99c4-dcbb98db193a)
![9949feedc2ca553e2b61e50d49e78dc](https://github.com/LC044/WeChatMsg/assets/154870947/58e43c51-fd2a-4c10-9cd5-6dfa8df811cf)

**Comment by LC044** [comment]
都2024年了别再用win7了
