### ISSUE TITLE
导出csv乱码 + txt导出无响应  解决

### ISSUE THREAD

**Issue by lorrainely99** [LC044/WeChatMsg#236]
**bug描述**
1. 在好友界面导出某个联系人的记录到csv乱码
2. 在好友界面导出某个联系人的记录到txt 无响应

**解决**
**1. output_pc.py**
   ChildThread(QThread) 中 def to_csv(self):
  ` with open(filename, mode='w', newline='', encoding='utf-8') as file:`
   修改为
  `with open(filename, mode='w', newline='', encoding='utf-8-sig') as file:`

**2. output_pc.py**
  class Output(QThread) 中没有处理TXT选项
  最简单处理把def run(self)里
`elif self.output_type == self.HTM:`
改成
`elif self.output_type == self.HTML or self.output_type == self.TXT:`

**Comment by LC044** [comment]
感谢
