### ISSUE TITLE
No such file or directory: 'app/DataBase/Msg/MSG0.db'

### ISSUE THREAD

**Issue by luoyang871111** [LC044/WeChatMsg#238]
**是否star** 是

**是否检查过issues没有相同问题** 是

**bug描述**

**报错截图**
![5da75ee1fce492d3bdae9dc029738d7](https://github.com/LC044/WeChatMsg/assets/52514896/2c026b46-91b9-4267-9d1e-06811b6f5d10)

**是否可复现**
可以
**运行环境:**
 - OS: Win11
 - Python版本:3.8
 - 软件版本: pycharm
 - 微信版本:3.9.8.25

  File "G:\BaiduNetdiskDownload\WeChatMsg-master\app\ui\tool\pc_decrypt\pc_decrypt.py", line 237, in run
    shutil.copy2("app/DataBase/Msg/MSG0.db", target_database)  # 使用一个数据库文件作为模板
  File "C:\Users\luoya\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\luoya\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'

**Comment by LC044** [comment]
重复issue，而且应该不是只有这一个报错吧

**Comment by luoyang871111** [comment]
已知道原因，电脑端双开微信导致的，关闭一个就可以了
![image](https://github.com/LC044/WeChatMsg/assets/52514896/4977ea7d-0292-4583-b4f4-20d09fdc5be8)
