### ISSUE TITLE
文件夹选择错误，我选择了wxid开头的文件夹

### ISSUE THREAD

**Issue by LipCao** [LC044/WeChatMsg#241]
![22222](https://github.com/LC044/WeChatMsg/assets/22443276/61e83f45-138a-4d08-a4ec-816e092a9e37)
![错误1](https://github.com/LC044/WeChatMsg/assets/22443276/71155e6a-39c5-4a9e-9c35-93726b8d3bd5)
win10, 最新版微信，exe文件和手动运行main.py都是这个错误

**Comment by LC044** [comment]
截图多截一点，看不到关键信息，点击获取信息后出现了啥

**Comment by LipCao** [comment]
> 截图多截一点，看不到关键信息，点击获取信息后出现了啥

点击获取信息是正常的，我卸载了微信，从新备份数据到电脑以后wxid 开头的文件夹没了。。
![screenshot-20231227-163147](https://github.com/LC044/WeChatMsg/assets/22443276/f076a297-e429-4a01-bd0d-dad9c8aa6a5d)
![20231227-163113](https://github.com/LC044/WeChatMsg/assets/22443276/db7d091e-695f-45ee-a5c9-7250bd492602)

**Comment by LC044** [comment]
应该可以用吧

**Comment by LipCao** [comment]
> 应该可以用吧

是可以用，我是Mac电脑，所以我在一个新的windows上操作的，历史的数据就看不到了，备份以后也看不到，这个是正常的吗？ 谢谢解答

**Comment by LC044** [comment]
仔细看一下文档，聊天记录迁移，不是备份

**Comment by LipCao** [comment]
> 仔细看一下文档，聊天记录迁移，不是备份

Sorry, 才知道有这个功能，这么多年一直用的备份，谢啦
