### ISSUE TITLE
导出的CSV文件内容的格式介绍

### ISSUE THREAD

**Issue by Isara-Mo** [LC044/WeChatMsg#242]
能否给出一个详细的导出的csv文件中的列名的含义，以及type和 Subtype下不同数值的含义

**Comment by LC044** [comment]
网上有很多有关介绍，可以搜一下，我就不过多解释了，如果你搜集到了有关信息可以补充一下文档，非常感谢

**Comment by ZHYCarge** [comment]
我在网上找到了个类似的，可以分享给你
[https://github.com/xaoyaoo/PyWxDump/blob/master/doc/wx数据库简述.md](https://github.com/xaoyaoo/PyWxDump/blob/master/doc/wx数据库简述.md)
