### ISSUE TITLE
增加了【群聊聊天记录分析】代码，希望能有所帮助

### ISSUE THREAD

**Issue by DayDreammy** [LC044/WeChatMsg#245]
完成了群聊聊天记录分析功能，见https://github.com/DayDreammy/wechat_group_msg_analysis

希望可以有所帮助。

---
目前是对导出的html文件进行解码，希望后面可以直接利用数据库。

**Comment by LC044** [comment]
兄弟你这个就有点绕弯路了，提供csv就是给开发人员准备的，读取csv会更方便且通用

**Comment by LC044** [comment]
另外，聊天记录查找与分析在app/DataBase/msg.py里，你可以看看里面的代码添加群聊的分析，感谢

**Comment by DayDreammy** [comment]
> 兄弟你这个就有点绕弯路了，提供csv就是给开发人员准备的，读取csv会更方便且通用

ok，感谢哥们！csv我看了，没发现哪一个属性是用户名。如果是 `TalkerId` 的话，那现在所有的 `TalkerId` 都是1 . 我导出了3个不同的群都是这样。
![image](https://github.com/LC044/WeChatMsg/assets/107911537/088ab559-4ef1-49d8-a536-040b8b878ec2)

**Comment by DayDreammy** [comment]
ok，刚看了`msg.py`源码。这里没有群聊信息发送人~ 请指出，拿到这个我后面就好加了。
```
def get_messages(self, username_):
        '''
        return list
            a[0]: localId,
            a[1]: talkerId, （和strtalker对应的，不是群聊信息发送人）
            a[2]: type,
            a[3]: subType,
            a[4]: is_sender,
            a[5]: timestamp,
            a[6]: status, （没啥用）
            a[7]: str_content,
            a[8]: str_time, （格式化的时间）
            a[9]: msgSvrId,
            a[10]: BytesExtra,
            a[11]: CompressContent,
        '''
        ```

**Comment by LC044** [comment]
群聊的csv确实少了两个字段，导出全部聊天记录那里加了发送者昵称，可以参考那个改一下

**Comment by DayDreammy** [comment]
> 群聊的csv确实少了两个字段，导出全部聊天记录那里加了发送者昵称，可以参考那个改一下

where，没找到
