### ISSUE TITLE
建议丰富导出聊天记录后的消息类别

### ISSUE THREAD

**Issue by LTcorpio** [LC044/WeChatMsg#247]
导出聊天记录为 HTML 后，部分消息如分享的链接、小程序、视频号、微信红包、转账、分享的位置等都没有显示。分享的文件，建议无论文件是否过期都能够显示文件名称和文件大小。

**Comment by LipCao** [comment]
> 以后会慢慢更新的

建议html可以搜索哈更方便

**Comment by yudidi** [comment]
> 以后会慢慢更新的

用户分享的链接之类的，现在导出不了。比如高德分享的地址之类的。

**Comment by LC044** [comment]
都支持了
