### ISSUE TITLE
群聊导出Word功能建议

### ISSUE THREAD

**Issue by occasional15** [LC044/WeChatMsg#251]
以下建议均针对群聊导出Word：

1 建议新增按日期筛选导出范围，因为有时只需要导出部分内容，这样可以节省时间。

2 导出的图片都很模糊，但很多图片确实很重要，需要在word中保证清晰度（不在乎导出word文件过大），不然重新一张张手动替换又很麻烦，希望有导出原图选项。还可以通过日期范围筛选+图片清晰度设置来达到控制文件大小。

3 希望在word中（头像旁）添加人物微信名（昵称）。

4 引用的内容：对于引用的文字，可以正常显示；而引用其他内容比如图片，则会显示“未知引用”，希望可以如实标注。

5 许多内容在导出的word中并无记录，希望可以加上。如：【很重要】转发的聊天记录（至少备注“转发的聊天记录”标识，可考虑按正常内容全文展开）；【很重要】文件（文件名+扩展名+大小）；转账记录；分享的链接；语音、视频、等等其他信息，重在有记录可寻。

其他的想到了再来反馈，感谢大佬！

**Comment by LC044** [comment]
可以关注公众号获取更新通知

**Comment by occasional15** [comment]
> 可以关注公众号获取更新通知

已关注，每天都上这里来等更新呢。才意识到，有人会经常换头像，word里面没有微信名和备注，已经分不清了谁是谁了，希望大佬提高日程优先级

**Comment by LC044** [comment]
> > 可以关注公众号获取更新通知
> 
> 已关注，每天都上这里来等更新呢。才意识到，有人会经常换头像，word里面没有微信名和备注，已经分不清了谁是谁了，希望大佬提高日程优先级

还在不断优化中，发布新版本会在公众号通知大家的

**Comment by occasional15** [comment]
感谢大佬！最新版（1.03）已使用，新增了按日期范围导出后，速度直接起飞！目前最重要的诉求是，word中新增微信名和备注，希望大佬早日提上日程！再次感谢大佬~
