### ISSUE TITLE
聊天记录里不能导出公众号链接

### ISSUE THREAD

**Issue by Really-well** [LC044/WeChatMsg#252]
**是否star** 
是

**是否检查过issues没有相同问题** 
已检查，没有相同问题

**bug描述**
导出的聊天记录里没有公众号链接

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/128007304/b00957a0-d956-4f44-9b32-da346a5bbf89)
![image](https://github.com/LC044/WeChatMsg/assets/128007304/c0c5ffa1-b901-4e73-ab72-d2354d03f934)

**是否可复现**
可以复现

**运行环境:**
 - OS: [e.g. Win11] Windows 10 家庭中文版
 - Python版本: 直接采用MemoTrace-1.0.1
 - 软件版本: MemoTrace-1.0.1
 - 微信版本: 3.9.8.25

**Additional context**

**Comment by occasional15** [comment]
同求
