### ISSUE TITLE
每次解密到90%闪退

### ISSUE THREAD

**Issue by 0x-eth** [LC044/WeChatMsg#254]
**是否star**
是

**是否检查过issues没有相同问题**
否

**bug描述**
每次解密到90%闪退

**报错截图**
![微信截图_20240101105231](https://github.com/LC044/WeChatMsg/assets/78288949/d931011d-95ea-4038-8996-b8aaa1a0b392)

**运行环境:**
 - OS: Win10
 - Python版本: 3.12
 - 软件版本: 1.0.1
 - 微信版本: 3.9.8.25

**Comment by LC044** [comment]
你没有给程序读写权限

**Comment by 0x-eth** [comment]
> 你没有给程序读写权限

我要如何解决

**Comment by LC044** [comment]
下载exe程序试试

**Comment by 0x-eth** [comment]
> 下载exe程序试试

一样的，我最先使用的就是exe程序

**Comment by LC044** [comment]
用管理员运行

**Comment by 0x-eth** [comment]
> 用管理员运行

把微信文件夹权限设置成完全访问解决了，谢谢
