### ISSUE TITLE
导出聊天记录不完整

### ISSUE THREAD

**Issue by thechentr** [LC044/WeChatMsg#256]
有的好友聊天记录恢复到手机上时包含完整的从加好友那天起的聊天记录，使用软件导出则缺少加好友前几天的记录

**Comment by wang77dj** [comment]
我也存在此问题，是不是记录太多了呢？

**Comment by LC044** [comment]
缺少加好友前几天的记录是啥意思，加好友前哪来的聊天记录

**Comment by junluo-aspecta** [comment]
> 缺少加好友前几天的记录是啥意思，加好友前哪来的聊天记录

我猜测是加上好友后，前几天的记录

**Comment by heehee365** [comment]
我也遇到相同的问题，我是4月14日加的好友，PC端的微信能看到那之后的记录，可是导出来的记录是从8月份到现在的记录，现在已经是新的一年的一月份了

**Comment by thechentr** [comment]
我好像发现了问题的原因，当前解密的数据库是`wxid_xxxxxxxxxxxx\\Msg`中的数据（这里的数据似乎是电脑wechat所能显示的所有聊天记录），而真正的备份的数据在`wxid_xxxxxxxxxxxx\\BackupFiles`中。可以试一下，如果使用刚刚下载的微信导出聊天记录，则数据量十分少。

**Comment by LC044** [comment]
你看我写的教程啊，”迁移而不是备份“说了三遍

**Comment by thechentr** [comment]
救命，原来是这样！请问如果迁移时一直显示“未发现可迁移的设备”怎么解决啊，已经连接在了一个wifi下，并关闭了防火墙还是不可以。

**Comment by ftx66** [comment]
> 救命，原来是这样！请问如果迁移时一直显示“未发现可迁移的设备”怎么解决啊，已经连接在了一个wifi下，并关闭了防火墙还是不可以。

手机开热点连电脑吧，我这样挺快的
