### ISSUE TITLE
请求优化导出的html聊天记录手机端页面展示

### ISSUE THREAD

**Issue by zxjathome** [LC044/WeChatMsg#257]
**是否star**
是

**是否检查过issues没有相同问题**
是

**bug描述**
手机之类的窄页面下，布局会错乱

**报错截图**
![DD2JYC~W4JR_7CLKMKHYB K](https://github.com/LC044/WeChatMsg/assets/30248127/614eaba3-a176-48c5-ab68-4c893d9a056a)

**是否可复现**
是

**运行环境:**
 - OS: Windows11
 - Python版本:
 - 软件版本: 1.0.1
 - 微信版本:3.9.8

**Additional context**
试着用自己浅薄的前端知识改了一下，将.pagination-container移到了页面底部，并微调了一下。
无论是在PC浏览器还是窄屏的手机浏览器上，效果看起来都正常了很多
![0@)3CWE@4K$HNM%X2V2ZS2G](https://github.com/LC044/WeChatMsg/assets/30248127/3b848204-f3e6-4909-afe7-835cfd17da72)
![X7W_8MRX1RY2$319L4GXF3S](https://github.com/LC044/WeChatMsg/assets/30248127/d0c58acc-d6b0-466c-a217-8b12f32cd83c)

**Comment by LC044** [comment]
已经适配了，可以等下个版本，可以关注微信号获取更新日志
