### ISSUE TITLE
导出聊天记录类型缺失

### ISSUE THREAD

**Issue by xianyu21** [LC044/WeChatMsg#260]
导出记录
![1704189262188](https://github.com/LC044/WeChatMsg/assets/35288214/0f6c7bfc-11b1-45d5-b00d-1a94fc402594)
微信记录
![1704189209192](https://github.com/LC044/WeChatMsg/assets/35288214/7c756e93-cc7b-4200-abf2-16f2ca55e4bc)
这个好像是ios的语音备忘录 转发过来的

**Comment by LC044** [comment]
这不是写了丢失了吗
