### ISSUE TITLE
[Request] 建议

### ISSUE THREAD

**Issue by QiMiBieJiao** [LC044/WeChatMsg#261]

**Comment by LC044** [comment]
考虑到安全问题，暂时不允许用户自己输入key、等信息，不然我直接把信息写入到info里了

**Comment by QiMiBieJiao** [comment]
我看来每次都重新编译一份可以输入的了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LC044/WeChatMsg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月2日(星期二) 晚上10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LC044/WeChatMsg] [Request] 建议将手机号，微信名，微信id ，key等相关ui由label改为lineedit (Issue #261)



 
考虑到安全问题，暂时不允许用户自己输入key、等信息，不然我直接把信息写入到info里了
