### ISSUE TITLE
[Question] 为什么界面内是 Copyright ShuaikangZhou 而github是GPL3

### ISSUE THREAD

**Issue by zuoanqh** [LC044/WeChatMsg#262]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

为什么界面内不标gpl3 license

### 📝 补充信息 | Additional Information

<img width="636" alt="image" src="https://github.com/LC044/WeChatMsg/assets/8357370/de6c4a2d-7c03-4e2c-b26c-fe1c7d8913bd">
https://github.com/LC044/WeChatMsg/blob/master/LICENSE

**Comment by LC044** [comment]
有什么问题？
