### ISSUE TITLE
[Request] 增加语音的分类

### ISSUE THREAD

**Issue by DoshideDK** [LC044/WeChatMsg#264]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

导出的语音两人是放在一起的，手动分类不现实

### 🧐 解决方案 | Proposed Solution

导出时根据来源，自动分类语音的发出者

### 📝 补充信息 | Additional Information

其他文件最好也做一下拆分功能

**Comment by LC044** [comment]
分类之后有什么具体需求吗

**Comment by DoshideDK** [comment]
有，比如说想训练对方的语音模型

**Comment by DoshideDK** [comment]
导出时把双方的语音分开放放置，就很方便了

**Comment by LC044** [comment]
最新版已实现
