### ISSUE TITLE
[Question] 导出HTML只能显示固定内容

### ISSUE THREAD

**Issue by Armsinrius** [LC044/WeChatMsg#268]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

![image](https://github.com/LC044/WeChatMsg/assets/36504277/4683766e-6ba7-4948-a6a2-d7853aa62fd8)
导出HTML后, 用chrome打开这个HTML文件只能停留在这个画面，但是用VS　CODE打开该文件可以在下面看到聊天记录与内容

**Comment by LC044** [comment]
应该是HTML出现了转义字符，vscode打开看看是哪个字符出错了，反馈一下我修一下bug

**Comment by Armsinrius** [comment]
> 应该是HTML出现了转义字符，vscode打开看看是哪个字符出错了，反馈一下我修一下bug

抱歉，我真的没写过HTML, 真的不知道怎么看哪里出错了.

**Comment by LC044** [comment]
你打开vscode他有代码提示，聊天记录是用类似Python字典存储的，出问题的地方颜色跟前面的不一样，主要看引号和大括号｛

**Comment by Armsinrius** [comment]
应该是和选择了导出文件名有关,最后选择只导出文字和图片就没这个问题了. 谢谢. 有些文件名导致了你说的问题
