### ISSUE TITLE
导出聊天记录的起始日期是根据迁移到电脑上起始日期开始计算的，如何重置这个起始日期

### ISSUE THREAD

**Issue by daneyoung01** [LC044/WeChatMsg#269]
### 👌 是否检查过没有类似issue

None

### 🧐 问题描述 | Proposed Solution

之前迁移聊天记录，自定义开始日期为2023年1月，导出聊天记录的起始日期就是2023年1月。现在希望导出聊天记录的起始日期是2024年1月。如何删除之前的迁移，重新设置新的迁移。或者有没有功能可以设置导出聊天记录的起始日期的？

**Comment by LC044** [comment]
等后续更新吧，未来会实现自定义导出时间的

**Comment by LC044** [comment]
1.0.3支持自定义导出时间

**Comment by daneyoung01** [comment]
点赞
