### ISSUE TITLE
进度一直卡在97%

### ISSUE THREAD

**Issue by alongLFB** [LC044/WeChatMsg#27]
**Describe the bug**
![image](https://github.com/LC044/WeChatMsg/assets/17883682/055f7a7a-fd0b-4b00-a158-b8aa259d5622)

![image](https://github.com/LC044/WeChatMsg/assets/17883682/a0324c50-e4ec-4310-b209-be466a242f6a)

点击解密后 卡在 97 %进度很久了 不知道啥原因 在点击一次解密 直接就崩溃了。

**Comment by LC044** [comment]
你把产生的文件都删了再重新运行一下看看是不是还这样，如果还是这样的话你到微信文件保存路径就那个wxid底下MSG下的文件发个截图，要有各个文件的详细信息
