### ISSUE TITLE
[Bug] 签个名吧

### ISSUE THREAD

**Issue by HeavySnowJakarta** [LC044/WeChatMsg#273]
### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.12

### 💻 微信版本

None

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

签个开发者证书吧，要不提示通常不会下载此文件，挺难受的。

**Comment by LC044** [comment]
怎么签

**Comment by HeavySnowJakarta** [comment]
简单说，找ca机构，要交不少钱。它不像苹果有个苹果账号就能签。你也可以自己生成证书，但是这个证书是不被ca信任的，签了等于没签。

https://stackoverflow.com/questions/252226/signing-a-windows-exe-file

**Comment by LC044** [comment]
> 简单说，找ca机构，要交不少钱。它不像苹果有个苹果账号就能签。你也可以自己生成证书，但是这个证书是不被ca信任的，签了等于没签。
> 
> https://stackoverflow.com/questions/252226/signing-a-windows-exe-file

多谢，我晓得了，钱从哪领，我去签个证书

**Comment by HeavySnowJakarta** [comment]
> > 简单说，找ca机构，要交不少钱。它不像苹果有个苹果账号就能签。你也可以自己生成证书，但是这个证书是不被ca信任的，签了等于没签。
> > 
> > https://stackoverflow.com/questions/252226/signing-a-windows-exe-file
> 
> 多谢，我晓得了，钱从哪领，我去签个证书

我也想领钱，要是还能有个苹果开发者账号那就更好了

**Comment by LC044** [comment]
> > > 简单说，找ca机构，要交不少钱。它不像苹果有个苹果账号就能签。你也可以自己生成证书，但是这个证书是不被ca信任的，签了等于没签。
> > > https://stackoverflow.com/questions/252226/signing-a-windows-exe-file
> > 
> > 
> > 多谢，我晓得了，钱从哪领，我去签个证书
> 
> 我也想领钱，要是还能有个苹果开发者账号那就更好了

那就先难受着吧，我这里一点都不难受

**Comment by hanfangyuan4396** [comment]
扯淡的需求，哈哈

**Comment by wuzimo233** [comment]
这也算。。

**Comment by sjxqzl** [comment]
真是牛人。

**Comment by wzy52z** [comment]
ca来打广子的啊
