### ISSUE TITLE
[Bug] 1.0.2解密成功后重启不了，双击程序电脑上转会儿圈就没反应了，1.0.1正常使用

### ISSUE THREAD

**Issue by sssomeoneee** [LC044/WeChatMsg#274]
### 👌 是否检查过没有类似issue

是

### 💻 Python版本

Other

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

 1.0.2解密成功后重启不了，双击程序电脑上转会儿圈就没反应了，1.0.1正常使用，win10版本

**Comment by LC044** [comment]
怎么个没反应，其他人都正常使用，应该是你电脑的问题，换个电脑再试试

**Comment by LC044** [comment]
已找到问题，可以等下个版本

**Comment by yuchen0010** [comment]
刚好第一次用就给我碰上了🫥

**Comment by nnwaiting** [comment]
我也有这个问题，昨天晚上还能用，今天不行了

**Comment by carolusliu** [comment]
解密成功之后，提示重启，我的是点击之后，直接没有反应。
删了app/database/msg目录，重新运行，重新解密成功后，重启还是没有反应。

2024-01-08 09:52:19,207 - main.py[line:97] - ERROR: None
2024-01-08 09:55:17,051 - main.py[line:97] - ERROR: None
2024-01-08 09:59:55,548 - main.py[line:29] - ERROR: 程序发生了错误:

Exception Type: OperationalError
Exception Value: no such table: ContactLabel
details: Traceback (most recent call last):
  File "app\ui\chat\chat_window.py", line 137, in run
  File "app\DataBase\micro_msg.py", line 58, in get_contact
sqlite3.OperationalError: no such table: ContactLabel

2024-01-08 10:01:00,261 - main.py[line:97] - ERROR: None
2024-01-08 10:06:54,253 - main.py[line:97] - ERROR: None

**Comment by LC044** [comment]
> 解密成功之后，提示重启，我的是点击之后，直接没有反应。 删了app/database/msg目录，重新运行，重新解密成功后，重启还是没有反应。
> 
> 2024-01-08 09:52:19,207 - main.py[line:97] - ERROR: None 2024-01-08 09:55:17,051 - main.py[line:97] - ERROR: None 2024-01-08 09:59:55,548 - main.py[line:29] - ERROR: 程序发生了错误:
> 
> Exception Type: OperationalError Exception Value: no such table: ContactLabel details: Traceback (most recent call last): File "app\ui\chat\chat_window.py", line 137, in run File "app\DataBase\micro_msg.py", line 58, in get_contact sqlite3.OperationalError: no such table: ContactLabel
> 
> 2024-01-08 10:01:00,261 - main.py[line:97] - ERROR: None 2024-01-08 10:06:54,253 - main.py[line:97] - ERROR: None

你的微信版本是多少

**Comment by Coco422** [comment]
大佬好，我微信版本3.9.8.25
第一次打开1.0.2后点击开始获取后进度条98卡了几分钟，我就直接重启了，重启后就报
Traceback (most recent call last):
  File "app\ui\contact\contact_window.py", line 133, in run
TypeError: 'NoneType' object is not iterable
换1.0.1之后也是一样的情况

**Comment by G11sleeping** [comment]
我也是这样，重启之后再点就没反应了
看任务管理器是启动了一下就闪退了

**Comment by LC044** [comment]
1.0.3已解决该问题
