### ISSUE TITLE
[Request] 希望能够导出已删除或退出的群聊的聊天记录

### ISSUE THREAD

**Issue by LTcorpio** [LC044/WeChatMsg#277]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

早些时候，在退出群聊后，微信并没有提供“退出但保留聊天记录”的选项，在主页面搜索是搜不到这些群聊的聊天记录的。实际上，这部分聊天记录可以在PC端“设置-通用设置-存储空间管理-聊天数据管理”页面中查看。而针对目前“退出但保留聊天记录”的群聊，我不确定在迁移后是否手机和PC端都会将这些聊天记录进行迁移。因此：
需求1：希望能够导出退出后的群聊的聊天记录（无法在电脑端微信主页面搜索到任何聊天记录，但可以在“聊天数据管理”中查看到）。
需求2：希望能够导出“退出但保留聊天记录”的群聊的聊天记录。

![image](https://github.com/LC044/WeChatMsg/assets/41532915/87c9a88c-5516-4928-889b-bdbc2a264583)

### 🧐 解决方案 | Proposed Solution

无。

### 📝 补充信息 | Additional Information

不清楚在迁移或备份聊天记录后，已经退出的聊天记录是否能够被迁移或备份。如果不能，那么在更换电脑或重装系统后，这些隐藏的数据都将被删除。希望能够通过该项目，拿回即将丢失的数据。

**Comment by Black-Rhen** [comment]
我也很需要这个功能，不知道原生文件能不能转成txt啊
