### ISSUE TITLE
请问是否未来可以添加微信聊天记录备份文件解密功能

### ISSUE THREAD

**Issue by sxuan2** [LC044/WeChatMsg#28]
请问是否未来可以添加微信聊天记录备份文件解密功能。
因为现在聊天记录备份文件，如果移动了路径（换设备，重装系统，或者单纯放在硬盘里备份）就再也无法读取了，基本上以前的备份文件都成为了废数据，如果能利用起来是非常有帮助的。
-------------------------------------------------------------------
请关掉这个issue，是我使用了错误的微信号，导致备份文件无法读取

**Comment by deardeer7** [comment]
我也想问下这个问题，因为完整的聊天记录都在手机上，我备份到电脑上后，发现聊天记录好像没有合并到电脑端上，跑了下程序，数据也只是PC端微信的，这块有什么好的办法吗

**Comment by LC044** [comment]
软件导出的db数据库是可以永久存储的，无论是移动到哪都能再次利用

**Comment by moleoxa** [comment]
> 软件导出的db数据库是可以永久存储的，无论是移动到哪都能再次利用

有个需求，不知道大佬能否考虑实现。

需求：定期备份手机聊天记录到PC端，然后解密备份合并到sqlite数据库。
难点：定期备份会重复备份部分历史备份过的聊天记录，如何实现解密后增量合并到数据库？
