### ISSUE TITLE
[Bug] 貌似最早的聊天记录只能抓取到2022年4月份，不知道是不是只是我的问题

### ISSUE THREAD

**Issue by ftx66** [LC044/WeChatMsg#282]
### 👌 是否检查过没有类似issue

否

### 💻 Python版本

3.12

### 💻 微信版本

3.9.8.15

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

貌似最早的聊天记录只能抓取到2022年4月份，包括我在程序导出html中也是最早到2022年4月，同时2023年只有1月、10月、11月、12月的数据。但是在微信中查看是全包含的。希望作者大大能够解答一下，感谢作者！

**Comment by LC044** [comment]
你发个app/DataBase/Msg里的db文件截图，主要是那几个MSG.db

**Comment by ftx66** [comment]
> 你发个app/DataBase/Msg里的db文件截图，主要是那几个MSG.db

![拼接图](https://github.com/LC044/WeChatMsg/assets/117646924/54f1a187-5c5b-469e-8567-d5562929e7c3)

**Comment by ftx66** [comment]
> 你发个app/DataBase/Msg里的db文件截图，主要是那几个MSG.db
麻烦大佬了，谢谢大佬！！！

**Comment by LC044** [comment]
你再发一个微信数据库文件的截图，在微信保存路径下，Msg/Multi/文件夹下，也是MSG.db那几个文件

**Comment by LC044** [comment]
你是用的源码吧，你把app/DataBase/merge.py里的74行加一句话
logger.error(traceback.format_exc())，或者把try,except这个去掉，看看会报啥错

**Comment by ftx66** [comment]
> 你是用的源码吧，你把app/DataBase/merge.py里的74行加一句话 logger.error(traceback.format_exc())，或者把try,except这个去掉，看看会报啥错

我是下载exe文件的，版本是1.0.2

**Comment by LC044** [comment]
> > 你是用的源码吧，你把app/DataBase/merge.py里的74行加一句话 logger.error(traceback.format_exc())，或者把try,except这个去掉，看看会报啥错
> 
> 我是下载exe文件的，版本是1.0.2

那就等一个会用python的发现这个问题再解决吧

**Comment by LC044** [comment]
不用代码的话发现不了问题

**Comment by ftx66** [comment]
> 不用代码的话发现不了问题

那我尝试一下删除重下看看问题是否会复现吧～

**Comment by LC044** [comment]
> > 不用代码的话发现不了问题
> 
> 那我尝试一下删除重下看看问题是否会复现吧～

可以多试几次，不行的话等后续版本解决问题

**Comment by LC044** [comment]
你运行的是源码吧

**Comment by LC044** [comment]
可以拉取一下最新代码重新解密一下看看有哪些报错

**Comment by jameszu** [comment]
哈喽，我也有相同的问题。 
我把那个try catch 去掉了之后有如下的报错
![image](https://github.com/LC044/WeChatMsg/assets/41566813/acae1ee7-fcd9-49d8-981b-9d2789ec59d1)
![image](https://github.com/LC044/WeChatMsg/assets/41566813/f2b83493-b530-43fd-8d5a-9fbc8f496cc3)
我的微信版本和代码版本都是最新的

**Comment by itspidercn** [comment]
我从2020年开始的群聊记录，基本是完整的。
供参考

**Comment by cmyang-it** [comment]
你好我也遇到同意的问题，看了数据库 MSG4.db 和 MSG6.db 是空的。

2024-06-06 22:34:09,178 - pc_decrypt.py[line:335] - INFO: 从云端获取内存基址失败:3.9.10.27
2024-06-06 22:35:23,800 - merge.py[line:77] - ERROR: ./app/Database/Msg\MSG4.db数据库合并错误:
Traceback (most recent call last):
  File "E:\workspace\WeChatMsg\app\DataBase\merge.py", line 67, in merge_databases
    cursor.execute(sql)
sqlite3.OperationalError: no such table: MSG

2024-06-06 22:35:24,501 - merge.py[line:77] - ERROR: ./app/Database/Msg\MSG6.db数据库合并错误:
Traceback (most recent call last):
  File "E:\workspace\WeChatMsg\app\DataBase\merge.py", line 67, in merge_databases
    cursor.execute(sql)
sqlite3.OperationalError: no such table: MSG


![截图](https://github.com/LC044/WeChatMsg/assets/41405161/934b5335-8353-4f60-8a6f-6ec727b54768)
