### ISSUE TITLE
正在解密时突然关闭软件，再次打开一直显示Unhandled Exception(未响应)[Question] 

### ISSUE THREAD

**Issue by Kvan-K** [LC044/WeChatMsg#283]
### 👌 是否检查过没有类似issue

None

### 🧐 问题描述 | Proposed Solution

![无标题](https://github.com/LC044/WeChatMsg/assets/92514010/ae05f680-5816-4e6a-9eac-e44de6fbb1f3)
如图所示，谢谢

**Comment by LC044** [comment]
试试1.0.1看看有什么显示，把黑框里的报错截图发给我

**Comment by wamian1939** [comment]
同样问题，说是多开或者没有更新到最新版微信

**Comment by LC044** [comment]
1.0.3已解决该问题
