### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by UYSAUIYO** [LC044/WeChatMsg#284]
### 👌 是否检查过没有类似issue

否

### 💻 Python版本

3.12

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![1704715979342](https://github.com/LC044/WeChatMsg/assets/65168184/1fbc5c08-3931-4290-9fb4-5013736e59ea)

### 📷 复现步骤 | Recurrence Steps

第一次打开解密数据库后自动重启，重启后即出现报错弹窗。

**Comment by LC044** [comment]
多重启一下电脑重新解密

**Comment by LC044** [comment]
1.0.3已解决该问题
