### ISSUE TITLE
[Bug]跟一个人的聊天记录太多，导致导出后的html文件，对方的头像显示不出来

### ISSUE THREAD

**Issue by xydgithub** [LC044/WeChatMsg#286]
### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

None

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:

![微信截图_20240109075614](https://github.com/LC044/WeChatMsg/assets/49560940/82f864eb-4e04-44bb-971d-92354f6861e2)

**Comment by LC044** [comment]
填几个选项很难吗
