### ISSUE TITLE
[Request] 怎么设置导出的默认勾选

### ISSUE THREAD

**Issue by pingyuan2016** [LC044/WeChatMsg#287]
### 👌 是否检查过没有类似issue

否

### 🥰 需求描述 | Feature Description

![image](https://github.com/LC044/WeChatMsg/assets/25808622/cee507cc-0fb4-45f7-bcb8-ce18776297e1)
每次都要重新选择，如果好友较多，要一个一个点，比较麻烦

### 🧐 解决方案 | Proposed Solution

不知道代码中有没有可以设置的，我去改改

### 📝 补充信息 | Additional Information

无

**Comment by LC044** [comment]
最新代码已经支持批量导出，在菜单栏->数据那里选择

**Comment by pingyuan2016** [comment]
收到，我现在去给你送杯big奶茶

**Comment by pingyuan2016** [comment]
感觉批量导出卡卡的，有时候选中两个，但实际上，导出只有一个，看日志，鼠标选中了，但是日志显示没选中

**Comment by LC044** [comment]
是最新代码吗

**Comment by pingyuan2016** [comment]
拉的最新代码，试的会有点小bug，如果选择两个，第一个选的或者最后一个选的，会有几率选择不上，不是必现的，没事，问题不大

**Comment by LC044** [comment]
我之前也有这个问题，但是现在复现不出来了
