### ISSUE TITLE
数据解密成功后报错

### ISSUE THREAD

**Issue by nonu11** [LC044/WeChatMsg#29]
**Describe the bug**
数据库解密成功后无法使用程序打开数据库文件，报错后在闪退结束。

1. 首次打开程序，提示
![图片](https://github.com/LC044/WeChatMsg/assets/17950878/5cf5dc73-4724-4156-a158-b632f0af9ce4)

2. 获取解密信息正常
![图片](https://github.com/LC044/WeChatMsg/assets/17950878/5de9bea7-b790-4938-9fc2-6714d50754bc)

3.解密成功后报错退出
![图片](https://github.com/LC044/WeChatMsg/assets/17950878/2c8d904c-b3f5-4a69-ab2e-004e5b078bc2)

4.有成功生成解密db文件
![图片](https://github.com/LC044/WeChatMsg/assets/17950878/546a133b-beea-430c-93d7-c5d641794699)

测试环境：
OS：windows10
微信：3.9.8.15
SQLiteStudio：3.4.4
WeChatMsg：MemoTrace-0.2.4.exe

**Comment by LC044** [comment]
重新登录微信试试可以不

**Comment by qingshuicn** [comment]
我是解密成功后，就一直闪退了
管理员运行也不行
