### ISSUE TITLE
[Bug] 对于多数据库的解密出错

### ISSUE THREAD

**Issue by ConCose** [LC044/WeChatMsg#290]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

寻找一个Msg数据库分页为3个及以上的微信号
正常登录获取信息
解密重启后报错
翻看app/database发现其中只有msg0msg1两个数据库分页。
报错截图：【请重启微信后重试】.jpg

### 📷 复现步骤 | Recurrence Steps

寻找一个Msg数据库分页为3个及以上的微信号
正常登录获取信息
解密重启后报错
翻看app/database发现其中只有msg0msg1两个数据库分页。

**Comment by LC044** [comment]
图呢
