### ISSUE TITLE
[Request] 导出的聊天记录支持按时间、类型进行检索。

### ISSUE THREAD

**Issue by zhufacai** [LC044/WeChatMsg#291]
### 👌 是否检查过没有类似issue

就不检查

### 🥰 需求描述 | Feature Description

感谢大佬

### 🧐 解决方案 | Proposed Solution

参考http://wxbackup.imxfd.com/demo/index.html

**Comment by LC044** [comment]
所以你为什么不检查一下有没有类似issue
