### ISSUE TITLE
[Bug] 微信双开抓取信息失败

### ISSUE THREAD

**Issue by RichardFWC** [LC044/WeChatMsg#292]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

None

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
确实有两个微信号在一个电脑上，平时会双开使用，但是抓取信息的时候只开了一个，选择的文件夹也没错，但是就是运行不了；
![image](https://github.com/LC044/WeChatMsg/assets/47077871/ea1833dd-1764-4345-9ff0-7961b21350fa)
![image](https://github.com/LC044/WeChatMsg/assets/47077871/be319b03-f26c-4ffc-a920-9f1e38a081b3)

### 🚦 期望结果 | Expected Behavior

是功能不支持还是什么原因

**Comment by LC044** [comment]
把双开关了不就行了

**Comment by RichardFWC** [comment]
已经关了。并且重新抓取了，还是提示这样

**Comment by RichardFWC** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/47077871/d40e1a07-aa7b-4bf6-9a13-0c141ad51af4)

**Comment by LC044** [comment]
可以重装一下微信

**Comment by RichardFWC** [comment]
重装解决了，非常感谢，但是读取不了公众号的推文链接信息

**Comment by LC044** [comment]
公众号的推文链接信息是指哪些可以截个图吗

**Comment by RichardFWC** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/47077871/69336ae1-fc51-40f0-84df-a7791b6b6cb5)

**Comment by LC044** [comment]
这种可以吧，你导出HTML把那个分享卡片勾上

**Comment by RichardFWC** [comment]
成功了，导出html或txt都有链接的信息，非常感谢帮助，打赏一下~
