### ISSUE TITLE
[Bug] 无法打开MemoTrace

### ISSUE THREAD

**Issue by LeonXu260** [LC044/WeChatMsg#293]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图: 我的微信聊天记录是存到NAS上的，当我登录微信并且获得或者在NAS上的路径之后，MemoTracer无法打开。尝试过多少次都不行。

### 🚦 期望结果 | Expected Behavior

可以解读存储在NAS上的微信聊天记录。

### 📷 复现步骤 | Recurrence Steps

1. 打开MemoTracker并且登录微信，确定路径存在NAS中
2. 在MemoTracer中访问NAS\WeChat Files\wxid_xxxx路径
3. 解密成功之后，提示重启，但是软件无法重启。

**Comment by LC044** [comment]
别乱搞，正常用微信

**Comment by LeonXu260** [comment]
没乱搞，我所有的微信数据都是存在我自己的NAS上面，因为微信备份需要占用本地磁盘，所以移到NAS上，微信可以读到NAS上的聊天记录。

**Comment by LC044** [comment]
没必要为你一个人做适配

**Comment by LC044** [comment]
把微信存到电脑硬盘上应该也不费劲

**Comment by zetaloop** [comment]
试试 git clone 用自己的 python 环境？
我用 exe 一开始就打不开（弹了个提示，主界面出不来），但是直接用代码就可以。
