### ISSUE TITLE
[Request] 进度条计导出消息数，而非人数

### ISSUE THREAD

**Issue by zetaloop** [LC044/WeChatMsg#299]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

![image](https://github.com/LC044/WeChatMsg/assets/36418285/6bce1c5c-2282-46d8-b08c-ce934613c445)
目前进度条是按**导出人数**计算。
大部分人对话很少，很快就完成了导出，进度条前面部分走的很快。
少部分人对话很多，导出需要很长时间，进度条会在98%左右持续很长时间。

将进度条改为根据**导出消息数**来计算，这样显示的进度更加均匀。

### 🧐 解决方案 | Proposed Solution

进度条改为计算消息条数。

**Comment by LC044** [comment]
加了一个日志窗口，能看到有东西在输出就不会觉得卡住了
