### ISSUE TITLE
这种格式的微信聊天记录是怎么导出来的？

### ISSUE THREAD

**Issue by nissansz** [LC044/WeChatMsg#3]
![image](https://github.com/LC044/WeChatMsg/assets/41010669/3cd30492-af16-456e-bf36-49cf8d63e981)

**Comment by LC044** [comment]
我不太理解你说的格式是什么意思，目前该软件可以导出成word文档，形式跟微信聊天界面一致

**Comment by nissansz** [comment]
就是上面这种格式
人名缩写 + 全名+时间
+聊天内容

从上往下列表

**Comment by LC044** [comment]
你可以看./app/DataBase/Output.py 的to_docx函数，里面有昵称，时间，聊天内容等信息，你可以自己设计输出的格式

**Comment by nissansz** [comment]
还没试这个软件，现在最新的微信，也能导出吗？要安卓还是苹果？
我看这软件好久没更新了

**Comment by LC044** [comment]
> 还没试这个软件，现在最新的微信，也能导出吗？要安卓还是苹果？ 我看这软件好久没更新了

最新的也是可以的，你看一下教程安卓或者苹果都是可以的
