### ISSUE TITLE
[Request] 增加英文版，还有聊天记录支持搜索

### ISSUE THREAD

**Issue by ewfubwefwe** [LC044/WeChatMsg#300]
### 👌 是否检查过没有类似issue

就不检查

### 🥰 需求描述 | Feature Description

增加英文版，还有聊天记录支持搜索

### 🧐 解决方案 | Proposed Solution

增加英文版，还有聊天记录支持搜索

**Comment by LC044** [comment]
你就不检查那我就不支持
