### ISSUE TITLE
[Question] 作者你好，我想请教一下，谢谢了。

### ISSUE THREAD

**Issue by bibabo911** [LC044/WeChatMsg#302]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

我只想拿到64位公钥那一步，但是微信更新了后，就无法在version_list.json里读到新的偏移了，然后就不支持了，我想问下，这个偏移是怎么弄到的。

**Comment by LC044** [comment]
不在本项目的研究范围之内
