### ISSUE TITLE
[Request] 能不能将所有聊天记录导出到SQLITE3数据库文件

### ISSUE THREAD

**Issue by coloraven** [LC044/WeChatMsg#304]
### 👌 是否检查过没有类似issue

搜索过

### 🥰 需求描述 | Feature Description

如题，现在可以选择导出到csv文件，docx或者html，我选择的是html，但是导着导着就出错了，可能是我文件太多了（用了几年的旧手机的数据）硬盘扛不住，我的还是固态硬盘，如果是机械硬盘....

### 🧐 解决方案 | Proposed Solution

能不能将聊天记录数据保存到sqlite3数据库呢，查看聊天记录时，html的JavaScript再去查询sqlite3数据库？这样不至于文件过多，就一个数据库文件，移植保存都很方便。而且可以的话，可以使用duckdb来保存，以便查看聊天记录时查库更方便。

**Comment by LC044** [comment]
出错你应该把错误日志发过来，数据库已经解密完成了可自行解析
