### ISSUE TITLE
[Bug] 词云统计有无意义词汇

### ISSUE THREAD

**Issue by Fanisting** [LC044/WeChatMsg#305]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.11

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图: 
![image](https://github.com/LC044/WeChatMsg/assets/87118530/85ad0214-d8ff-4adf-9abe-3c12387378a6)

### 🚦 期望结果 | Expected Behavior

应该没有以下两种词汇：
1. http, https, .edu, .com
2. 表情包的文字（流泪，憨笑，发怒...）

**Comment by LC044** [comment]
工具里可以设置自定义停用词
