### ISSUE TITLE
[Question] 导出为html时崩溃

### ISSUE THREAD

**Issue by AutumnPizazz** [LC044/WeChatMsg#306]
### 👌 是否检查过没有类似issue

就不检查

### 🧐 问题描述 | Proposed Solution

运行两分钟后磁盘不再写入，程序无响应，下面附上报错。

### 📝 补充信息 | Additional Information

2024-01-13 11:49:35,415 - main.py[line:16] - ERROR: 程序发生了错误:

Exception Type: FileNotFoundError
Exception Value: [Errno 2] No such file or directory: 'C:\\Users\\27162\\Downloads/data/聊天记录/原654\\651数学群/原654\\651数学群.html'
details: Traceback (most recent call last):
  File "app\DataBase\output.py", line 105, in run
  File "app\DataBase\exporter_html.py", line 288, in export
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\27162\\Downloads/data/聊天记录/原654\\651数学群/原654\\651数学群.html'

**Comment by AutumnPizazz** [comment]
<img width="953" alt="image" src="https://github.com/LC044/WeChatMsg/assets/114050365/ad33f1c6-cbb1-42a4-8c2b-8b45b71b66d9">

**Comment by AutumnPizazz** [comment]
重试了一下，仍然崩溃。
![image](https://github.com/LC044/WeChatMsg/assets/114050365/08908095-231c-45d4-93e7-4d730f611683)

**Comment by LC044** [comment]
已发现问题，可等下个版本解决

**Comment by LC044** [comment]
新版本已解决
