### ISSUE TITLE
[Bug] VX最新版本已经是3.9.9.25 需要更新

### ISSUE THREAD

**Issue by PreGrafer** [LC044/WeChatMsg#308]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

Other(更新到最新版再试试)

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:

**Comment by ricksun2023** [comment]
version_list.json文件中没有增加3.9.9.25，这个版本的微信用不了
