### ISSUE TITLE
[Bug] 导出HTML后，显示成功，但是打开html后一直卡住，按钮没有反应

### ISSUE THREAD

**Issue by Zzzchh** [LC044/WeChatMsg#310]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

exe文件

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

1.0.3
### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/111729189/851fb0f5-4abb-410e-a6ea-c5b596ab17a9)

### 📷 复现步骤 | Recurrence Steps

不确定如何复现，我导出我和朋友的聊天记录大约有11G左右

### 📝 补充信息 | Additional Information

从手机迁移聊天记录到电脑后，图片和表情包也没有在软件中显示出来，但是导出的文件夹中可以找到。导出的HTML大小350M左右，无法翻页并且打开HTML的页面也不是我和我朋友的聊天记录。
报错信息如下：
![image](https://github.com/LC044/WeChatMsg/assets/111729189/ebf2a30f-bb1c-407f-9226-0572426a127d)

**Comment by LC044** [comment]
逐个排查导出的消息类型，看看是哪种消息类型出错的

**Comment by Zzzchh** [comment]
> 逐个排查导出的消息类型，看看是哪种消息类型出错的

排查后发现两个问题：
1. log文件报错是导出表情包导致的，html文件可以正常打开，但部分表情包无法浏览，显示无法加载的图片样式
2. 导出分享卡片会导致打开html文件时，无法点击按钮翻页，log文件无报错信息

**Comment by LC044** [comment]
只勾选分享卡片，用vscode打开HTML，看看底下的js部分哪有问题

**Comment by Zzzchh** [comment]
> 只勾选分享卡片，用vscode打开HTML，看看底下的js部分哪有问题

json字符串多了换行和空格。。删了就好了
![image](https://github.com/LC044/WeChatMsg/assets/111729189/eb882f8d-99b9-4f16-9539-07d57480c5bb)

**Comment by LC044** [comment]
把出错的那个发过来看看
