### ISSUE TITLE
[Bug] 不支持微信3.9.8.27版本

### ISSUE THREAD

**Issue by coldrainsnow** [LC044/WeChatMsg#315]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.12

### 💻 微信版本

Other(更新到最新版再试试)

### 软件版本 | EXE Version

源码

### 🐛 问题描述 | Bug Description

我的微信版本是3.9.8.27，但是我在获取信息时，提示需要更新3.9.9.27，但在微信官网最新的版本为3.9.8，并无3.9.9版本
报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/76909178/5371ece9-1af4-496e-9553-913fe1e5ee9a)

![image](https://github.com/LC044/WeChatMsg/assets/76909178/add310f3-281f-499e-a9d6-9fd822ff0416)

![image](https://github.com/LC044/WeChatMsg/assets/76909178/c39ec737-d197-42db-bb91-ee6337706ca9)

### 🚦 期望结果 | Expected Behavior

3.9.8.27可以正常运行

### 📷 复现步骤 | Recurrence Steps

需要注意，我没有装任何数据库，不知道是否有影响。
复现步骤，下载源码后，配置完各种python环境，执行python main.py命令。

**Comment by showlotus** [comment]
俺也一样 🥲 ～

**Comment by LC044** [comment]
下载官网那个安装一下

**Comment by showlotus** [comment]
下载官网最新的版本是 `3.9.8.25`，是不是不支持 `3.9.8.27` 呀？

**Comment by coldrainsnow** [comment]
> 下载官网那个安装一下

下载release的也没有用，我刚才发现是下午18点42分代码提交3.9.9.27时错误，应该把两个version_list.json中的3.9.9.27改为3.9.8.27即可修复这个bug

**Comment by LC044** [comment]
我这边没有3.9.8.27，我的微信直接从3.9.8.25升级到了3.9.9.27，不知道张小龙在搞什么飞机✈

**Comment by houkunlin** [comment]
别挣扎了，作者直接关掉了两个“不支持3.9.9.25”的issue，并且没有任何的解释，相信这个issue于不久后也会被关闭

![image](https://github.com/LC044/WeChatMsg/assets/12333292/9d3194d4-7487-4a5b-aa1d-94144e69f9a7)

**Comment by LC044** [comment]
> 别挣扎了，作者直接关掉了两个“不支持3.9.9.25”的issue，并且没有任何的解释，相信这个issue于不久后也会被关闭
> 
> ![image](https://private-user-images.githubusercontent.com/12333292/296899127-9d3194d4-7487-4a5b-aa1d-94144e69f9a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNjQ4NTEsIm5iZiI6MTcwNTM2NDU1MSwicGF0aCI6Ii8xMjMzMzI5Mi8yOTY4OTkxMjctOWQzMTk0ZDQtNzQ4Ny00YTViLWFhMWQtOTQxNDRlNjlmOWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAwMjIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDFkYjNiYjdlOTM5YmNjYmYyZWJjMDNmZmI0OWI5YjI1ODE0ZDI1NWVkNTJhNzNmZDU1YTdjZWE3ZDJjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jLsGsQVieGP44GXtFBKD0baUqi6lM7i07DFGK3rKnKg)

解释什么，自己选的不需要解答，眼瞎的话当我没说

**Comment by coldrainsnow** [comment]
> 我这边没有3.9.8.27，我的微信直接从3.9.8.25升级到了3.9.9.27，不知道张小龙在搞什么飞机✈

好的谢谢，那估计是微信分批更新版本的原因吧
