### ISSUE TITLE
[Bug] 不支持微信 3.9.9.25 版本

### ISSUE THREAD

**Issue by houkunlin** [LC044/WeChatMsg#317]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

Other(更新到最新版再试试)

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:

### 🚦 期望结果 | Expected Behavior

![image](https://github.com/LC044/WeChatMsg/assets/12333292/739f4968-7d8e-4ce0-a1d4-eeea35df5b21)

**Comment by LC044** [comment]
自己去看别人咋解决的 #315
