### ISSUE TITLE
聊天记录数据库读取缺失，报错MSG表不存在[Bug] 

### ISSUE THREAD

**Issue by superyuxiao** [LC044/WeChatMsg#321]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.11

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

我确定和女朋友每天都有聊天，微信检查聊天记录也确实存在，因此确定导入的数据库缺少1月1日、1月2日和9月大部分的聊天。
![Snipaste_2024-01-16_11-13-16](https://github.com/LC044/WeChatMsg/assets/41314611/e78530a5-1bcc-4f98-b9d5-59479ba721f4)

参考类似情况的issues，我在app/DataBase/merge.py里的74行加一句话
logger.error(traceback.format_exc())
报错如下

报错截图:
![Snipaste_2024-01-16_11-23-47](https://github.com/LC044/WeChatMsg/assets/41314611/1880067e-7023-4c7b-a009-efb445534346)

**app/DataBase/Msg数据库情况如下**

![Snipaste_2024-01-16_11-29-28](https://github.com/LC044/WeChatMsg/assets/41314611/ef3afbb6-4de8-4726-a607-3767cdb21090)
![Snipaste_2024-01-16_11-29-39](https://github.com/LC044/WeChatMsg/assets/41314611/06f2403c-6942-431b-92a9-9e6d57bf78ad)

**微信保存路径下，Msg/Multi/文件夹下数据库情况如下**

![Snipaste_2024-01-16_11-32-09](https://github.com/LC044/WeChatMsg/assets/41314611/ad5c2b50-2610-471f-a6e5-05f09dbce383)

### 🚦 期望结果 | Expected Behavior

全年的每一天聊天记录全部读取

### 📷 复现步骤 | Recurrence Steps

app/DataBase/merge.py里的74行加代码
logger.error(traceback.format_exc())

启动后，在工具-获取信息 之后，开始启动，即会报错

**Comment by LC044** [comment]
你打开MSG1.db，看看里面的表结构是怎样的

**Comment by superyuxiao** [comment]
WeChatMsg\app\DataBase\Msg\MSG1.db
![Snipaste_2024-01-16_14-15-55](https://github.com/LC044/WeChatMsg/assets/41314611/edd750d6-3129-4587-8969-00ef3bba0f5c)

**Comment by LC044** [comment]
这个有MSG表啊，他为啥会报错no such table MSG

**Comment by LC044** [comment]
你再运行一下，记录一下报错的是哪个数据库文件

**Comment by superyuxiao** [comment]
是这个app/DataBase/Msg/MSG2.db，是空的
 
![Snipaste_2024-01-16_14-39-49](https://github.com/LC044/WeChatMsg/assets/41314611/31fc3740-3246-4a4e-aa7d-69db086e5191)

**Comment by LC044** [comment]
你检查一下电脑微信是否有那天的消息，再重启一下微信，重新解密看看

**Comment by superyuxiao** [comment]
电脑微信上有那天的微信，重新微信，重新解密后，情况一样，没有变化

**Comment by dollarser** [comment]
遇到了同样的问题，请问你解决了么
