### ISSUE TITLE
[Bug] python版本不能使用高于3.12的，最高只能到3.11X，因为pilk==0.2.4这个最高支持到3.11，踩了好多坑，3.9，3.10，3.11，3.12都试过，最终在3.11下跑起来了

### ISSUE THREAD

**Issue by AmadaDeusa** [LC044/WeChatMsg#324]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

3.11

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/59082586/081f7503-da0d-432b-adc7-77c38dc517ff)

**Comment by LC044** [comment]
我一直用的是python3.12,但是3.10,3.11我都试了，都能运行

**Comment by AmadaDeusa** [comment]
奇怪，我用3.12一直装不上pilk这个模块，最后它的github好像只能支持到3.11，难道不装这个模块也不影响吗

**Comment by LC044** [comment]
我都能装上，可能是你其他环境有问题

**Comment by Swzer** [comment]
不会吧?我目前3.12.1版本都跑起来了
