### ISSUE TITLE
[Question] Exception Type: TypeError Exception Value: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by luyundie** [LC044/WeChatMsg#326]
### 👌 是否检查过没有类似issue

就不检查

### 🧐 问题描述 | Proposed Solution

<img width="433" alt="111" src="https://github.com/LC044/WeChatMsg/assets/90026002/b07d0835-24b8-4c7a-9354-bafc4582d530">

### 📝 补充信息 | Additional Information

通过releases下载的，出了这个问题不知道怎么解决

**Comment by LC044** [comment]
你就不检查那我也没办法

**Comment by hunderlinehh** [comment]
我也遇到了一模一样的问题。之后打开就会一直未响应或者闪退。

**Comment by HengY1Cola** [comment]
CN:我windows遇到了这个问题，已经解决。我是clone下来后运行的，解决办法就是项目路径中不要含有英文即可。
EN:I had this problem by using windows and it has been fixed. I am running after gitting clone and the solution is to do not contain English in the project path.
