### ISSUE TITLE
[Question] hello ,我这里下载了这个exe文件，可是打开有问题，显示找不到指定程序

### ISSUE THREAD

**Issue by roswang** [LC044/WeChatMsg#327]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

![image](https://github.com/LC044/WeChatMsg/assets/120555371/03a208a8-9ae7-4341-b402-f0b0a27f5b42)
Failed to execute script 'main' due to unhandled exception:DLL load failed while importing QtGui:找不到指定的程序。

Traceback is disabled via bootloader option.

**Comment by LC044** [comment]
截图多截点吧

**Comment by roswang** [comment]
hello，我解决了这个问题，需要把这个文件使用管理员权限
希望可以提醒后来人哈哈哈哈哈

**Comment by LC044** [comment]
OK

**Comment by roswang** [comment]
这个截图就是报错的全部内容啦，没有多余的啦
