### ISSUE TITLE
[Bug] 聊天记录导出HTML后头像丢失

### ISSUE THREAD

**Issue by jiashuaizhang** [LC044/WeChatMsg#328]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

Other(更新到最新版再试试)

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/33648447/22d84cde-027f-40aa-a418-94d1344b57fd)

### 🚦 期望结果 | Expected Behavior

大佬，聊天记录导出HTML的时候，为什么头像不使用真实头像，而是使用[https://wx.qlogo.cn/mmhead/ver_1](https://wx.qlogo.cn/mmhead/ver_1/XXX)
现在这个网站好像挂了，我导出来直接不显示头像😂

### 📷 复现步骤 | Recurrence Steps

“好友”菜单选择聊天记录导出为HTML格式

**Comment by jiashuaizhang** [comment]
额，倒是可以解决，写了个替换命令给替换成自己的图片了。大概像这样:
```sh
sed -i.bak.0 's/https:\/\/wx.qlogo.cn\/mmhead\/ver_1\/KQ1IgD8iaAHbXk4W66WnKZ3Op40sOurIvwTMATNsWTrMO2UKt36ic1RqrUqF82KZFUE26NKO4OPQ9NPUUhsrQ4KGAA9mTFBYhRe0nE00scIMu2XE3Xy1lQT7Fz6axhW4Ow\/132/image\/my.jpg/g' 老婆.html
sed -i.bak.1 's/https:\/\/wx.qlogo.cn\/mmhead\/ver_1\/UIURRdZlQfibCKxKpKNRibibzYQm7JwnibOGL9hMvJMjNOdaI0Bdaoe3lHxYQAicae2uKiboibwiaJric94QeDmGJPXIXKfnaEtV1gBgvr1u5rz5dFkk\/132/image\/her.jpg/g' 老婆.html
```

**Comment by LC044** [comment]
已收到反馈，后期会修复该问题，存在部分头像url失效
