### ISSUE TITLE
Mac支持吗？

### ISSUE THREAD

**Issue by AndersonHJB** [LC044/WeChatMsg#33]
Mac支持吗？

**Comment by benthecoder** [comment]
i have the same question about mac support +1

**Comment by Nummer12** [comment]
应该可以吧，用的是python。
这里有说明：https://github.com/LC044/WeChatMsg/blob/master/doc/电脑端使用教程.md

**Comment by LC044** [comment]
Mac不支持哦，可以安装一个Windows虚拟机运行
