### ISSUE TITLE
[Request] 年度报告增加导出 html 功能

### ISSUE THREAD

**Issue by panwanke** [LC044/WeChatMsg#331]
### 👌 是否检查过没有类似issue

就不检查

### 🥰 需求描述 | Feature Description

现在的年度报告是挂在1314端口的动态程序，能否增加导出静态html的功能。
- 去掉复杂的动效和实时计算。
- 增加自定义主题或布局方式

### 🧐 解决方案 | Proposed Solution

至少让网页是一个连续的html，不用翻页，这样也可以用 singlefile等插件实现导出为单独的html。

**Comment by FangPengbo** [comment]
为什么我的年度报告打开一堆字堆在一个页面上

**Comment by vegetablelong** [comment]
> 为什么我的年度报告打开一堆字堆在一个页面上

在浏览器F12，调成手机模式，然后刷新，再调回去就好了

**Comment by LC044** [comment]
> > 为什么我的年度报告打开一堆字堆在一个页面上
> 
> 在浏览器F12，调成手机模式，然后刷新，再调回去就好了

可能是网络问题，多刷新几次就行了，下个版本我会把js文件放我服务器上，应该就不会出现这个问题了

**Comment by FangPengbo** [comment]
> > > 为什么我的年度报告打开一堆字堆在一个页面上
> > 
> > 
> > 在浏览器F12，调成手机模式，然后刷新，再调回去就好了
> 
> 可能是网络问题，多刷新几次就行了，下个版本我会把js文件放我服务器上，应该就不会出现这个问题了

科学上网就好了，怀疑是用了引入了某些css库国内访问不到。

**Comment by FangPengbo** [comment]
> > > 为什么我的年度报告打开一堆字堆在一个页面上
> > 
> > 
> > 在浏览器F12，调成手机模式，然后刷新，再调回去就好了
> 
> 可能是网络问题，多刷新几次就行了，下个版本我会把js文件放我服务器上，应该就不会出现这个问题了

嗯嗯。我科学上网之后就好了。应该就是某些资源没加载到。
