### ISSUE TITLE
[Question] 从手机同步过来的消息不显示

### ISSUE THREAD

**Issue by branden28** [LC044/WeChatMsg#335]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

手机端聊天记录可以看到22年， 同步过来之后聊天报告显示首次聊天是23年12-20，之前的记录也没使用

**Comment by LC044** [comment]
可以查看https://memotrace.cn/doc/教程解决

**Comment by branden28** [comment]
404了

**Comment by branden28** [comment]
> 可以查看https://memotrace.cn/doc/教程解决

404了
