### ISSUE TITLE
[Bug] 导出HTML时出现Unhandled Exception，然后软件卡死

### ISSUE THREAD

**Issue by perfectdo** [LC044/WeChatMsg#336]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

None

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/63947613/238422cb-6e17-4b9f-bbda-d17649cde74f)

### 🚦 期望结果 | Expected Behavior

修复

### 📷 复现步骤 | Recurrence Steps

参考截图

**Comment by LC044** [comment]
把log日志发过来
