### ISSUE TITLE
我的手机端微信无法登录，这个软件可以非登录状态下读取到聊天记录不？

### ISSUE THREAD

**Issue by bitxx** [LC044/WeChatMsg#338]
### 👌 是否检查过没有类似issue

就不检查

### 🧐 问题描述 | Proposed Solution

我手机号很多年前的，没法用了。里面有些聊天记录想要导出。
手机上的聊天记录文件都还在，我拷贝到windows电脑上，能用这个软件读出来聊天信息不？

**Comment by LC044** [comment]
不能
