### ISSUE TITLE
[Question] 这个repo有上榜github trending吗？

### ISSUE THREAD

**Issue by zpointS** [LC044/WeChatMsg#341]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

我觉得这个做的很amazing也在很多角度上很meaningful，但我突然好奇这个项目有没有上过github的trending？这个项目的star数量在12月开始增长了这么多，感觉上榜应该是很合理的，而且也可以充当一个引流的渠道。感觉trending算法有点奇妙的说实话。

**Comment by LC044** [comment]
可以去官网看看
