### ISSUE TITLE
[Bug] csv导出引用错误

### ISSUE THREAD

**Issue by jacktaolai** [LC044/WeChatMsg#344]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

3.11

### 💻 微信版本

3.9.8.15

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

csv导出的聊天消息，卡片的StrContent是空的,(目前只看到这两个），但是html显示是正常的

### 🚦 期望结果 | Expected Behavior

其它类型消息还不要紧，希望能把引用的消息显示出来，像txt那样表示也行，其它表示方式也行

**Comment by BernieHuang2008** [comment]
我也发现了这个问题，因为引用的内容和消息本身好像都没有存在StrContent里面

**Comment by LC044** [comment]
Excel和TXT格式都支持引用消息了
