### ISSUE TITLE
[Bug] 程序无法正常启动

### ISSUE THREAD

**Issue by blacktion** [LC044/WeChatMsg#353]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

Other(更新到最新版再试试)

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:显示数据库不存在，请先解密数据库
![image](https://github.com/LC044/WeChatMsg/assets/47000256/f13b146e-c113-45dc-8cc4-952bb865c60d)

### 🚦 期望结果 | Expected Behavior

希望能正常打开

### 📷 复现步骤 | Recurrence Steps

下载后双击运行程序exe文件

**Comment by zhousc11** [comment]
这个应该是首次打开都会弹出两次这个对话框的吧，直接点确定后就可以正常使用了

**Comment by lanbinshijie** [comment]
数据库未解密的提示只会在首次打开时或者检测到目录下没有解密后的数据才会弹出，关闭对话框后点击解密数据即可。
