### ISSUE TITLE
图片点开都还是小图

### ISSUE THREAD

**Issue by Cara-W** [LC044/WeChatMsg#354]
### Discussed in https://github.com/LC044/WeChatMsg/discussions/352

<div type='discussions-op-text'>

<sup>Originally posted by **Cara-W** February  2, 2024</sup>
请问为何图片都是小图？
无论是在EXE里，或是导出的html里，点击聊天里发的图片打开的都是小图。

没有人发现这个问题吗？我查了issue，里面没人提到这个。</div>

**Comment by Cara-W** [comment]
使用 WeChat 3.9.9.35 和 MemoTrace-1.0.7

**Comment by gyco** [comment]
> 使用 WeChat 3.9.9.35 和 MemoTrace-1.0.7

我就是这个微信版本+MemoTrace版本 但仍然是小图（缩略图）  一万张照片才几十兆
![Uploading image.png…]()

**Comment by Cara-W** [comment]
视频都直接显示大的，就是图片有问题。可能是点击指向的图片错误（没有正确的把原图导出），希望这个可以快点解决啊。

**Comment by LC044** [comment]
已修复

**Comment by Cara-W** [comment]
谢谢！请问是有新版本吗？

**Comment by LC044** [comment]
> 谢谢！请问是有新版本吗？

马上发布新版本，稍等一下

**Comment by Cara-W** [comment]
太感谢了！

**Comment by gyco** [comment]
> > 谢谢！请问是有新版本吗？
> 
> 马上发布新版本，稍等一下

刚测试的  发现导出图片仍然是缩略图。。。

**Comment by Cara-W** [comment]
1.0.8吗？我测试了，很多导出的都直接和视频一样是大图了，无需点击。但是有一些还是缩略图，我正在查找看看那些只会显示缩略图片在微信里有什么不同。

**Comment by LC044** [comment]
> 1.0.8吗？我测试了，很多导出的都直接和视频一样是大图了，无需点击。但是有一些还是缩略图，我正在查找看看那些只会显示缩略图片在微信里有什么不同。

那些是微信没有加载原图

**Comment by Cara-W** [comment]
喔，是说我在微信里没点开加载过原图，所以才会显示缩略图了？我去重新迁移，解密，导出看看。

你的问题解决了吗？

**Comment by Cara-W** [comment]
> > 1.0.8吗？我测试了，很多导出的都直接和视频一样是大图了，无需点击。但是有一些还是缩略图，我正在查找看看那些只会显示缩略图片在微信里有什么不同。
> 
> 那些是微信没有加载原图

果然如此！^_^
