### ISSUE TITLE
增加到处PDF选项[Request] 

### ISSUE THREAD

**Issue by jianhuangzheng** [LC044/WeChatMsg#356]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

发现身边人还挺多有导出PDF的需求，更方便阅读，希望作者能跟进下这个功能哈

### 🧐 解决方案 | Proposed Solution

期待跟进

**Comment by LC044** [comment]
可以自行word转pdf

**Comment by Xuan-Xuann** [comment]
如果是网页的话直接就Ctrl+P进行打印不进好了

**Comment by Harry2010410** [comment]
现在爆料流行pdf，哈哈哈

**Comment by LC044** [comment]
最新版已支持导出PDF，可下载使用
