### ISSUE TITLE
年度报告打开只有index.html

### ISSUE THREAD

**Issue by HeadmasterEggy** [LC044/WeChatMsg#357]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

年度报告打开只有`index.html`, 但是访问'http://127.0.0.1:21314/christmas'就可以打开。这是bug吗还是什么原因。
![image](https://github.com/LC044/WeChatMsg/assets/93173363/406863c1-1d18-4a08-83fd-a174cddc825d)
![image](https://github.com/LC044/WeChatMsg/assets/93173363/2f46c86f-f82c-421c-8f46-355c06913f79)

而且微信昵称获取是none，其他正常
![image](https://github.com/LC044/WeChatMsg/assets/93173363/6a086fe4-f2d3-4a56-aae2-198c06cef82e)
![image](https://github.com/LC044/WeChatMsg/assets/93173363/50b6ef5a-975a-4192-96a8-f98e2fed9904)

**Comment by LC044** [comment]
不是bug，本来就是访问的Christmas，你的自动打开失败了
