### ISSUE TITLE
[Bug] 导出的聊天记录数据中  <回复>消息无法正常显示 只能看到type和subtype

### ISSUE THREAD

**Issue by whxxxxxxxxxx** [LC044/WeChatMsg#362]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.1

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

报错截图：
![微信图片_20240205132814](https://github.com/LC044/WeChatMsg/assets/114289969/1730108f-0f5f-4109-89f3-74ff675c7edf)
![微信图片_20240205132827](https://github.com/LC044/WeChatMsg/assets/114289969/8ba85f85-c422-4401-9a08-3654e8b932b9)

### 🚦 期望结果 | Expected Behavior

能够在导出的消息记录中，正常显示<回复>的消息内容

### 📷 复现步骤 | Recurrence Steps

导出消息记录为csv

**Comment by Panaoxuan** [comment]
这个用安卓模拟器的方法好像可以，b站有个up视频里讲了,id：是三木同学

**Comment by LC044** [comment]
这个是纯文本格式的csv，引用消息不在那一列，可以参考代码自行解析
