### ISSUE TITLE
无法获取到中文昵称[Bug] 

### ISSUE THREAD

**Issue by HUSX100** [LC044/WeChatMsg#364]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

3.9.8.15

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/80823417/5256c183-58f3-42cb-ae13-c39924efd54d)
不知道为什么获取到的昵称是None

### 📷 复现步骤 | Recurrence Steps

使用解密二的方式手动填写中文昵称，获取完以后昵称为None，如果自动获取就会乱码
![image](https://github.com/LC044/WeChatMsg/assets/80823417/651de44b-f331-457b-9823-55d3afb2d79c)

**Comment by LC044** [comment]
多试几次呢，我这边中午昵称没有问题，其他人也都没有反馈这个问题

**Comment by zxjathome** [comment]
> 多试几次呢，我这边中午昵称没有问题，其他人也都没有反馈这个问题

同存在此问题，不知道是不是昵称太长，【冒热气的小汤圆】，七个字

**Comment by HUSX100** [comment]
> > 多试几次呢，我这边中午昵称没有问题，其他人也都没有反馈这个问题
> 
> 同存在此问题，不知道是不是昵称太长，【冒热气的小汤圆】，七个字

我的昵称 8 个字

**Comment by LC044** [comment]
> > > 多试几次呢，我这边中午昵称没有问题，其他人也都没有反馈这个问题
> > 
> > 
> > 同存在此问题，不知道是不是昵称太长，【冒热气的小汤圆】，七个字
> 
> 我的昵称 8 个字

改成英文昵称试试

**Comment by exgmzbzzh** [comment]
> > > > 多试几次呢，我这边中午昵称没有问题，其他人也都没有反馈这个问题
> > > 
> > > 
> > > 同存在此问题，不知道是不是昵称太长，【冒热气的小汤圆】，七个字
> > 
> > 
> > 我的昵称 8 个字
> 
> 改成英文昵称试试

我中文改成英文依旧乱码

**Comment by LC044** [comment]
经过测试7个字以上的中文昵称会乱码，最新版已经支持修改昵称了，可以下载最新版使用
