### ISSUE TITLE
[Bug] 导出的html中微信自带表情包图片因反盗链

### ISSUE THREAD

**Issue by zxjathome** [LC044/WeChatMsg#366]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

Other(更新到最新版再试试)

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:

【本地打开HTML文件】
![1](https://github.com/LC044/WeChatMsg/assets/30248127/7c96f6cd-27cb-431d-a450-e99a8e5942c8)

【上传到服务器后通过自有域名打开】
![2](https://github.com/LC044/WeChatMsg/assets/30248127/fb5cafdc-587b-45a1-891d-eacad5281e06)

### 🚦 期望结果 | Expected Behavior

希望可以直接保存图片文件到本地，以免后续出现图片链接过期的问题

### 📷 复现步骤 | Recurrence Steps

本地打开html文件后显示是正常的，放到自己服务器上后就会显示【此图片来自微信公众平台，未经允许不得引用】

**Comment by zxjathome** [comment]
尝试自己搜索教程，在html开头加入了一行后可以正常显示
`<meta name="referrer" content="no-referrer"/>`

**Comment by LC044** [comment]
多谢，以后会考虑本地保存的

> 尝试自己搜索教程，在html开头加入了一行后可以正常显示 `<meta name="referrer" content="no-referrer"/>`

**Comment by Chenm4** [comment]
> 多谢，以后会考虑本地保存的
> 
> > 尝试自己搜索教程，在html开头加入了一行后可以正常显示 `<meta name="referrer" content="no-referrer"/>`

请问现在还没有实现本地保存表情包的原因是什么？总感觉不本地不靠谱哈，生怕哪天腾讯严格反盗链就看不了了。我现在放在服务器上有一部分就看不了，有些域名前缀的能看得到，但是有些就看不到了。
