### ISSUE TITLE
[Bug] 某段时间内聊天记录无法读取

### ISSUE THREAD

**Issue by amusedJimmy233** [LC044/WeChatMsg#368]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![8369e148c31be2044731eab1fc9a2828](https://github.com/LC044/WeChatMsg/assets/99393272/1ba73fec-4acb-447f-8072-42cabb2208b3)
这是导出的csv，中间的聊天记录莫名其妙的缺失
![截屏2024-02-11 22 32 22](https://github.com/LC044/WeChatMsg/assets/99393272/9539940d-5961-4776-bb43-2ade5772f7b1)

### 🚦 期望结果 | Expected Behavior

通过微信电脑端查询可以看到这段日期在微信电脑端是可以看到的
![99bb5912a8a48fa7c60e83b5c0eb3c0e](https://github.com/LC044/WeChatMsg/assets/99393272/4fee97db-ff78-4ab4-90fa-4f5a751ed073)

### 📝 补充信息 | Additional Information

在文件的目录下log文件没有报错

**Comment by amusedJimmy233** [comment]
补充一下：
![82757da96f247ea502dcc0d01854dd92](https://github.com/LC044/WeChatMsg/assets/99393272/cdc54886-e51f-440d-96d8-0982b9aa0882)
这是我从8月29号-12月19号生成的年度报告截图，进一步验证了程序似乎没有读到这段时间聊天记录，并且消息数量和总字数似乎有些bug（统计了这段时间的消息数量和一年的总字数）

**Comment by swordBRSPA** [comment]
我也遇到了这个问题，选取缺失时间段导出后，确实为空白，微信客户端是有聊天记录的

**Comment by LC044** [comment]
重新解析数据，多试几次就行了
