### ISSUE TITLE
[Request] “分析好友过往所有聊天记录”功能（即年报功能扩展至所有聊天记录）

### ISSUE THREAD

**Issue by Liunian2000** [LC044/WeChatMsg#369]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

希望能添加一个分析过往所有聊天记录的功能，数据输入从前一年改为所有时间

### 🧐 解决方案 | Proposed Solution

在已有的年度报告功能上添加一个选择分析时间（起始日期-终止日期），软件只对该分析日期内的聊天记录做统计

**Comment by CSLby7** [comment]
虽然有这个功能，但是我感觉词云还是只基于过去一年，没有包括今年（1-2月）的数据
