### ISSUE TITLE
[Bug] 无法打开情感分析

### ISSUE THREAD

**Issue by Ziwen426** [LC044/WeChatMsg#370]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.12

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/145950863/f843d58d-60e4-440a-8524-a1e7daf8df8f)
![image](https://github.com/LC044/WeChatMsg/assets/145950863/fcf57fc2-93a8-4869-a684-6ca43d4340f5)
1. 年度报告可以打开，但是在页面中[点击生成我的年度聊天报告](https://memotrace.lc044.love/)会跳转下载页面
![image](https://github.com/LC044/WeChatMsg/assets/145950863/44539068-495c-40a2-b0a4-67d6fc44bd6b)
2. 情感分析无法打开，直接跳转下载页面，跳转页同上
3. 以上问题都已经下载软件，但如果要打开情感分析依然会跳转下载软件可见

### 🚦 期望结果 | Expected Behavior

修复情感分析页面

**Comment by LC044** [comment]
该部分还没有实现，可以关注公众号等待功能更新
