### ISSUE TITLE
[Request] 可否实现一个网页版前端

### ISSUE THREAD

**Issue by raysworld** [LC044/WeChatMsg#371]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

解密数据库后，目前是通过pyqt界面实现对聊天记录的可视化，可否实现一个基于web的网页前端，这样方便将解密数据库部署到个人服务器上，方便随时查询

### 🧐 解决方案 | Proposed Solution

请参见需求描述

### 📝 补充信息 | Additional Information

感谢任何相关讨论😊

**Comment by LC044** [comment]
不能

**Comment by LC044** [comment]
需要重写架构，感兴趣的可以自己单独开发一个
