### ISSUE TITLE
[Bug] 群聊信息导出csv自己的名字为空

### ISSUE THREAD

**Issue by LSDog** [LC044/WeChatMsg#372]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

导出后csv文件中所有**自己**的聊天记录中 `Remark` 和 `NickName` 是空的
![image](https://github.com/LC044/WeChatMsg/assets/61925478/2b1b927b-8908-475f-b6dc-1bb2833838e3)

### 🚦 期望结果 | Expected Behavior

加入自己的Remark和Nickname

### 📷 复现步骤 | Recurrence Steps

好友 -> 选择群聊 -> 导出csv

**Comment by LC044** [comment]
自己的昵称自己知道啊

**Comment by LSDog** [comment]
> 自己的昵称自己知道啊

是这样的，我在做聊天频率的统计，但是发现没有自己的名字而百思不得其解，如果导出时能顺便把自己的昵称加上去的话就更好了...方便使用，我是这么想的

**Comment by LC044** [comment]
已修复

**Comment by LSDog** [comment]
感谢！
