### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by isaylife** [LC044/WeChatMsg#373]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.11

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
导出为html之后，里面的图片不显示，
图片地址是这样http://emoji.qpic.cn/wx_emoji/5SibvMM0Fu25TKGOVgNVW5eG558ULUX3DLYiceZ53icwzrxtibHOp14SUsJpV3dp474N/
![Snipaste_2024-02-15_18-22-40](https://github.com/LC044/WeChatMsg/assets/135199468/a917fac4-6e9d-4d9b-b865-ee8b9e0dbfc9)

**Comment by LC044** [comment]
这种是加密表情包，不让访问
