### ISSUE TITLE
[Question] 对于特定好友的自定义时间年度报告中词云没有包含2024年的数据

### ISSUE THREAD

**Issue by CSLby7** [LC044/WeChatMsg#374]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

对于特定好友的自定义时间年度报告，我选择的时间范围是(2023.12-2024.02)，但根据我的观察，报告中词云没有包含2024年（1-2月）的数据。请问大家有类似的情况吗？谢谢

**Comment by LC044** [comment]
已发现问题，可以等下个版本修复
