### ISSUE TITLE
缩小导出的HTML聊天记录PC端页面底部页码占用区域

### ISSUE THREAD

**Issue by CrossWow** [LC044/WeChatMsg#375]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

None

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

报错截图:
![Snipaste_2024-02-20_13-57-13](https://github.com/LC044/WeChatMsg/assets/158282208/46a424f7-85c2-4405-b298-d2ce271c818c)

### 🚦 期望结果 | Expected Behavior

1、导出的HTML聊天记录PC端页面底部页码占用区域过大，挤占了聊天记录显示区域，图片/视频都不能完整显示出来；2、页码原先位于左侧，多次建议恢复，如确定放于底部，原左侧区域建议取消；

**Comment by LC044** [comment]
已修复
