### ISSUE TITLE
[Question] 年度报告选择时间乱码，刚刚开始解码页面进度条也是，几个月前用的时候好像还没这个问题

### ISSUE THREAD

**Issue by LCYLYM** [LC044/WeChatMsg#376]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/46252748/979c3dd7-4b29-4639-bccb-18b9e2e3b4ed)
年度报告选择时间乱码，
![image](https://github.com/LC044/WeChatMsg/assets/46252748/e0440c84-d58f-4f37-b272-779c1d6c0e7b)

**Comment by LC044** [comment]
这是由于系统语言导致的，可能是开启了代理，或者地区设置成了香港等非大陆地区，可以检查一下相关系统设置
