### ISSUE TITLE
[Bug] 聊天记录中没有转发的聊天内容

### ISSUE THREAD

**Issue by liuyinzhe** [LC044/WeChatMsg#381]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

3.11

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

聊天记录中没有转发的聊天内容；希望尝试添加这部分的解析

**Comment by liuyinzhe** [comment]
done

**Comment by CrossWow** [comment]
+1

**Comment by GluttonousCat** [comment]
+1

**Comment by LC044** [comment]
已支持
