### ISSUE TITLE
[Request] 导出的html聊天界面好小，能不能加高加宽

### ISSUE THREAD

**Issue by sssomeoneee** [LC044/WeChatMsg#386]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

导出的html聊天界面好小，能不能加高加宽呢，网页打开四周还有很多空白，整个界面放大一点看聊天记录会舒服很多。而且HTML左边本就没有联系人，能不能直接把左侧空白去掉，直接居中一个细长条放聊天记录会不会好看点。还有翻页按钮能不能缩小一点放在靠底下位置，现在的就很突兀。叠个甲，该项目牛逼炸天，希望越来越好！

### 🧐 解决方案 | Proposed Solution

导出的html聊天界面好小，能不能加高加宽呢，网页打开四周还有很多空白，整个界面放大一点看聊天记录会舒服很多。而且HTML左边本就没有联系人，能不能直接把左侧空白去掉，直接居中一个细长条放聊天记录会不会好看点。还有翻页按钮能不能缩小一点放在靠底下位置，现在的就很突兀。叠个甲，该项目牛逼炸天，希望越来越好！

**Comment by CrossWow** [comment]
+1

**Comment by licasea** [comment]
+1

**Comment by LC044** [comment]
已修复
