### ISSUE TITLE
[Request]  非同一账号的聊天记录提取与恢复（情侣向）

### ISSUE THREAD

**Issue by NoIgnore** [LC044/WeChatMsg#389]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

A和B的聊天，A手误右往左滑，误删了手机中和B的聊天框导致A方手机无记录，能不能从B的手机里提取记录，导入A的手机中恢复两人的聊天记录。

### 🧐 解决方案 | Proposed Solution

不懂

### 📝 补充信息 | Additional Information

“我希望每个人都有将自己的生活痕迹”，然而好几年的生活痕迹，异地多年的点点滴滴记录毁于一旦，着实心痛，希望大佬们看看。

**Comment by dqgo** [comment]
我也想要这个功能🥹

**Comment by KiritoXF** [comment]
看到你在论坛发的贴子了
我觉得这个功能理论上可能没法实现
不过既然你对象的聊天记录还在，让其使用本项目备份到电脑上如何？因为可以导出成HTML等格式，导出后就可以发给你了，你就也能在电脑上查看了。

**Comment by xaoyaoo** [comment]
理论上可以实现，但是因为涉及到修改聊天记录，所以法律风险很大

**Comment by LC044** [comment]
修改之后恢复到微信里肯定是不允许的，也不会做这个功能，到是可以导出来之后修改发送方保存起来
