### ISSUE TITLE
[Question] 这个项目能处理手机端的聊天数据么（非迁移）？已ROOT设备

### ISSUE THREAD

**Issue by Thunderltx** [LC044/WeChatMsg#391]
### 👌 是否检查过没有类似issue

否

### 🧐 问题描述 | Proposed Solution

这个项目能处理手机端的聊天数据么（非迁移）？
手机已经root
相关文件路径是什么

**Comment by Thunderltx** [comment]
翻了翻，找到了相关问题，请问只有0.1.0和0.2.0支持手机端的解密么

**Comment by LC044** [comment]
> 翻了翻，找到了相关问题，请问只有0.1.0和0.2.0支持手机端的解密么

对
