### ISSUE TITLE
[Question] 请问支持已删除的好友导出吗？

### ISSUE THREAD

**Issue by frank5** [LC044/WeChatMsg#394]
### 👌 是否检查过没有类似issue

就不检查

### 🧐 问题描述 | Proposed Solution

请问支持已删除的好友导出吗？无需导聊天记录，只需找到已删除好友的ID就行

**Comment by EthanLiu6** [comment]
我也是删除好友想找回聊天记录w(ﾟДﾟ)w

**Comment by hallejuyahaha** [comment]
微信做的是写0删除，想恢复是不可能的。

**Comment by xiangshang-kok** [comment]
兄弟，忘了她吧

**Comment by LC044** [comment]
删了的东西都不支持

**Comment by lin752252801** [comment]
放过她也放过自己
