### ISSUE TITLE
[Question] 能具体讲讲这个train.json怎么使用吗

### ISSUE THREAD

**Issue by sanbei011** [LC044/WeChatMsg#396]
### 👌 是否检查过没有类似issue

就不检查

### 🧐 问题描述 | Proposed Solution

是在哪里训练呢?
我看作者发的链接中只有资料库

**Comment by LC044** [comment]
稍等哈，这几天就更新教程，今天比较忙

**Comment by sanbei011** [comment]
**好嘞好嘞,大佬万岁!!!!**

**Comment by LC044** [comment]
已添加
