### ISSUE TITLE
打开main.py后, 换个微信号备份, 选择完文件夹后, 再选择获取信息就出错[Question] 

### ISSUE THREAD

**Issue by latestminer** [LC044/WeChatMsg#398]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
ok 本次加载用了 2.2324345111846924 s
================================
[+]      pid: 8528
[+]  version: 3.9.9.43
[+]  account: None
[+]   mobile: 13923132
[+]     name: ྎg
[+]     mail: None
[+]     wxid: bill55
[+] filePath: C:\Users\b23v\Documents\WeChat Files\bi231
[+]      key: 10575e81f3219da1a88927aa422a054378a99278a54b58aa3f
================================
QPixmap::scaled: Pixmap is a null pixmap

C:\Users\b311v\WeChatMsg>python main.py
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
ok 本次加载用了 0.4755239486694336 s
[-] WeChat No Run
================================
[+]      pid: 1540
[+]  version: 3.9.9.43
[+]  account: lele123gbian
[+]   mobile: 1715312981
[+]     name: Dodrwo
[+]     mail: None
[+]     wxid: wxid_qrtl4kd5tlzm22
[+] filePath: C:\Users\23v\Documents\WeChat Files\wxid_qrtl4231
[+]      key: 0d0bccf242cd0c60fcc8d38cff8efc34105ba965a64f32c6a63
================================

**Comment by latestminer** [comment]
换回去之前那个微信号依然出错

**Comment by LC044** [comment]
哪有报错信息
