### ISSUE TITLE
批量导出功能只能导出近一年的记录[Bug] 

### ISSUE THREAD

**Issue by crane168** [LC044/WeChatMsg#399]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

首先感谢作者的辛勤付出，在使用时遇到一个问题，我是把手机上全量的聊天记录数据备份到电脑上，然后批量导出数据，查看html页面只有最近一年的数据，一年前的就看不到了，我在手机上确实是有这种数据的，不知道是不是我使用问题，但确实是没到导出全部记录

### 🚦 期望结果 | Expected Behavior

期望能够导出全部聊天记录

**Comment by LC044** [comment]
是批量导出的问题还是数据只有一年呢，可以试试导出手机微信数据超过一年单个好友
