### ISSUE TITLE
在使用main.py时报错

### ISSUE THREAD

**Issue by Svie1** [LC044/WeChatMsg#4]
提示错误:sqlite3.OperationalError: no such table: userinfo
我去app/Database文件夹下看了眼里面的Msg.db,发现这个是空的

**Comment by LC044** [comment]
按理说第一次运行main.py会弹出解密数据库的界面，按教程要求把两个文件导入进去即可自动解密数据库,此时会产生Msg.db，重新运行即可，你看看解密数据库是否成功
