### ISSUE TITLE
[Bug] Exception Type: AttributeError

### ISSUE THREAD

**Issue by Johnagrant** [LC044/WeChatMsg#401]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

None

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![Snipaste_2024-03-22_23-42-21](https://github.com/LC044/WeChatMsg/assets/125749873/5828edab-7ede-4e34-8608-21554d333dc1)

### 🚦 期望结果 | Expected Behavior

能正常导出聊天记录

### 📷 复现步骤 | Recurrence Steps

管理员权限打开软件，点“数据”-“批量导出”，导出格式选择“HTML”，类型就是类型的文本和图片，随便选择任何一个人，点“开始”后就马上报错了

**Comment by LC044** [comment]
软件包已更新，请重新下载使用
