### ISSUE TITLE
[Bug]导出的csv，有引用的消息都不会显示内容

### ISSUE THREAD

**Issue by WenG97** [LC044/WeChatMsg#403]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

None

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

只要引用了对方的消息进行恢复的，导出csv在StrContent段就没有内容

**Comment by LC044** [comment]
XLSX格式支持显示内容

**Comment by miantanhh** [comment]
> XLSX格式支持显示内容
导出xlsx时，长的聊天会报错

**Comment by LC044** [comment]
> > XLSX格式支持显示内容
> > 导出xlsx时，长的聊天会报错

报什么错

**Comment by CarlGao4** [comment]
导出全部聊天记录只支持csv，所以可不可以任何时候导出csv都自动将压缩的信息解压开单独存一列？
