### ISSUE TITLE
[Bug] AI训练完成，但推理报错

### ISSUE THREAD

**Issue by sanbei011** [LC044/WeChatMsg#406]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.1

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![0608e40ca0518cd059c72477b6f31505](https://github.com/LC044/WeChatMsg/assets/95988545/5e84bbc5-6016-427c-951d-c47ed783bc0d)

**怀疑是版本错误**

> https://github.com/THUDM/ChatGLM3/issues/1012#issue-2200177712

### 🚦 期望结果 | Expected Behavior

推理正常

### 📷 复现步骤 | Recurrence Steps

正常训练结束之后,进行推理,就会报错

**Comment by LC044** [comment]
请去https://github.com/THUDM/ChatGLM3/反馈
