### ISSUE TITLE
获取数据后，再次运行软件时能打开聊天记录页面，但立即弹出一个空白窗口，窗口栏上显示“未知错误”，重启，删除app和Data目录均无效[Bug] 

### ISSUE THREAD

**Issue by qiupihabo** [LC044/WeChatMsg#407]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![屏幕截图 2024-03-31 133533](https://github.com/LC044/WeChatMsg/assets/148854860/ef677063-d6c4-43bb-9f81-73fbdf966fbf)

### 📷 复现步骤 | Recurrence Steps

全正常操作，聊天记录可获取，在全英文目录下，删除app与Data再重启再运行均爆出“未知错误”弹窗

**Comment by LC044** [comment]
给出log文件内容

**Comment by qiupihabo** [comment]
抱歉，忘记给出日志了：
  2024-03-31 13:06:12,611 - main.py[line:20] - ERROR: 程序发生了错误:

Exception Type: OperationalError
Exception Value: no such table: OpenIMContact
details: version:2.0.3
Traceback (most recent call last):
  File "app\ui\contact\contact_window.py", line 186, in run
  File "app\DataBase\open_im_contact.py", line 38, in get_contacts
sqlite3.OperationalError: no such table: OpenIMContact

数据库错误，请删除app文件夹后重启电脑再运行软件

您可添加QQ群:548409157发送log文件以便解决该问题

**Comment by LC044** [comment]
你的微信没有企业好友联系人吗，不能用的话可以下载2.0.2版本

**Comment by qiupihabo** [comment]
2.0.2可以运行了，十分感谢
