### ISSUE TITLE
 database disk image is malformed

### ISSUE THREAD

**Issue by wlmnzf** [LC044/WeChatMsg#41]
**Describe the bug**
解密后提示重新启动，然后重新启动就起不来了

**To Reproduce**
1. Go to '根目录'
2. Click on '双击XXX.exe'
3. 管理员启动也不行

**Screenshots**
![Weixin Image_20231203224037](https://github.com/LC044/WeChatMsg/assets/6256515/7cf5e838-7aeb-4d97-9e15-4c533e05ef34)

**Comment by LC044** [comment]
微信版本是多少呢，重启微信试试呢，把生成的东西都删了

**Comment by LC044** [comment]
> @LC044 微信版本3.9.8.15。重启微信试过几次，同样的问题，生成的东西删掉过几次，也还是同样的问题

wxid显示正常吗，是不是登陆了多个微信号，wxid是不是wxid_开头的

**Comment by LC044** [comment]
> > > @LC044 微信版本3.9.8.15。重启微信试过几次，同样的问题，生成的东西删掉过几次，也还是同样的问题
> > 
> > 
> > wxid显示正常吗，是不是登陆了多个微信号，wxid是不是wxid_开头的
> 
> wxid,我从python脚本和exe文件执行两种途径，获取到的都是我的微信账号，并非“wxid_”开头

你用这个工具https://github.com/xaoyaoo/PyWxDump看看能不能解密数据库，如果可以的话麻烦告诉我，我查找一下原因

**Comment by wlmnzf** [comment]
> > > > > @LC044 微信版本3.9.8.15。重启微信试过几次，同样的问题，生成的东西删掉过几次，也还是同样的问题
> > > > 
> > > > 
> > > > wxid显示正常吗，是不是登陆了多个微信号，wxid是不是wxid_开头的
> > > 
> > > 
> > > wxid,我从python脚本和exe文件执行两种途径，获取到的都是我的微信账号，并非“wxid_”开头
> > 
> > 
> > 你用这个工具 https://github.com/xaoyaoo/PyWxDump 看看能不能解密数据库，如果可以的话麻烦告诉我，我查找一下原因
> 
> 试了一下PyWxDump ，提示Key Error!，对比了一下PyWxDump 算出来的key和[WeChatMsg]算出来的一致

看到 @Becky0909 d 消息，又检查了一下，确实数据库看着都解析成功了。然后PyWxDump 那边报key错误是因为微信目录识别错误，换成正确的以后，也就不报Key Error!了。 @LC044

**Comment by Becky0909** [comment]
> > > > > > @LC044 微信版本3.9.8.15。重启微信试过几次，同样的问题，生成的东西删掉过几次，也还是同样的问题
> > > > > 
> > > > > 
> > > > > wxid显示正常吗，是不是登陆了多个微信号，wxid是不是wxid_开头的
> > > > 
> > > > 
> > > > wxid,我从python脚本和exe文件执行两种途径，获取到的都是我的微信账号，并非“wxid_”开头
> > > 
> > > 
> > > 你用这个工具 https://github.com/xaoyaoo/PyWxDump 看看能不能解密数据库，如果可以的话麻烦告诉我，我查找一下原因
> > 
> > 
> > 试了一下PyWxDump ，提示Key Error!，对比了一下PyWxDump 算出来的key和[WeChatMsg]算出来的一致
> 
> 看到 @Becky0909 d 消息，又检查了一下，确实数据库看着都解析成功了。然后PyWxDump 那边报key错误是因为微信目录识别错误，换成正确的以后，也就不报Key Error!了。 @LC044

但是我好像还是没法再次打开软件，就跟你最初报的错一样，你这个问题解决了吗

**Comment by wlmnzf** [comment]
> > > > > > > @LC044 微信版本3.9.8.15。重启微信试过几次，同样的问题，生成的东西删掉过几次，也还是同样的问题
> > > > > > 
> > > > > > 
> > > > > > wxid显示正常吗，是不是登陆了多个微信号，wxid是不是wxid_开头的
> > > > > 
> > > > > 
> > > > > wxid,我从python脚本和exe文件执行两种途径，获取到的都是我的微信账号，并非“wxid_”开头
> > > > 
> > > > 
> > > > 你用这个工具 https://github.com/xaoyaoo/PyWxDump 看看能不能解密数据库，如果可以的话麻烦告诉我，我查找一下原因
> > > 
> > > 
> > > 试了一下PyWxDump ，提示Key Error!，对比了一下PyWxDump 算出来的key和[WeChatMsg]算出来的一致
> > 
> > 
> > 看到 @Becky0909 d 消息，又检查了一下，确实数据库看着都解析成功了。然后PyWxDump 那边报key错误是因为微信目录识别错误，换成正确的以后，也就不报Key Error!了。 @LC044
> 
> 但是我好像还是没法再次打开软件，就跟你最初报的错一样，你这个问题解决了吗

@Becky0909 是的，再次打开软件的时候，还是报错，哈哈。

**Comment by LC044** [comment]
试试最新代码，看看该问题能否解决

**Comment by wlmnzf** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/6256515/cdbf372d-5421-4603-8a96-2804832fca05)
试了，依然如此，这个问题感觉有点玄学。可能就得跟另一个onedrive同步的那个老哥说的那样，得删掉整个微信文件夹然后重新来一遍了，哈哈哈，有点折腾

**Comment by agtcxjy** [comment]
这个问题我刚刚也出现了，我尝试将 "WeChatMsg-master\app\DataBase\Msg" 路径内的文件全部移动走后，再重新运行程序，这时程序可以正常打开，进入"聊天"中提示数据库不存在，此时将移动走的文件重新放回 "...../Msg" 路径内，再点击 "聊天" 就可以正常加载。所以问题出现在程序的初始化阶段，但是数据库文件是没有损坏的，且解析数据库模块的代码正常

**Comment by agtcxjy** [comment]
> 这个问题我刚刚也出现了，我尝试将 "WeChatMsg-master\app\DataBase\Msg" 路径内的文件全部移动走后，再重新运行程序，这时程序可以正常打开，进入"聊天"中提示数据库不存在，此时将移动走的文件重新放回 "...../Msg" 路径内，再点击 "聊天" 就可以正常加载。所以问题出现在程序的初始化阶段，但是数据库文件是没有损坏的，且解析数据库模块的代码正常

@LC044
