### ISSUE TITLE
[Request] 语音提取

### ISSUE THREAD

**Issue by Clxj** [LC044/WeChatMsg#411]
### 👌 是否检查过没有类似issue

否

### 🥰 需求描述 | Feature Description

能不能让语音提取就是提取对面的语音不提取自己的.或者加个选择？

### 🧐 解决方案 | Proposed Solution

【

**Comment by LC044** [comment]
后面会实现该功能

**Comment by SuperJuice666** [comment]
支持，建议增加分用户提取语音，便于训练AI模型

**Comment by LC044** [comment]
2.0.11已实现
