### ISSUE TITLE
[Bug] 不支持微信内测版

### ISSUE THREAD

**Issue by zlj-tyf** [LC044/WeChatMsg#414]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/110816992/eec5b3a8-1126-488b-99a9-9ba36c5efd9f)
![image](https://github.com/LC044/WeChatMsg/assets/110816992/170103ca-ffd4-4137-8950-c8dd0f084245)

**Comment by LC044** [comment]
是支持该版本的，请查看教程解决相关问题，如有其他问题可加群反馈
