### ISSUE TITLE
[Bug] 为什么没有视频号的视频消息呢？

### ISSUE THREAD

**Issue by anrgct** [LC044/WeChatMsg#417]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

None

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

我导出html、word、txt，都没有视频号的消息，视频号的视频消息似乎被排出了？

### 🚦 期望结果 | Expected Behavior

能获取视频消息

**Comment by LC044** [comment]
2.0.7已经实现该功能

**Comment by anrgct** [comment]
的确可以了👍感谢
