### ISSUE TITLE
[Bug] 当微信已经在pc登录情况下，有新的消息产生，如果要解密出最新的消息并导出，好像必须要重新登陆一次微信？

### ISSUE THREAD

**Issue by weizeng** [LC044/WeChatMsg#419]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

None

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

报错截图:

### 🚦 期望结果 | Expected Behavior

能否不用重新登录？

**Comment by LC044** [comment]
不能
