### ISSUE TITLE
求朋友圈  导出

### ISSUE THREAD

**Issue by willshion** [LC044/WeChatMsg#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Awalter0411** [comment]
支持！

**Comment by jundaychan** [comment]
支持！

**Comment by Ultrasty** [comment]
朋友圈不是本地数据，导出朋友圈涉及频繁爬取微信的接口，很容易被ban
不过我也想要这个功能，能每天自动存就更好了~
