### ISSUE TITLE
[Request] 加入朋友圈好友点赞和评论数据

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#420]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

已购 VIP，整体还是挺好用的
朋友圈现在 html 里还没有点赞和评论数据，希望能加上。
朋友圈本来就是跟朋友互动的地方，少了点赞评论感觉都少了好多东西

### 🧐 解决方案 | Proposed Solution

简单看了一下那个 Sns.db，FeedsV20 和 CommentV20 可以通过 FeedId 连接，CommentV20 里是点赞评论，CommentType = 1 是点赞，等于 2 是评论，都是明文存储；评论者和回复对象也有，最麻烦的地方就是写个界面了，但是难度也不大，希望开发者能实现这个功能

**Comment by LC044** [comment]
点赞和评论已实现，下个版本上线，可以留意更新通知

**Comment by IllyaMiller** [comment]
好的！辛苦大大了😍
