### ISSUE TITLE
[Bug] 朋友圈评论显示问题

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#425]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/167181872/fd70b4af-bb8b-4f7a-8b54-8c3c3e220c9e)
一个是这个布局的话如果字很多会溢出。
另一个是他不能像pyq那样文字和回复人等信息同级别

### 📷 复现步骤 | Recurrence Steps

给朋友备注很长然后回复的信息也很长

**Comment by LC044** [comment]
已修复该问题，可以等下个版本
