### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sudolxwh** [LC044/WeChatMsg#428]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/63297908/a722e184-a699-490a-98aa-944cfd64be5f)
导出聊天记录html的时候，一直卡着在这里。好奇怪。

### 🚦 期望结果 | Expected Behavior

修复bug

**Comment by LC044** [comment]
最新版应该没这个问题了
