### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'

### ISSUE THREAD

**Issue by bigOK666** [LC044/WeChatMsg#43]
**Describe the bug**
运行 `run .\decrypt_window.py` 或者以管理员身份运行exe时，在获取信息成功后，点击开始会在98%的时候程序崩溃，并显示无法找到`app/DataBase/Msg/MSG0.db'
**To Reproduce**
1. `run .\decrypt_window.py`
2. Click on '获取信息'
3. Click on `开始启动
4. 98%时程序崩溃，并显示`FileNotFoundError: [Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'`

**Expected behavior**
解密成功

**Screenshots**
```
Traceback (most recent call last):
  File "I:\WeChatMsg\app\ui_pc\tool\pc_decrypt\pc_decrypt.py", line 176, in btnExitClicked
    shutil.copy("app/DataBase/Msg/MSG0.db", target_database)  # ʹ��һ�����ݿ��ļ���Ϊģ��
  File "C:\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'app/DataBase/Msg/MSG0.db'
```

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Python Version [3.10.6]

**Additional context**
获取信息时，key为`None`

**Comment by yushiro** [comment]
同样的问题， 用的是源码运行的版本,  commit hash为1381f9bd8c7cf34b973a6039b2a50c983f827c0e
微信路径就是指向wxid_开头的目录， 密钥为None
一点“开始启动”， 就卡98%了

**Comment by scavin** [comment]
同样的问题，这个文件 `app/DataBase/Msg/MSG0.db` 未成功创建，Msg 文件夹是空的。

**Comment by LC044** [comment]
更新微信版本重启电脑是否能解决该问题

**Comment by lengyingmofeng** [comment]
```python
2023-12-10 21:35:10,060 - pc_decrypt.py[line:87] - ERROR: Traceback (most recent call last):
  File "F:\WeChatMsg\app\ui_pc\tool\pc_decrypt\pc_decrypt.py", line 55, in get_info
    result = get_wx_info.get_info(VERSION_LIST)
  File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 286, in get_info
    result = read_info(VERSION_LIST, True)  # 读取微信信息
  File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 259, in read_info
    tmp_rd['key'] = get_key(tmp_rd['filePath'], addrLen)
  File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 197, in get_key
    if verify_key(key_bytes, MicroMsg_path):
  File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 160, in verify_key
    with open(wx_db_path, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'None\\MSG\\MicroMsg.db'
```
这个是什么错误

**Comment by LC044** [comment]
> ```python
> 2023-12-10 21:35:10,060 - pc_decrypt.py[line:87] - ERROR: Traceback (most recent call last):
>   File "F:\WeChatMsg\app\ui_pc\tool\pc_decrypt\pc_decrypt.py", line 55, in get_info
>     result = get_wx_info.get_info(VERSION_LIST)
>   File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 286, in get_info
>     result = read_info(VERSION_LIST, True)  # 读取微信信息
>   File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 259, in read_info
>     tmp_rd['key'] = get_key(tmp_rd['filePath'], addrLen)
>   File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 197, in get_key
>     if verify_key(key_bytes, MicroMsg_path):
>   File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 160, in verify_key
>     with open(wx_db_path, "rb") as file:
> FileNotFoundError: [Errno 2] No such file or directory: 'None\\MSG\\MicroMsg.db'
> ```
> 
> 这个是什么错误

试试最新版本能否解决该问题

**Comment by Epiphuany** [comment]
> > ```python
> > 2023-12-10 21:35:10,060 - pc_decrypt.py[line:87] - ERROR: Traceback (most recent call last):
> >   File "F:\WeChatMsg\app\ui_pc\tool\pc_decrypt\pc_decrypt.py", line 55, in get_info
> >     result = get_wx_info.get_info(VERSION_LIST)
> >   File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 286, in get_info
> >     result = read_info(VERSION_LIST, True)  # 读取微信信息
> >   File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 259, in read_info
> >     tmp_rd['key'] = get_key(tmp_rd['filePath'], addrLen)
> >   File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 197, in get_key
> >     if verify_key(key_bytes, MicroMsg_path):
> >   File "F:\WeChatMsg\app\decrypt\get_wx_info.py", line 160, in verify_key
> >     with open(wx_db_path, "rb") as file:
> > FileNotFoundError: [Errno 2] No such file or directory: 'None\\MSG\\MicroMsg.db'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个是什么错误
> 
> 试试最新版本能否解决该问题
我的也是出现这个问题，最新版

**Comment by scavin** [comment]
我的最新版本已解决此问题。 https://www.appinn.com/wechatmsg/
