### ISSUE TITLE
[Bug] pyq HTML不能正常显示换行

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#430]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

换行没有了，这个挺好理解的不配图了。

### 🚦 期望结果 | Expected Behavior

把换行和留白都原样保留

### 📝 补充信息 | Additional Information

建议 .cellContent>p 加一个 white-space: pre-wrap，试了一下这个最符合朋友圈的格式。

**Comment by LC044** [comment]
以修复
