### ISSUE TITLE
[Request] 能否支持基于条件过滤后，在每条聊天记录边支持勾选导出

### ISSUE THREAD

**Issue by duguxiaobiao** [LC044/WeChatMsg#434]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

目前支持导出的选择数据匹配是基于日期和数据类型，我想要筛选后， 在选择性的选出指定记录导出，目前直接导出成pdf，无法在进行操作pdf来删除或者裁剪部分聊天记录。

### 🧐 解决方案 | Proposed Solution

想要筛选后， 在选择性的选出指定记录导出

**Comment by LC044** [comment]
做不了
