### ISSUE TITLE
[Question] 数据安全问题

### ISSUE THREAD

**Issue by kongfucurry** [LC044/WeChatMsg#436]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

这个东西需要联网吗？如果需要，那数据安全能得到保障吗？毕竟微信里面多多少少会涉及到一些敏感信息，功能目前来看已经很有意思了，但如果安全性得不到保障，总会有一种后背发凉的感觉

**Comment by sanbei011** [comment]
**这个完全就是本地的**

**Comment by xinyikan** [comment]
抓包看一下不就知道了，或者打开火绒联网行为管理

**Comment by lqz72** [comment]
检查了一遍代码，唯一涉及云端的就是config.py中定义的SERVER_API_URL这个接口，但是这个接口只会用于两个目的：1、上传版本信息2、生成年度报告时分享你的年度报告。如果你不放心的话可以把这个接口设置为空''，不影响正常使用

**Comment by kongfucurry** [comment]
> 检查了一遍代码，唯一涉及云端的就是config.py中定义的SERVER_API_URL这个接口，但是这个接口只会用于两个目的：1、上传版本信息、错误信息以及检查更新等；2、生成年度报告时分享你的年度报告。如果你不放心的话可以把这个接口设置为空''，不影响正常使用

感谢大佬
