### ISSUE TITLE
[Bug] 音乐分享为空

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#444]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图: html导出音乐分享那个栏什么都没有

### 🚦 期望结果 | Expected Behavior

看了看开源的music_share函数没啥问题，把数据库里的东西扒出来发现我的所有音乐分享都是 type=49, subtype=76 而不是 subtype=3。。
开源代码跑了一下发现换了这个subtype就能用了。。。

**Comment by LC044** [comment]
你的全部都是76吗，我这边是3

**Comment by IllyaMiller** [comment]
全都是76，没有一个3

> 你的全部都是76吗，我这边是3

**Comment by LC044** [comment]
试试2.0.9
