### ISSUE TITLE
[Bug] 分享内容里的回车还是\n，包括有的地方转义没处理好

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#445]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图: 
![image](https://github.com/LC044/WeChatMsg/assets/167181872/e0239b12-e03e-4d4b-8ddd-2927a03927bc)
![image](https://github.com/LC044/WeChatMsg/assets/167181872/6c4caf5c-a400-4527-9f15-9b45d97c3d1c)
![image](https://github.com/LC044/WeChatMsg/assets/167181872/515f8b2c-fbcd-4761-b2f1-353c223247bd)
![image](https://github.com/LC044/WeChatMsg/assets/167181872/6a545787-4523-4bb1-b361-42b14b0760a1)

### 🚦 期望结果 | Expected Behavior

我看微信的处理是有一个换行就给他换了，有两个及以上的换行就把后面的直接扔掉了
![image](https://github.com/LC044/WeChatMsg/assets/167181872/786b5f91-7d12-4045-97a8-6c16b1f9b1be)
![image](https://github.com/LC044/WeChatMsg/assets/167181872/49136299-8857-4ad4-9220-be156866a721)
![image](https://github.com/LC044/WeChatMsg/assets/167181872/750743c9-3fdb-4a54-99b8-170a2ec2611d)
![image](https://github.com/LC044/WeChatMsg/assets/167181872/749f40b1-6d01-4806-a462-e0698884276f)

**Comment by LC044** [comment]
试试最新版2.0.9

**Comment by IllyaMiller** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/167181872/da690e24-74a7-4f43-8907-c414db6fdd59)
这个没解决

**Comment by IllyaMiller** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/167181872/8b51d38c-0de1-430e-a27d-138a3aa99815)
这个也没有

**Comment by IllyaMiller** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/167181872/d13420ea-0d46-4f75-9b84-dbdc9379d1e2)
