### ISSUE TITLE
[Question] 提问大神们为什么我下载了“使用c＋＋的桌面开发”然后用这个编译器下载”r requirements.txt“ 会一直给我报错呢？

### ISSUE THREAD

**Issue by ccIsCool6** [LC044/WeChatMsg#448]
### 👌 是否检查过没有类似issue

就不检查

### 🧐 问题描述 | Proposed Solution

![image](https://github.com/LC044/WeChatMsg/assets/151799590/a2cdf7e4-bbb9-4068-aad5-8d6913769ab8)
这样的错误！┭┮﹏┭┮
有人知道吗

**Comment by LC044** [comment]
这个错误很典型，可以去搜一下解决教程
