### ISSUE TITLE
[Bug] 音乐的分享倒是能显示出来了但是html里没有适配这个subtype=76

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#449]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:

**Comment by IllyaMiller** [comment]
所以点击音乐和音频分类依旧什么都没有

**Comment by LC044** [comment]
HTML能显示，但是按类型筛选没有是吧

**Comment by IllyaMiller** [comment]
> HTML能显示，但是按类型筛选没有是吧

对
