### ISSUE TITLE
[Request] 导出pdf的时候可以不弹出来这么多框吗（）

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#455]
### 👌 是否检查过没有类似issue

就不检查

### 🥰 需求描述 | Feature Description

![image](https://github.com/LC044/WeChatMsg/assets/167181872/2d478f46-4819-472b-a60f-3b342a377c2d)

### 🧐 解决方案 | Proposed Solution

rt

**Comment by LC044** [comment]
不能
