### ISSUE TITLE
[Request] 语音转文字下面这个框的小三角好奇怪啊

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#456]
### 👌 是否检查过没有类似issue

就不检查

### 🥰 需求描述 | Feature Description

![image](https://github.com/LC044/WeChatMsg/assets/167181872/d0c4b5d9-e045-473f-8350-488db9bbf123)

### 🧐 解决方案 | Proposed Solution

rt

**Comment by LC044** [comment]
不奇怪
