### ISSUE TITLE
[Bug] 为什么日期最早只能设置202201？

### ISSUE THREAD

**Issue by fangyucun** [LC044/WeChatMsg#457]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

3.12

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:

**Comment by xmcn532** [comment]
我是所有聊天记录都只能从2019.1.3开始统计

**Comment by LC044** [comment]
这个时间只能选择有聊天记录的日期，可以导出看看最早的聊天记录是不是2019.1.3

**Comment by xmcn532** [comment]
> 这个时间只能选择有聊天记录的日期，可以导出看看最早的聊天记录是不是2019.1.3

导出的聊天记录也是2019.1.3但是实际的聊天记录更早前面还有好多年的也不能导出
 微信聊天记录里面是都有的但是不能点到18年以前的日期选了就卡死

**Comment by LC044** [comment]
> > 这个时间只能选择有聊天记录的日期，可以导出看看最早的聊天记录是不是2019.1.3
> 
> 导出的聊天记录也是2019.1.3但是实际的聊天记录更早前面还有好多年的也不能导出

可以检查一下数据库数据

**Comment by leantli** [comment]
可以看下是不是备份迁移的时候是不是在电脑端的微信选择：迁移与备份-备份与恢复-备份聊天记录至电脑。
如果是在电脑上操作备份迁移，聊天记录不会全量同步手机的(很坑)。。。
正确的操作应该是在手机端微信选择：我-设置-聊天-聊天记录迁移与备份-迁移-迁移到电脑微信
