### ISSUE TITLE
[Bug] 年度报告中存在显示问题，23年油389天

### ISSUE THREAD

**Issue by SunnyBoy-WYH** [LC044/WeChatMsg#458]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

None

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/48077841/1f3d0014-d6ea-4bcc-a6be-ca1624a4dc90)

**Comment by LC044** [comment]
年度报告就应该选一年的数据
