### ISSUE TITLE
[Bug] 视频号栏只有一条消息的话，点击时间轴会复制出来一份一模一样的

### ISSUE THREAD

**Issue by IllyaMiller** [LC044/WeChatMsg#459]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

报错截图: 
![image](https://github.com/LC044/WeChatMsg/assets/167181872/63239374-5bab-4a46-b297-0e4d0ec903f8)
![image](https://github.com/LC044/WeChatMsg/assets/167181872/c46b967f-0220-4a66-8671-b41771a123d7)
![image](https://github.com/LC044/WeChatMsg/assets/167181872/edb4b10e-e3c4-4cb2-a3c5-4b15811ae168)

### 📷 复现步骤 | Recurrence Steps

切到别的页面再切回来，然后点击时间轴的月份，最多可以复制11份（可能还可以更多）
别的页面没有测试，也许也有同样的问题

**Comment by LC044** [comment]
试试2.0.11
