### ISSUE TITLE
[Request] 能不能出个一键训练AI，我都不知道怎么训练那个自带AI，显示未接入聊天内容，只能体验基础

### ISSUE THREAD

**Issue by zztzz8601** [LC044/WeChatMsg#470]
### 👌 是否检查过没有类似issue

就不检查

### 🥰 需求描述 | Feature Description

能不能出个一键训练AI，我都不知道怎么训练那个自带AI，显示未接入聊天内容，只能体验基础

### 🧐 解决方案 | Proposed Solution

能不能出个一键训练AI，我都不知道怎么训练那个自带AI，显示未接入聊天内容，只能体验基础

**Comment by LC044** [comment]
训练AI需要很多卡

**Comment by foebor26291** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/59093369/5bfc7f61-899b-4d2c-8a16-d4f860a06f69)

**Comment by foebor26291** [comment]
text me
