### ISSUE TITLE
点完时间轴中4月的效果，页面还是显示3月

### ISSUE THREAD

**Issue by wyx163** [LC044/WeChatMsg#472]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

None

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![@3EN_LU81$ Q4`24YB_UIJE](https://github.com/LC044/WeChatMsg/assets/118347703/a128b17a-ebfd-445b-93a4-f3a3bd326d53)

### 🚦 期望结果 | Expected Behavior

点击时间轴月份，页面上方出现该月首次聊天记录

**Comment by LC044** [comment]
试试2.0.11
