### ISSUE TITLE
[Request] 买不了会员

### ISSUE THREAD

**Issue by taozhiyuai** [LC044/WeChatMsg#474]
### 👌 是否检查过没有类似issue

就不检查

### 🥰 需求描述 | Feature Description

M3 MAX 128GB的电脑因为不能用这个软件所以不能买会员.

### 🧐 解决方案 | Proposed Solution

支持MAC

### 📝 补充信息 | Additional Information

加快速度

**Comment by LC044** [comment]
Mac做不了
