### ISSUE TITLE
[Question] 有没有java版本的

### ISSUE THREAD

**Issue by lzs5091** [LC044/WeChatMsg#477]
### 👌 是否检查过没有类似issue

就不检查

### 🧐 问题描述 | Proposed Solution

RT

### 📝 补充信息 | Additional Information

RT

**Comment by LC044** [comment]
没有

**Comment by xuchengsheng** [comment]
wx-dump-4j是一款基于Java开发的微信数据分析工具。它不仅可以准确显示您的好友数、群聊数和当日的消息总量，还提供了过去15天内的每日消息统计功能，让您清晰了解自己的社交活跃度。此外它还能够识别并展示最近一个月内与您互动最频繁的前10位联系人。它还支持导出微信的聊天记录、联系人和群聊信息，甚至可以查看超过三天限制的朋友圈历史记录。
https://github.com/xuchengsheng/wx-dump-4j
