### ISSUE TITLE
我使用的是在windows应用中心下载的2.6.3.200版本（无法升级新版本了）[Request] 

### ISSUE THREAD

**Issue by chenjy1** [LC044/WeChatMsg#480]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

我想在提取出就有的聊天记录，还有可能么

### 🧐 解决方案 | Proposed Solution

能否维护对2.6.3.200的支持，或者请问我重新下载一个新版本的微信会使得聊天记录清理掉么

**Comment by LC044** [comment]
下载最新版微信使用
