### ISSUE TITLE
[Request] 批量导出增加追加和勾选非群功能

### ISSUE THREAD

**Issue by farceli** [LC044/WeChatMsg#481]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

软件的->数据->批量导出页面在只想导出好友时和已导出聊天再次导出时不友好

### 🧐 解决方案 | Proposed Solution

增加一键取消勾选群或者一键全选非群   和   导出时同好友/群已存在记录部分跳过，只在已有好友/群目录中追加新增聊天部分

**Comment by LC044** [comment]
已实现该功能，可以下载2.0.12使用
