### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by IShinji** [LC044/WeChatMsg#484]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

无法导出微信群聊信息。大概是聊天记录比较大，同步到PC的时候，可以看到聊天记录是2.4G。尝试了html导出，程序导出2-3分钟后崩溃，再尝试txt导出，还是崩溃。

### 🚦 期望结果 | Expected Behavior

可以正常运行

**Comment by LC044** [comment]
多试几次

**Comment by IShinji** [comment]
试了好几次了……
