### ISSUE TITLE
批量导出增加AI对话专用TXT格式[Request] 

### ISSUE THREAD

**Issue by bookwoods** [LC044/WeChatMsg#486]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

目前批量导出的格式中没有AI对话专用TXT格式，想导出该格式只能手动一个个点

### 🧐 解决方案 | Proposed Solution

建议在导出格式中增加该格式
![image](https://github.com/LC044/WeChatMsg/assets/106570410/37fc8423-dac9-47e3-96d5-c0ded9cebaba)

**Comment by LC044** [comment]
2.0.13已实现
