### ISSUE TITLE
[Bug] 解析结果中语音记录丢失，html无法导出语音翻译后的文本

### ISSUE THREAD

**Issue by primejava** [LC044/WeChatMsg#487]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:原微信截图
![原本](https://github.com/LC044/WeChatMsg/assets/10646824/60aa0fe2-b44e-439e-a69b-52d1a835cf00)
 程序截图

![解析](https://github.com/LC044/WeChatMsg/assets/10646824/0a0e887c-0b68-478e-baf9-25a3b1a0d079)

### 🚦 期望结果 | Expected Behavior

希望html可以导出语音翻译后的文本。另外我看到同样的问题已经有好几个人提出，但没有解决就被关闭了，希望不要随便关闭issue

**Comment by LC044** [comment]
很显然你这不是HTML
