### ISSUE TITLE
[Question] image文件夹下的图片名称逻辑

### ISSUE THREAD

**Issue by stay-leave** [LC044/WeChatMsg#490]
### 👌 是否检查过没有类似issue

否

### 🧐 问题描述 | Proposed Solution

请问csv导出的聊天记录里的图片内容和保存到本地image文件夹的图片名有对应关系吗？我想能根据csv的图片找到对应的本地图片，该怎么做？谢谢大佬

**Comment by LC044** [comment]
可以看一下这个：https://github.com/LC044/WeChatMsg/blob/master/app/util/exporter/exporter_html.py
