### ISSUE TITLE
听说你偷数据？
https://mp.weixin.qq.com/s/mvae88fxG2BFte2TTGh1ZQ

### ISSUE THREAD

**Issue by Privauto** [LC044/WeChatMsg#491]

**Comment by sysfox** [comment]
md，也刚刚看到这个文章，分析没问题。
@LC044 咱要不给个合理的解释？

**Comment by sysfox** [comment]
上传人家用户名、昵称和号码算什么意思？

**Comment by Sicalxy** [comment]
https://github.com/LC044/WeChatMsg/blob/8be7d0d34e49b591c926c24f1531d45ae9a7feb5/app/ui/tool/get_bias_addr/get_bias_addr.py#L102-L108

https://github.com/LC044/WeChatMsg/blob/8be7d0d34e49b591c926c24f1531d45ae9a7feb5/app/config.py#L35

**Comment by LC044** [comment]
大家可以参考一下这个啊：https://github.com/LC044/WeChatMsg/issues/492

**Comment by LC044** [comment]
> https://github.com/LC044/WeChatMsg/blob/8be7d0d34e49b591c926c24f1531d45ae9a7feb5/app/ui/tool/get_bias_addr/get_bias_addr.py#L102-L108
> 
> https://github.com/LC044/WeChatMsg/blob/8be7d0d34e49b591c926c24f1531d45ae9a7feb5/app/config.py#L35

version_data从字面上看它也不是用户个人数据，字面上看不出来的话只有自己跑一下才知道这个是个什么东西。没有这个偏移基址，没法解析数据，大家的微信版本用的都不一样，我得一个个去下载适配之后才能用，有弹窗说明，写的明明白白。参考[issue315](https://github.com/LC044/WeChatMsg/issues/315), #308 #185

**Comment by sysfox** [comment]
我们不理解的是为什么会上传昵称、账号、手机号(尽管似乎经过了加密)，适配更多版本发送微信版本号不就行了吗
(当然我承认自己并不了解本工具的整个解析数据原理
但是还请作者解释下谢谢

**Comment by LC044** [comment]
> 我们不理解的是为什么会上传昵称、账号、手机号(尽管似乎经过了加密)，适配更多版本发送微信版本号不就行了吗 (当然我承认自己并不了解本工具的整个解析数据原理 但是还请作者解释下谢谢

上传的数据不是什么昵称、账号、手机号，而是版本信息：("为了适配更多版本，需要收集微信的版本信息，该操作不会上传包括手机号、微信号、昵称等在内的任何信息\n示例数据：\n\"3.9.9.27\": [68065304, 0, 68065112, 0, 68066576]")，也不是加密的，所有人的这些信息都是一样的，只跟微信版本有关。

**Comment by LC044** [comment]
> > 我们不理解的是为什么会上传昵称、账号、手机号(尽管似乎经过了加密)，适配更多版本发送微信版本号不就行了吗 (当然我承认自己并不了解本工具的整个解析数据原理 但是还请作者解释下谢谢
> 
> 上传的数据不是什么昵称、账号、手机号，而是版本信息：("为了适配更多版本，需要收集微信的版本信息，该操作不会上传包括手机号、微信号、昵称等在内的任何信息\n示例数据：\n"3.9.9.27": [68065304, 0, 68065112, 0, 68066576]")，也不是加密的，所有人的这些信息都是一样的，只跟微信版本有关。

只需要收集一次，然后所有人都能用了，不用每次都要我发布一个新版本大家才能用

**Comment by sysfox** [comment]
也就是说，如果我使用**同一个**微信版本，解析**不同的**账号数据，放松的信息依然相同是吗？

**Comment by LC044** [comment]
> 也就是说，如果我使用**同一个**微信版本，解析**不同的**账号数据，发送的信息依然相同是吗？

是的

**Comment by sysfox** [comment]
如果确实如此的话，那我为自己的误会向您道歉 @LC044

**Comment by sysfox** [comment]
@Privauto issue关掉吧

**Comment by LC044** [comment]
> > 也就是说，如果我使用**同一个**微信版本，解析**不同的**账号数据，发送的信息依然相同是吗？
> 
> 是的

而且只有解析2才会发送这个信息，解析2是在解析1用不了的情况下使用的，解析1用不了就是因为没有这个版本信息，所以只需要第一个用某个微信版本的人上传之后后面的人才可以用解析1一键解析数据

**Comment by sysfox** [comment]
那确实是个很好的方法，我想我应该去跟这个公众号的作者联系下删文，这确实是个误解

**Comment by LC044** [comment]
> 那确实是个很好的方法，我想我应该去跟这个公众号的作者联系下删文，这确实是个误解

感谢

**Comment by dem0ns** [comment]
文章作者应该是抓过包的，然后发现实锤不了，为了流量就这样搞

**Comment by sysfox** [comment]
文章已删除

**Comment by sysfox** [comment]
> 文章作者应该是抓过包的，然后发现实锤不了，为了流量就这样搞

这个验证起来是挺方便，用多个账号Burp抓包就知道了

**Comment by LC044** [comment]
之前kimi就找过我合作AI对话的项目，接入聊天记录进行问答，啥都谈好了就是因为隐私问题最后没谈拢

![image](https://github.com/user-attachments/assets/3afbdcca-ab3e-4d2d-83f2-41f6f65a829f)

![image](https://github.com/user-attachments/assets/45f98d4b-6a6d-4555-882f-521381eea4b5)
