### ISSUE TITLE
[Bug] 导出时显示权限异常请联系管理

### ISSUE THREAD

**Issue by BAJimH** [LC044/WeChatMsg#497]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

None

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/user-attachments/assets/9f64f7ee-76d1-4fe7-96bd-776cc5a6d4de)

**Comment by tckntckn** [comment]
问题复现，请问如何解决
