### ISSUE TITLE
[Bug] 导出朋友圈的的时候存在部分图片缺失的情况

### ISSUE THREAD

**Issue by Sivanyanst** [LC044/WeChatMsg#499]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![bugpic](https://cdn.jsdelivr.net/gh/sivanyanst/picgo@main/img/Snipaste_2024-08-06_21-39-16.png)

### 🚦 期望结果 | Expected Behavior

**能够完整显示图片，或者告知我是哪一部分出现了问题**

### 📷 复现步骤 | Recurrence Steps

客户端导出html➡️打开html➡️发现图片缺失（重复一次依旧出现问题）

### 📝 补充信息 | Additional Information

（一名小白的困惑）麻烦解答了！感谢

**Comment by LC044** [comment]
图片就是这样的，没法显示
