### ISSUE TITLE
微信8.0.40国内版，统计信息和生成年度报告无法使用，

### ISSUE THREAD

**Issue by gurain** [LC044/WeChatMsg#5]
统计信息：
![image](https://github.com/LC044/WeChatMsg/assets/61127675/e6f6ac5e-c492-4a3a-b3ac-c833219a5cbc)
有时候报错的信息中，我似乎看到了拍一拍后提示的文字，疑似没有适配拍一拍。

年度报告：
![image](https://github.com/LC044/WeChatMsg/assets/61127675/1ce63715-4c60-4bd5-bacc-e8311f85d543)

**Comment by LC044** [comment]
年度报告还在完善中，暂时还不支持自动化展示，最近实现该功能，如果方便的话可以发一下出现错误的拍一拍的原始内容吗，这一部分格式比较复杂，可能遗漏了部分，可以暂时使用try: [code] except:pass暂时跳过异常

**Comment by LC044** [comment]
兄弟，该项目已经很完善了，可以上线看看了
