### ISSUE TITLE
[Request] 批量导出群消息为AI TXT格式时，希望能够展示群友昵称

### ISSUE THREAD

**Issue by bookwoods** [LC044/WeChatMsg#502]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

目前双人对话的AI txt格式批量导出已实现，效果很好，但是群消息导出该格式时出现问题，说话人昵称全部被隐藏，消息内容全部用空格隔开，很乱，希望能够更新该功能
![image](https://github.com/user-attachments/assets/1e37c82f-7dd5-4020-b8a1-6325a183dcfe)

### 🧐 解决方案 | Proposed Solution

群消息显示说话人，并参照双人对话格式，用换行符分隔开

### 📝 补充信息 | Additional Information

我有很多三四个人的同学小群，但是这类对话记录很难搞定，希望大佬后续更新考虑该功能，感谢！

**Comment by LC044** [comment]
最新版已支持该功能
