### ISSUE TITLE
[Bug]AI TXT或JSON导出时，选择了语音，导出时也没有（转成文字形式）

### ISSUE THREAD

**Issue by luisxin** [LC044/WeChatMsg#503]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

None

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:JSON和AI TXT模式下没有语音转文本
![image](https://github.com/user-attachments/assets/302d31f0-6899-447b-a4df-9bd316e088df)

### 🚦 期望结果 | Expected Behavior

可以将语音信息转成文本。这样对话才能完整。

**Comment by LC044** [comment]
最新版已修复该问题
