### ISSUE TITLE
[Request] 提供精确到天的日期聊天记录手动选择（像微信PC版一样选择具体某一天的聊天记录）

### ISSUE THREAD

**Issue by TickToTock** [LC044/WeChatMsg#505]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

导出为html文件后，能否和微信PC版/微信安卓手机版一样，手动选择xx年xx月xx日，具体某一天的聊天记录
目前版本MemoTrace2013下，导出的html文件，只能在月份中选择，当某个聊天记录话非常多的时候，一个月一个月的找效率很低，是否可以在后续版本中进行更新，感谢
![精确到日期的聊天记录定位04-当前版本功能](https://github.com/user-attachments/assets/af31300b-84f6-42b5-b911-197d30df33c2)

### 🧐 解决方案 | Proposed Solution

像微信PC版那样，增加日期，按天选择的选项
![精确到日期的聊天记录定位02](https://github.com/user-attachments/assets/e47a1509-8936-432c-9e90-21bdfa37da5d)
![精确到日期的聊天记录定位03](https://github.com/user-attachments/assets/d30269a4-4607-4af7-9b19-f55359f2c0b3)
![精确到日期的聊天记录定位01](https://github.com/user-attachments/assets/fa339885-8462-47d2-9658-f205279adff5)

**Comment by LC044** [comment]
最新版已支持该功能
