### ISSUE TITLE
[Request] 本软件打包方式存在被破解可能，建议改进

### ISSUE THREAD

**Issue by hi-zcy** [LC044/WeChatMsg#506]
### 👌 是否检查过没有类似issue

是

### 🥰 需求描述 | Feature Description

如题，本软件打包方式为Pyinstaller，存在被破解可能（pyinstxtrator-ng / pycdc），建议改进（我不知道算不算bug反馈，所以加了功能建议的标签）～

### 🧐 解决方案 | Proposed Solution

将打包方式换为nutkia+pystand[就可以这样](https://www.zhihu.com/question/281858271/answer/3544188023)。

### 📝 补充信息 | Additional Information

在知乎上看到的这种打包方式，并且根据_internal文件夹结构判断是pyinstaller（很明显）～

**Comment by unknown-o** [comment]
这项目本来就是开源项目，破解个毛线。
第一次见那么呆issues。
