### ISSUE TITLE
[Request] 本软件的CLI支持建议

### ISSUE THREAD

**Issue by hi-zcy** [LC044/WeChatMsg#507]
### 👌 是否检查过没有类似issue

否

### 🥰 需求描述 | Feature Description

因为我需要在输出结果后进行一些其他处理，然而手动处理效率又略显底下，所以能不能添加一个专门的CLI接口？

### 🧐 解决方案 | Proposed Solution

1. 创建一个新的分支，将窗口代码取消，main.py改为cli接口，用CLI调用；
2. 与main同级目录添加api.py，在10236端口（或者别的）开放public/authedAPI，方便调用（optional）。

### 📝 补充信息 | Additional Information

无。

**Comment by xianfei** [comment]
https://github.com/xaoyaoo/PyWxDump
