### ISSUE TITLE
[Bug] OPENSSL_Uplink(00007FFF541 A9C88 8 ）： no OPENSSL AppIink

### ISSUE THREAD

**Issue by Nu1i** [LC044/WeChatMsg#511]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/user-attachments/assets/af51f918-880b-4536-a649-98c5ea4f44f7)

### 📷 复现步骤 | Recurrence Steps

打开软件点击获取信息就报错了。

**Comment by LC044** [comment]
[参考教程](https://memotrace.cn/doc/posts/error/unknown.html)
