### ISSUE TITLE
[Bug] 导出不全，只到1月份

### ISSUE THREAD

**Issue by lskyzero** [LC044/WeChatMsg#513]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

聊天记录明明到从2020年至23年7月份都有，但是导出的时候到最后只去到23年1月份，这是怎么回事？

**Comment by lskyzero** [comment]
我到处格式是html格式

**Comment by lskyzero** [comment]
![Snipaste_2024-09-26_21-28-34](https://github.com/user-attachments/assets/cbc452dd-85c6-4cd2-b984-bede2cf44b02)
日志这样提示

**Comment by lskyzero** [comment]
在微信PC版该人的聊天记录里显示也正常，就是导出就没有

**Comment by LC044** [comment]
[聊天记录缺失](https://memotrace.cn/doc/posts/error/faq.html)
