### ISSUE TITLE
[Request] 能否支持win7？

### ISSUE THREAD

**Issue by xy0124** [LC044/WeChatMsg#516]
### 👌 是否检查过没有类似issue

就不检查

### 🥰 需求描述 | Feature Description

公司电脑受限制，是win7，能否支持到win7呢？

### 🧐 解决方案 | Proposed Solution

如上

**Comment by LC044** [comment]
> python3.8.10是官方支持win7的最后发布一个版本，将源代码克隆，版本换成3.8，所有的报错部分全部自己重新修改

可以试试，或许把聊天记录迁移到其他电脑上更方便
