### ISSUE TITLE
[Bug] No module named 'PyQt5' 

### ISSUE THREAD

**Issue by wzgrx** [LC044/WeChatMsg#519]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

3.11

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
<img width="865" alt="Snipaste_2024-10-31_23-16-48" src="https://github.com/user-attachments/assets/d8533797-44c9-4bf2-8d4e-b73d29e066c8">

### 🚦 期望结果 | Expected Behavior

正常启动

**Comment by LC044** [comment]
仔细阅读文档，根据文档进行操作
