### ISSUE TITLE
开源项目合作请求

### ISSUE THREAD

**Issue by ellermister** [LC044/WeChatMsg#52]
@LC044 你好，我对你的这个项目不太了解，今天看到后感觉很有兴趣。

**我想问下当前是否可以实现以下内容：**
1. 通过手机端备份的聊天记录文件，单一在PC端能否实现解密? 包含DB和img、video等资源文件。
2. 读取到明文数据库数据和文件结构是破坏式的，还是说可以通过 sqlcipher 连接数据库进行查改，资源文件也是一样修改。（此项指有没有签名类似的，如修改后备份将不可用）

如果可以做到上述两项，那么就水到渠成了。
我想做一个微信的垃圾文件清理工具，目前也有一个轻量的版本 [wechat-clean](https://github.com/ellermister/wechat-clean)，它会将你所有微信垃圾以及群消息清理，但只支持Android。
由于我更换到了IOS，因为IOS越狱带来的复杂性以及学习ios开发的成本太高就没有继续在IOS端做。

如果可以借助手机微信自带的备份功能，将数据备份到PC微信端（指备份的一个文件）且能解析能修改能还原回去，那么就可以实现
1. **定期备份聊天记录，似版本快照**
2. **不仅仅支持一个端设备，包括Android、IOS**
3. **能够按照版本将你备份的数据进行【自定义修剪】再存回手机微信，甚至手机端只留存最新滚动周期的一个版本数据。**
4. **在PC端对备份聊天记录的解析预览以及快速搜索、模糊搜索（微信的搜索很难用）。**

我更倾向于将微信的数据修建后放回手机，减少存储空间。
而你更倾向于将数据提取出来进行备份、预览归档。

而我看到你的issue也有人提议做成支持全平台以及PC端备份文件解密的需求：
- https://github.com/LC044/WeChatMsg/issues/28
- https://github.com/LC044/WeChatMsg/issues/46
- https://github.com/LC044/WeChatMsg/issues/35

所以我建议，项目采用 golang + vue 编写，用golang去读取数据，用前端去展示数据，也能够轻松处理数据以及绘制。

该方式的风险在于：
- **后期若微信新增了备份文件的签名校验机制，如果无法解密出数据或者还原回去，项目就吃灰了。**

由于上述的**关键内容**我还有没有详细研究过，一直较忙也没有时间处理，刚好看到这个项目，想询问你的想法，要不要一起做这个。

**Comment by LC044** [comment]
解密后的数据库无法还原
