### ISSUE TITLE
[Question] 导出json内容始终为空

### ISSUE THREAD

**Issue by kakuibeyond** [LC044/WeChatMsg#520]
### 👌 是否检查过没有类似issue

是

### 🧐 问题描述 | Proposed Solution

使用exe程序，选择左侧【好友】，选择群聊，点击右上角【导出聊天记录】，选择json格式，导出后有两个json文件：dev.json和train.json，两个文件都是空的
![image](https://github.com/user-attachments/assets/7179e1d3-1bdd-48a3-bf53-c4d02c6ea310)
> 补充说明：在弹出的窗口中，全选和全不选两种方式都试过，仍然没有内容
![image](https://github.com/user-attachments/assets/8ce08b2c-2188-4310-b39b-175a2f66c0cc)

**Comment by LC044** [comment]
导出为空可能是没有聊天数据，导出TXT看看有没有，如果没有的话，根据[教程](https://memotrace.cn/doc/posts/error/)进行操作，

**Comment by Kevin-free** [comment]
@kakuibeyond 同问题&同家驹粉😄 你解决了吗（群聊天记录不是空的，因为TXT有数据
