### ISSUE TITLE
[Bug] AI对话无法显示

### ISSUE THREAD

**Issue by north212wangbo** [LC044/WeChatMsg#521]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

None

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![memotrace](https://github.com/user-attachments/assets/abe2e6f3-99db-41d5-970d-2321673bad28)

**Comment by LC044** [comment]
AI对话没有接入聊天记录，没有什么功能，需要的话可以根据教程自己训练部署
