### ISSUE TITLE
[Bug] 付费功能“导出PDF”，聊天记录内的“图片消息”全部404

### ISSUE THREAD

**Issue by 627969687** [LC044/WeChatMsg#527]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

导出PDF功能图片部分全部404，导出HTML就正常

报错截图:
![image](https://github.com/user-attachments/assets/69e7e616-2445-4f64-80cb-393d42c63e3e)
![image](https://github.com/user-attachments/assets/462f1748-63d1-4dbb-87bb-6ce8d559e616)

**Comment by LC044** [comment]
检查一下HTML是否能正确显示图片，可以参考一下[教程](https://memotrace.cn/doc/posts/error/faq.html#%E4%BA%8C%E3%80%81%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),如果还解决不了的话可以添加客服微信解决
