### ISSUE TITLE
Hoping for iOS release

### ISSUE THREAD

**Issue by Peter-JY** [LC044/WeChatMsg#56]
Hope there'll be a release for iOS to uncode msg and imgs and so on. XD

**Comment by blkot** [comment]
> Hope there'll be a release for iOS to uncode msg and imgs and so on. XD

you probably cannot get the access to the  MicroMsg.db on iOS,
i did the same thing back in 2021 so, if you have a root android device:

1. backup your chat history through wechat desktop
2. login wechat on root android phone, sync the backup history to android.
3. port the files from android, there you go

not sure if this still works

**Comment by blkot** [comment]
> But, will all my files and voices and moments be backed-up and be accessible on that Android device? If not, is there any possible solution?

afaik,
- files? yes, as long as you have read them/downloaded them to your phone
- moments? probably no, i guess they are stored somewhere in the cloud of wechat. But they certainly are local cached on your phone.
- voices? not sure, but they are correctly ported to new devices, so i assume it is possible. i was focusing on the messages so i cannot help you there.

**Comment by LC044** [comment]
移动端可以使用微信的聊天记录迁移功能将数据迁移到电脑上，然后使用本软件进行操作获取相关数据，详细步骤可以查看[教程](https://blog.lc044.love/post/4)
