### ISSUE TITLE
关与数据泄露问题

### ISSUE THREAD

**Issue by 2429818251** [LC044/WeChatMsg#57]
我想知道工具在爬取解密聊天记录时，后台是否会进行留存打包发送到博主的客户端？

聊天记录里包含的敏感信息一点也不少，希望博主能用代码层面说明下这种情况的不存在性

**Comment by LC044** [comment]
代码已经全部开源，关于是否会留存打包发送到我的客户端你可自行查看

**Comment by abrahamgreyson** [comment]
真是奇葩，跑这里来问数据安全。

**Comment by 2429818251** [comment]
确实如此，觉得我这问题蠢也无可厚非，不过我的角度是站在无基础用户而非开发者角度上，也非常感谢认真回答我的人。另外我对py感兴趣，主攻确是java，我羡慕py的灵活性和ai层面。最后请对这方面的语言小白留些宽容，少些傲慢即可，以上。

**Comment by UNIDY2002** [comment]
那我就斗胆给小白概括一下。很简单的道理：代码可以自行审计，不敢用也没人逼着您用。大多数开源软件开发者都在用爱发电，有些用户却以最坏的恶意揣测开发者。这样的大环境下，也难怪开源生态为什么发展不起来了。

**Comment by 2429818251** [comment]
> 那我就斗胆给小白概括一下。很简单的道理：代码可以自行审计，不敢用也没人逼着您用。大多数开源软件开发者都在用爱发电，有些用户却以最坏的恶意揣测开发者。这样的大环境下，也难怪开源生态为什么发展不起来了。

我又看了下我的提问，确实有攻击性，这个得改。但首先要纠正恶意揣测，我只是想合理提问，虽然提问水准有待提高。关于社区我了解的不多，只本地搭建过几个项目而已，更没有开源过。用爱发电的社区理念我很认同并且支持，社区很好，我也想维护。就先从学习社区守则开始吧。
