### ISSUE TITLE
加载慢的问题

### ISSUE THREAD

**Issue by 1176109313** [LC044/WeChatMsg#59]
我的聊天记录有40多G，我也不知道为什么这么离谱。加载的时候，从好友列表逐个加载，要花很久。我想看某个好友的记录，要等加载队列到这个好友才能看到，导出功能更是要等所有人加载完之后才能使用。   所以我想，能不能我正在打开的聊天框优先加载，导出功能也加载完单个好友后就可以对其使用导出

**Comment by LC044** [comment]
已解决该问题
