### ISSUE TITLE
导出聊天记录后的文件能否更加通用？

### ISSUE THREAD

**Issue by gurain** [LC044/WeChatMsg#6]
我想把聊天记录保存好，但貌似目前这个软件导出的聊天记录都是分段的dcox文件，是否考虑将导出的聊天记录，保存成html网页资源，方便不同设备查看。或说保存成json文件，方便以后对数据进行处理？

**Comment by LC044** [comment]
感谢您的建议，我会尽快适配HTML格式，聊天记录存储在数据库的message表里，你可先试着操作该数据库获取想得到的任何数据（聊天数据库已经完成解密，可以使用任何支持sqllite数据库的软件打开该数据库文件）

**Comment by gurain** [comment]
十分感谢！！

**Comment by LC044** [comment]
很抱歉前一段时间有些忙没有更新项目，我新建一个QQ群474379264，如果你感兴趣的话可以加群讨论

**Comment by LC044** [comment]
你的诉求已经基本实现
