### ISSUE TITLE
无法渲染年度报告

### ISSUE THREAD

**Issue by blkot** [LC044/WeChatMsg#60]
**bug描述**
[current commit] https://github.com/LC044/WeChatMsg/commit/1381f9bd8c7cf34b973a6039b2a50c983f827c0e
1. requirements缺少flask？可手动pip i
2. webui缺少index.html

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/19670662/2ae4bd0c-3387-4ef1-b8c6-cfba4adbb549)

**是否可复现**

**运行环境:**
 - OS: Windows 10 22H2 19045.3693
 - Python版本: 3.10
 - 软件版本: PyCharm 2023.2.5
 - 微信版本: 3.9.8.15

**Additional context**

**Comment by LC044** [comment]
年度报告资源文件暂未上传，想体验的小伙伴可进去下载体验版

**Comment by mp075496706** [comment]
请问正式版什么时候可以体验到年度报告呢？

**Comment by LC044** [comment]
群里有体验版，功能正常之后会发布正式版

**Comment by willbeee** [comment]
requirements_pc.txt 里还缺少 `jieba` 和 `pyecharts`。 @LC044

**Comment by qhykwsw** [comment]
刚刚的正式版依然缺少index.html

**Comment by LC044** [comment]
> 刚刚的正式版依然缺少index.html

可下载exe程序体验该功能

**Comment by Matt-wzy** [comment]
开发者您好，我发现群里的beta版本也提示缺少相关的index.html

**Comment by xlm7** [comment]
> > 刚刚的正式版依然缺少index.html
> 
> 可下载exe程序体验该功能

正式版是要VIP才能看年度报告吗

**Comment by LC044** [comment]
已解决
