### ISSUE TITLE
有没有macos版的？

### ISSUE THREAD

**Issue by ObitoMa** [LC044/WeChatMsg#62]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by passmetheplay** [comment]
同问

**Comment by liran** [comment]
referred #46

**Comment by LC044** [comment]
等等吧，俺是贫困生，不敢用Mac，怕被举报

**Comment by printfCYQ** [comment]
期待😚macOS

> 等等吧，俺是贫困生，不敢用Mac，怕被举报

**Comment by HashCookie** [comment]
期待一波

**Comment by Zhehua-Hu** [comment]
> 等等吧，俺是贫困生，不敢用Mac，怕被举报

如果基于QT, 应该可以用pyQT跨平台

**Comment by LC044** [comment]
> > 等等吧，俺是贫困生，不敢用Mac，怕被举报
> 
> 如果基于QT, 应该可以用pyQT跨平台

你只知其一不知其二，有个库叫pywin32，win32

**Comment by heresyrj** [comment]
期待Mac

**Comment by guohui-ma** [comment]
来看一下西工大老铁,哈哈

**Comment by jiangyong1998** [comment]
Mac哪里领
