### ISSUE TITLE
内容乱码了怎么处理呢

### ISSUE THREAD

**Issue by 2020Waker** [LC044/WeChatMsg#67]
**bug描述**

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/30645361/ce62e652-8723-419b-9ed5-35b8bc68ca5f)

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**

**Comment by mingchen3398** [comment]
可以看下这个 
https://github.com/LC044/WeChatMsg/issues/40
