### ISSUE TITLE
年度分析报告第二页溢出

### ISSUE THREAD

**Issue by qaq112233** [LC044/WeChatMsg#69]
**bug描述**
年度分析报告第二页溢出，文字量太多了
**报错截图**
![PixPin_2023-12-06_00-22-55](https://github.com/LC044/WeChatMsg/assets/84634293/f9f8cbab-2231-4ea0-9da1-7ead8a0186cb)

**是否可复现**
是

**Additional context**
做个判断，字数太多只显示前几行大概就好了

顺便提个大部分人可能用不到的功能：统计时只统计指定字数以下的信息，不统计特别长的。学生党有时候会聊天框发文章，全都被统计进去了......
但这只是个可有可无的功能，其他功能完善以后再考虑考虑吧

**Comment by LC044** [comment]
已解决
