### ISSUE TITLE
内存溢出，运行内存就占用满了，32g的

### ISSUE THREAD

**Issue by hlws** [LC044/WeChatMsg#70]
**bug描述**
内存溢出，运行内存就占用满了，32g的
年度报告无法生成

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/17338029/df0fa589-a600-41e9-986f-93d1aa7b221f)
![image](https://github.com/LC044/WeChatMsg/assets/17338029/0c4820ff-8465-4c82-b90d-6afb34bc66b0)

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**

**Comment by lewisxhe** [comment]
引用README ， 有没有从自身找原因，这么多年了，有没有努力，内存容量涨没涨
![5c4b5ed619b6e94a54f6ffaeefa365c](https://github.com/LC044/WeChatMsg/assets/22990954/579ae316-068e-41f2-b81d-e937c2615b97)

**Comment by hlws** [comment]
等晚上换服务器跑

**Comment by mingchen3398** [comment]
0.2.6
python:3.10.9
OS:win 10
微信版本3.9.8.15
软件内存占用400M
5800h+16G,可以查看与好友的年度报告
![image](https://github.com/LC044/WeChatMsg/assets/32698103/9dd6c62a-6754-4151-a3fc-e4b3c4299f78)
![image](https://github.com/LC044/WeChatMsg/assets/32698103/3ef5e614-ccdc-4711-95c2-226dcc6d0e23)

**Comment by WeileiZeng** [comment]
为什么会需要占用这么大的内存？感觉内存应该很好优化吧

**Comment by LC044** [comment]
> 0.2.6 python:3.10.9 OS:win 10 微信版本3.9.8.15 软件内存占用400M 5800h+16G,可以查看与好友的年度报告 ![image](https://private-user-images.githubusercontent.com/32698103/288252131-9dd6c62a-6754-4151-a3fc-e4b3c4299f78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzAwMDAsIm5iZiI6MTcwMTg2OTcwMCwicGF0aCI6Ii8zMjY5ODEwMy8yODgyNTIxMzEtOWRkNmM2MmEtNjc1NC00MTUxLWEzZmMtZTRiM2M0Mjk5Zjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzMzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NjNkODVkMTg0NzgxNTE4ZjQ2YWJlMzk1N2Y2OTNmNTAxMDk4YjRiODFjZjk1OTM3ODczZGU4YmEzY2ZlZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MUR_CwuAJ6uBjAh_HdyVhqJRxHv3sW0ttMgL5Dwmdig) ![image](https://private-user-images.githubusercontent.com/32698103/288252215-3ef5e614-ccdc-4711-95c2-226dcc6d0e23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzAwMDAsIm5iZiI6MTcwMTg2OTcwMCwicGF0aCI6Ii8zMjY5ODEwMy8yODgyNTIyMTUtM2VmNWU2MTQtY2NkYy00NzExLTk1YzItMjI2ZGNjNmQwZTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzMzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MzVhYTU0ODRmNjA0MDUyZDY5NWU5MWI0ZjQ2NmM4MTBlMDhiZWU1Yjc5ZDQyYTQ5ZjU3NWYwYWYyMTA3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BA05gt1XW3rvmdLaTNe0U5W5CsTVCQ0qsY2njjpEXBY)

四五百兆是正常的，其他溢出的可以反馈一下是哪里出问题了，我好优化
