### ISSUE TITLE
年度

### ISSUE THREAD

**Issue by 1-on** [LC044/WeChatMsg#72]
**bug描述**
打开年度报告出错
**报错截图**
![微信图片_20231206090908](https://github.com/LC044/WeChatMsg/assets/94747101/23a92631-5840-4210-8bc8-6564edcf876a)

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11] win11
 - Python版本:  3.10.9
 - 软件版本:  0.2.6
 - 微信版本:3.9.8.15

**Additional context**

**Comment by LC044** [comment]
咱就是说，没有聊过天的就别分析了，找个经常聊天的人分析吧

**Comment by LC044** [comment]
已解决
