### ISSUE TITLE
解密数据库报错

### ISSUE THREAD

**Issue by daimiaopeng** [LC044/WeChatMsg#73]
**bug描述**

**报错截图**
![_`Z@SW8P3O3N`OPQN`E{642](https://github.com/LC044/WeChatMsg/assets/32475719/8867bf83-3fee-4b33-b434-73870b91b038)

**是否可复现**
可以
**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 
 MemoTrace-0.2.6.exe
 - 微信版本:
微信3.9.8.15
**Additional context**

**Comment by changsen-dev** [comment]
![)CRRRETN(PL8TQECR@W`CHD](https://github.com/LC044/WeChatMsg/assets/59425847/837e7ddf-b8e0-43d1-8481-4dc4ccbe94db)
