### ISSUE TITLE
不能支持视频&语音么

### ISSUE THREAD

**Issue by qzqsmile** [LC044/WeChatMsg#76]
rt

**Comment by STDquantum** [comment]
希望速速~(￣▽￣)~*

视频我不知道

语音的话MediaMSG0.db那种里面的Buf就是.silk类型的文件，可以保存到文件然后

```python
import pilk
def decodeSilk(path):
    pilk.decode(path, "test.pcm", 44100)
    os.system(f"ffmpeg.exe -y -f s16le -i test.pcm -ar 44100 -ac 1 test.mp3")
```

**Comment by fcwys** [comment]
ffmpeg可以不用打包到程序吧

**Comment by STDquantum** [comment]
> ffmpeg可以不用打包到程序吧

这个我不太清楚，我只会写代码（

**Comment by fcwys** [comment]
ffmpeg有二进制程序，很方便的，可以不用内嵌到程序
http://www.ffmpeg.org/download.html

**Comment by imamiao** [comment]
一个是可以ffmpeg二进制直接下载；另一个是自定义编译，只保留需要的编解码器，编译出来可能只有几兆。

**Comment by xiaoguyu** [comment]
MSG表 Type=34 为语音类型数据
对应关系为 MSG表的MsgSvrID = Media表的Reserved0

**Comment by STDquantum** [comment]
> MSG表 Type=34 为语音类型数据 对应关系为 MSG表的MsgSvrID = Media表的Reserved0

谢谢，其实在代码里已经实现完成了

**Comment by LC044** [comment]
已支持
