### ISSUE TITLE
优化聊天记录文件的存储结构

### ISSUE THREAD

**Issue by STDquantum** [LC044/WeChatMsg#81]
现在的导出html聊天记录时候，文件夹里只有头像和html，而image和什么别的文件都存在上一层，这样感觉想要提取一个人的聊天记录相当不方便啊，而且导出几个人的就会让data/image相当大了，是不是可以考虑优化一下存储结构，比如
----| data
--------| 聊天记录
-------------| 某个人的文件夹
-------------------| 这个人的视频
-------------------| 这个人的语音
-------------------| 这个人的图片
-------------------| 表情包
-------------------| 这个人.html

**Comment by LC044** [comment]
已实现，感谢提建议
