### ISSUE TITLE
【礼貌提问】：请问这个聊天记录是所有的聊天记录吗？如果手机聊天记录清空了，同步到电脑应该就不存在内容了吧

### ISSUE THREAD

**Issue by CherishMvp** [LC044/WeChatMsg#85]
请问这个聊天记录是所有的聊天记录吗？如果手机聊天记录清空了，同步到电脑应该就不存在内容了吧

**Comment by LC044** [comment]
微信聊天记录迁移功能，保留两个设备的全部聊天记录，最终显示合并后的数据

**Comment by CherishMvp** [comment]
> 微信聊天记录迁移功能，保留两个设备的全部聊天记录，最终显示合并后的数据

好的。我以为这个数据库是微信包括过往的所有的聊天记录。
