### ISSUE TITLE
点击年度报告就提示，Python已停止工作

### ISSUE THREAD

**Issue by hlws** [LC044/WeChatMsg#90]
**bug描述**

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/17338029/f785a96b-55c4-4834-b1b1-7fe85e68b2b2)

**是否可复现**

**运行环境:**
 - OS: [e.g. Win11]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**

**Comment by LC044** [comment]
有更详细的报错信息吗

**Comment by hlws** [comment]
> 有更详细的报错信息吗

没有其他报错信息了，换成exe文件直接运行不报错，上面报错是源码直接运行报出来的

**Comment by LC044** [comment]
应该是你的Python的问题，可直接下载exe程序运行
