### ISSUE TITLE
请问能否做成无需管理员权限

### ISSUE THREAD

**Issue by jonozw** [LC044/WeChatMsg#91]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

我没有管理员权限, 只是解数据库一定需要管理员权限吗? 
请问能否出一个无需管理员权限的版本, 或者说没权限的时候, 提示退出也行? 
而不是上来就要管理员权限? 

谢谢

**Comment by LC044** [comment]
按理说你把exe程序放在一个可以自由创建文件夹的路径下是可以不需要管理员权限的，或者你手动创建需要的文件夹

**Comment by jonozw** [comment]
好的, 谢谢, 我去尝试一下

**Comment by LC044** [comment]
可以不
