### ISSUE TITLE
聊天记录无法显示图片和表情包

### ISSUE THREAD

**Issue by microrole** [LC044/WeChatMsg#92]
**bug描述**
功能一切正常，但是导出html和「聊天」界面里的聊天记录无法显示对方的头像、表情包和图片
![image](https://github.com/LC044/WeChatMsg/assets/152576234/2e954b27-b254-48d6-a50e-b33e02f455c8)
![image](https://github.com/LC044/WeChatMsg/assets/152576234/fcaa7795-6293-4b5d-868f-5679b6bff73e)

**报错截图**

**是否可复现**

**运行环境:**
 - OS: Win11
 - Python版本: 3.10.11
 - 软件版本: 0.2.6
 - 微信版本: 3.9.8.15

**Comment by LC044** [comment]
导出HTML可解决该问题
