### ISSUE TITLE
是否需要增加异常判断

### ISSUE THREAD

**Issue by hlws** [LC044/WeChatMsg#93]
**bug描述**
查看年度报告，如果选择一个本年度没有聊天记录的好友查看，会出异常

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/17338029/0b1e4237-3ca7-4e27-98ab-34f81bb6aa8e)

**是否可复现**
是
**运行环境:**
 - OS: [e.g. Win11]
 - win10
 - Python版本:
 - 软件版本: 
 - 0.2.6
 - 微信版本:

**Additional context**

**Comment by LC044** [comment]
最新代码已经修复该问题，暂未打包发布
