### ISSUE TITLE
解密后，再次打开就再也打不开了

### ISSUE THREAD

**Issue by HDXP** [LC044/WeChatMsg#98]
**bug描述**
2023-12-07 17:25:32,338 - main_pc.py[line:66] - ERROR: None

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/12638805/ad1a144d-7342-44c7-b139-fc9f3d4686c2)

**是否可复现**
是，再也打不开了
**运行环境:**
 - OS: Win11
 - Python版本:3.12.0
 - 软件版本: 0.2.6
 - 微信版本:3.9.8.15

**Additional context**

**Comment by LC044** [comment]
这是不是你新建的小号啊，多加几个好友，完善个人信息，加几个群聊试试该问题能否解决

**Comment by lx11573** [comment]
是小号的问题吗？ 我0.2.7依然有这个问题，好友几十个，群少一点

**Comment by dali-wa** [comment]
+1同样的问题。  报错：2023-12-12 09:19:31,438 - main_pc.py[line:66] - ERROR: None

**Comment by LC044** [comment]
解决方案可参考#136
